/**
 * ui-stats-organism — StatsOrganism — UI factory (1:1 with the @almadar/ui stats-organism pattern).
 *
 * Autogenerated by almadar-sync std-ts from
 * packages/almadar-std/behaviors/registry/organisms/ui-stats-organism.orb.
 *
 * This is a thin descriptor layer over the canonical .orb. The exported
 * functions return TraitReference / PageRefObject / OrbitalDefinition
 * payloads that reference the sibling .orb via `uses:` + `ref:`. The
 * compiler's inline phase materialises the real trait at build time.
 *
 * Do not hand-edit — regenerate via
 *   npx almadar-sync std-ts --only=ui-stats-organism
 *
 * @level organism
 * @packageDocumentation
 */

import type { TraitReference, PageRefObject, OrbitalDefinition, Entity, EntityField, EntityPersistence, TraitConfig, TraitFieldRef, EntityRow, SExpr, TraitEventListener, Trait, StateMachine, Page } from '@almadar/core/types';
import type { MakeTraitRefOpts } from '@almadar/core/builders';
import { makeTraitRef, makePageRef, makeOrbitalWithUses } from '@almadar/core/builders';
import { rebindInlineTraitEntity, mergeCallSiteConfigOverrides } from '../../../../../factory-runtime/apply-params-to-orb.js';

const BEHAVIOR_PATH = 'std/behaviors/ui-stats-organism';
const ALIAS = 'UiStatsOrganism';

/**
 * Closed set of event keys this trait recognises —
 * derived from the .orb's `stateMachine.events[]` block
 * (transition triggers + emit names). Use as the key type
 * when passing an `events:` rename map at the call site.
 */
export type StdUiStatsOrganismEventKey = 'INIT' | 'StatsOrganismLoaded';

/**
 * Payload shape for the `StatsOrganismLoaded` event.
 */
export interface StdUiStatsOrganismStatsOrganismLoadedPayload {
  data?: EntityRow[];
}

/**
 * Typed call-site config block for this trait — every
 * field maps to a `config { ... }` entry in the source
 * .lolo. The agent fills these to specialise the trait
 * without modifying its state-machine topology.
 */
export interface StdUiStatsOrganismConfig {
  /** Default: `{}` */
  activeFilters?: unknown;
  /** Default: `""` */
  className?: string;
  /** Default: `3` */
  columns?: number;
  error?: EntityRow;
  /** Default: `false` */
  isLoading?: boolean;
  /** Default: `0` */
  pageProp?: number;
  /** Default: `0` */
  pageSize?: number;
  /** Default: `""` */
  searchValue?: string;
  /** Default: `[]` */
  selectedIds?: string[];
  /** Default: `""` */
  sortBy?: string;
  /** Default: `"asc"` */
  sortDirection?: 'asc' | 'desc';
  /** Default: `0` */
  totalCount?: number;
}

type _StdUiStatsOrganismEntityName = 'StatsOrganismItem';
type _StdUiStatsOrganismListenTraitName = 'StatsOrganismRender';

/**
 * Tunable params for the StatsOrganismOrbital orbital.
 *
 * Canonical entity: StatsOrganismItem — overridable via
 * `entityName`. The factory threads the effective name through every
 * trait's `linkedEntity` binding; the `.orb` compiler's inline phase
 * auto-rewrites every `@Entity.x`, `["ref",X]`, `["fetch",X,…]`,
 * `["persist",…,X,…]` and payload type string accordingly.
 *
 * Override surface (mirrors `.lolo`'s native overrides 1:1):
 *   fields         — extra entity fields (appended)
 *   pagePath       — first-page URL override
 *   entityName     — rename the canonical entity
 *   traitOverrides — per-imported-trait `config`, `linkedEntity`,
 *                    `events`, `name`, `emitsScope`, `listens`.
 *                    `effects` is NOT exposed — `.lolo` removed it
 *                    in Phase 9.5.H. Use `listens` via a sibling
 *                    trait to react to atom events.
 */
export interface StdUiStatsOrganismStatsOrganismOrbitalParams {
  /** Extra fields appended to the canonical entity. */
  fields?: EntityField[];
  /** URL path override for the orbital's first page. */
  pagePath?: string;
  /** Rename the canonical entity (PascalCase singular, ≤32 chars). */
  entityName?: string;
  /**
   * Per-imported-trait override surface keyed on each imported
   * trait's canonical `name`. Accepts every override `.lolo`
   * natively supports: `config`, `linkedEntity`, `events`,
   * `name`, `emitsScope`, `listens`. `effects` is excluded —
   * atom-owned (use `listens` via a sibling trait instead).
   */
  traitOverrides?: Partial<Record<
    'StatsOrganismRender',
    Pick<MakeTraitRefOpts, 'config' | 'linkedEntity' | 'events' | 'name' | 'emitsScope' | 'listens'>
  >>;
}

/** `'Alias.traits.TraitName'` literal union of every trait StatsOrganismOrbital's `uses[]` exports. */
type _StdUiStatsOrganismStatsOrganismOrbitalUsesRef = never;

/** Per-orbital factory: builds the StatsOrganismOrbital orbital with consumer params. */
export function stdUiStatsOrganismStatsOrganismOrbital(params: StdUiStatsOrganismStatsOrganismOrbitalParams = {}): OrbitalDefinition {
  const canonicalName = params.entityName ?? 'StatsOrganismItem';
  const built = makeOrbitalWithUses({
    name: 'StatsOrganismOrbital',
    uses: [],
    entity: {
      name: canonicalName,
      persistence: 'runtime',
      fields: ((): EntityField[] => {
        const canonical: EntityField[] = [
          {
            'name': 'id',
            'required': true,
            'type': 'string',
          },
          {
            'default': 'Value',
            'name': 'value',
            'type': 'string',
          },
          {
            'default': 'Label',
            'name': 'label',
            'type': 'string',
          },
        ];
        const extras = params.fields ?? [];
        if (extras.length === 0) return canonical;
        const extraNames = new Set(extras.map((f) => f.name));
        return [...canonical.filter((f) => !extraNames.has(f.name)), ...extras];
      })(),
    } as Entity,
    traits: [
      rebindInlineTraitEntity({
        'category': 'interaction',
        'config': {
          'activeFilters': {
            'default': {},
            'description': 'Active filters',
            'label': 'Active Filters',
            'tier': 'presentation',
            'type': 'json',
          },
          'className': {
            'default': '',
            'description': 'Additional CSS classes',
            'label': 'Class Name',
            'tier': 'presentation',
            'type': 'string',
          },
          'columns': {
            'default': 3,
            'description': 'columns prop',
            'label': 'Columns',
            'tier': 'presentation',
            'type': 'number',
          },
          'error': {
            'description': 'Error state (UiError)',
            'label': 'Error',
            'properties': {
              'code': {
                'name': 'code',
                'required': false,
                'type': 'string',
              },
              'message': {
                'name': 'message',
                'required': true,
                'type': 'string',
              },
              'name': {
                'name': 'name',
                'required': false,
                'type': 'string',
              },
              'stack': {
                'name': 'stack',
                'required': false,
                'type': 'string',
              },
            },
            'tier': 'presentation',
            'type': 'StatsOrganismError',
          },
          'isLoading': {
            'default': false,
            'description': 'Loading state indicator',
            'label': 'Is Loading',
            'tier': 'presentation',
            'type': 'boolean',
          },
          'pageProp': {
            'default': 0,
            'description': 'Current page number',
            'label': 'Page',
            'synonyms': 'page',
            'tier': 'presentation',
            'type': 'number',
          },
          'pageSize': {
            'default': 0,
            'description': 'Number of items per page',
            'label': 'Page Size',
            'tier': 'presentation',
            'type': 'number',
          },
          'searchValue': {
            'default': '',
            'description': 'Current search query value',
            'label': 'Search Value',
            'tier': 'presentation',
            'type': 'string',
          },
          'selectedIds': {
            'default': [],
            'description': 'Currently selected item IDs',
            'items': {
              'type': 'string',
            },
            'label': 'Selected Ids',
            'tier': 'presentation',
            'type': '[string]',
          },
          'sortBy': {
            'default': '',
            'description': 'Current sort field',
            'label': 'Sort By',
            'tier': 'presentation',
            'type': 'string',
          },
          'sortDirection': {
            'default': 'asc',
            'description': 'Current sort direction',
            'label': 'Sort Direction',
            'tier': 'presentation',
            'type': 'string',
            'values': [
              'asc',
              'desc',
            ],
          },
          'totalCount': {
            'default': 0,
            'description': 'Total number of items',
            'label': 'Total Count',
            'tier': 'presentation',
            'type': 'number',
          },
        },
        'emits': [
          {
            'description': 'StatsOrganism rows finished loading; payload.data holds the collection.',
            'event': 'StatsOrganismLoaded',
            'payloadSchema': [
              {
                'name': 'data',
                'type': '[StatsOrganismItem]',
              },
            ],
            'scope': 'internal',
            'synonyms': 'loaded, fetched, retrieved',
            'tier': 'essential',
          },
        ],
        'entityContract': {
          'provides': [],
          'requires': [],
        },
        'entityRebindable': true,
        'linkedEntity': 'StatsOrganismItem',
        'name': 'StatsOrganismRender',
        'scope': 'instance',
        'stateMachine': {
          'events': [
            {
              'key': 'INIT',
              'name': 'Initialize',
            },
            {
              'description': 'StatsOrganism rows finished loading; payload.data holds the collection.',
              'key': 'StatsOrganismLoaded',
              'name': 'Stats organism loaded',
              'payloadSchema': [
                {
                  'name': 'data',
                  'type': '[StatsOrganismItem]',
                },
              ],
              'synonyms': 'loaded, fetched, retrieved',
              'tier': 'essential',
            },
          ],
          'states': [
            {
              'isInitial': true,
              'name': 'idle',
            },
          ],
          'transitions': [
            {
              'effects': [
                [
                  'fetch',
                  ('StatsOrganismItem' satisfies _StdUiStatsOrganismEntityName),
                  {
                    'emit': {
                      'success': 'StatsOrganismLoaded',
                    },
                  },
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'activeFilters': '@config.activeFilters',
                    'className': '@config.className',
                    'columns': '@config.columns',
                    'entity': '@entity',
                    'error': '@config.error',
                    'isLoading': '@config.isLoading',
                    'page': '@config.pageProp',
                    'pageSize': '@config.pageSize',
                    'searchValue': '@config.searchValue',
                    'selectedIds': '@config.selectedIds',
                    'sortBy': '@config.sortBy',
                    'sortDirection': '@config.sortDirection',
                    'totalCount': '@config.totalCount',
                    'type': 'stats-organism',
                  },
                ],
              ],
              'event': 'INIT',
              'from': 'idle',
              'to': 'idle',
            },
            {
              'effects': [
                [
                  'render-ui',
                  'main',
                  {
                    'activeFilters': '@config.activeFilters',
                    'className': '@config.className',
                    'columns': '@config.columns',
                    'entity': '@payload.data',
                    'error': '@config.error',
                    'isLoading': '@config.isLoading',
                    'page': '@config.pageProp',
                    'pageSize': '@config.pageSize',
                    'searchValue': '@config.searchValue',
                    'selectedIds': '@config.selectedIds',
                    'sortBy': '@config.sortBy',
                    'sortDirection': '@config.sortDirection',
                    'totalCount': '@config.totalCount',
                    'type': 'stats-organism',
                  },
                ],
              ],
              'event': 'StatsOrganismLoaded',
              'from': 'idle',
              'to': 'idle',
            },
          ],
        },
      } satisfies Trait, 'StatsOrganismItem', canonicalName),
    ],
    pages: [
      {
        'name': 'StatsOrganismPage',
        'path': '/stats-organism',
        'traits': [
          {
            'ref': 'StatsOrganismRender',
          },
        ],
      } satisfies Page,
    ],
  });
  type _OrbTrait = OrbitalDefinition["traits"][number];
  type _OrbPage = NonNullable<OrbitalDefinition["pages"]>[number];
  type _RefOverride = Pick<MakeTraitRefOpts, "config" | "linkedEntity" | "events" | "name" | "emitsScope" | "listens">;
  if (built.traits && params.traitOverrides !== undefined) {
    built.traits = (built.traits as _OrbTrait[]).map((t): _OrbTrait => {
      if (!t || typeof t !== "object") return t;
      const tr = t as TraitReference & { name?: string };
      // Match by name so inline traits (no `ref`) and
      // reference traits (with `ref`) both pick up the
      // override surface keyed on the trait's `name`.
      if (typeof tr.name !== "string") return t;
      const overrides = params.traitOverrides as Record<string, _RefOverride | undefined> | undefined;
      const override = overrides?.[tr.name];
      if (!override) return t;
      const merged: TraitReference = { ...tr };
      if (override.config !== undefined) {
        merged.config = mergeCallSiteConfigOverrides(tr.config ?? {}, override.config);
      }
      if (override.linkedEntity !== undefined) merged.linkedEntity = override.linkedEntity;
      if (override.events !== undefined) merged.events = { ...(tr.events ?? {}), ...override.events };
      if (override.emitsScope !== undefined) merged.emitsScope = override.emitsScope;
      if (override.listens !== undefined) merged.listens = override.listens;
      return merged;
    });
  }
  if (built.pages && params.pagePath !== undefined) {
    built.pages = (built.pages as _OrbPage[]).map((p, idx) => {
      if (!p || typeof p !== "object") return p;
      if (idx !== 0) return p;
      const out = { ...p } as _OrbPage & { path?: string };
      out.path = params.pagePath;
      return out;
    });
  }
  return built;
}

/** Manifest — describes the params surface of stdUiStatsOrganismStatsOrganismOrbital. */
export const StdUiStatsOrganismStatsOrganismOrbitalManifest = {
  organism: 'ui-stats-organism',
  orbitalName: 'StatsOrganismOrbital',
  paramFields: [
    { name: 'fields', type: 'EntityField[]', description: 'Extra fields appended to the canonical entity.' },
    { name: 'pagePath', type: 'string', description: 'URL override for the orbital first page.' },
    { name: 'entityName', type: 'string', description: 'Rename the canonical entity. PascalCase singular, ≤32 chars. Threads through every trait\'s linkedEntity binding; compiler rewrites @Entity.x refs.' },
    { name: 'traitOverrides', type: "Partial<Record<TraitName, { config?, linkedEntity?, events?, name?, emitsScope?, listens? }>>", description: 'Per-imported-trait overrides — mirrors .lolo\'s native trait-composition surface 1:1. effects is excluded (atom-owned; use listens via a sibling trait).' },
  ] as const,
  traitNames: [
  ] as const,
  inlineTraitNames: [
    'StatsOrganismRender',
  ] as const,
};

/** Typed guard — runtime validates StdUiStatsOrganismStatsOrganismOrbitalParams keys. */
export function isStdUiStatsOrganismStatsOrganismOrbitalParams(p: object): p is StdUiStatsOrganismStatsOrganismOrbitalParams {
  type _OverrideRecord = NonNullable<StdUiStatsOrganismStatsOrganismOrbitalParams['traitOverrides']>;
  const obj = p as { traitOverrides?: _OverrideRecord };
  if (obj.traitOverrides !== undefined) {
    if (typeof obj.traitOverrides !== "object" || obj.traitOverrides === null) return false;
    const allowed: readonly string[] = [
      ...StdUiStatsOrganismStatsOrganismOrbitalManifest.traitNames,
      ...StdUiStatsOrganismStatsOrganismOrbitalManifest.inlineTraitNames,
    ];
    for (const k of Object.keys(obj.traitOverrides)) {
      if (!allowed.includes(k)) return false;
    }
  }
  return true;
}

/**
 * Bundled params for ui-stats-organism — one optional entry per orbital.
 * Each entry maps to its per-orbital factory above.
 */
export interface StdUiStatsOrganismParams {
  StatsOrganism?: StdUiStatsOrganismStatsOrganismOrbitalParams;
}

/** Whole-organism descriptor (1 orbitals). Composes per-orbital factories. */
export function stdUiStatsOrganism(params: StdUiStatsOrganismParams = {}): OrbitalDefinition[] {
  return [
    stdUiStatsOrganismStatsOrganismOrbital(params.StatsOrganism ?? {}),
  ];
}
