/**
 * Validate Module - Input Validation
 *
 * Provides validation functions for form inputs and data.
 * Returns true/false for single validations.
 * validate/check returns { valid: boolean, errors: [...] } for multiple rules.
 *
 * @packageDocumentation
 */

import type { StdOperatorMeta } from '../types.js';

/**
 * Validate module operators.
 * All operators return boolean or validation result objects and have no side effects.
 */
export const VALIDATE_OPERATORS: Record<string, StdOperatorMeta> = {
  'validate/required': {
    module: 'validate',
    category: 'std-validate',
    minArity: 1,
    maxArity: 1,
    description: 'Check if value is not null, undefined, or empty string',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [{ name: 'value', type: 'any', description: 'Value to check' }],
    example: '["validate/required", "Ann"]',
  },
  'validate/string': {
    module: 'validate',
    category: 'std-validate',
    minArity: 1,
    maxArity: 1,
    description: 'Check if value is a string',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [{ name: 'value', type: 'any', description: 'Value to check' }],
    example: '["validate/string", "Ann"]',
  },
  'validate/number': {
    module: 'validate',
    category: 'std-validate',
    minArity: 1,
    maxArity: 1,
    description: 'Check if value is a number',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [{ name: 'value', type: 'any', description: 'Value to check' }],
    example: '["validate/number", 42]',
  },
  'validate/boolean': {
    module: 'validate',
    category: 'std-validate',
    minArity: 1,
    maxArity: 1,
    description: 'Check if value is a boolean',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [{ name: 'value', type: 'any', description: 'Value to check' }],
    example: '["validate/boolean", true]',
  },
  'validate/array': {
    module: 'validate',
    category: 'std-validate',
    minArity: 1,
    maxArity: 1,
    description: 'Check if value is an array',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [{ name: 'value', type: 'any', description: 'Value to check' }],
    example: '["validate/array", [1, 2]]',
  },
  'validate/object': {
    module: 'validate',
    category: 'std-validate',
    minArity: 1,
    maxArity: 1,
    description: 'Check if value is an object',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [{ name: 'value', type: 'any', description: 'Value to check' }],
    example: '["validate/object", {"a": 1}]',
  },
  'validate/email': {
    module: 'validate',
    category: 'std-validate',
    minArity: 1,
    maxArity: 1,
    description: 'Check if value is a valid email format',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [{ name: 'value', type: 'string', description: 'Email to validate' }],
    example: '["validate/email", "ann@example.com"]',
  },
  'validate/url': {
    module: 'validate',
    category: 'std-validate',
    minArity: 1,
    maxArity: 1,
    description: 'Check if value is a valid URL format',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [{ name: 'value', type: 'string', description: 'URL to validate' }],
    example: '["validate/url", "https://example.com"]',
  },
  'validate/uuid': {
    module: 'validate',
    category: 'std-validate',
    minArity: 1,
    maxArity: 1,
    description: 'Check if value is a valid UUID',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [{ name: 'value', type: 'string', description: 'UUID to validate' }],
    example: '["validate/uuid", "550e8400-e29b-41d4-a716-446655440000"]',
  },
  'validate/phone': {
    module: 'validate',
    category: 'std-validate',
    minArity: 1,
    maxArity: 1,
    description: 'Check if value is a valid phone number',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [{ name: 'value', type: 'string', description: 'Phone number to validate' }],
    example: '["validate/phone", "+15551234567"]',
  },
  'validate/creditCard': {
    module: 'validate',
    category: 'std-validate',
    minArity: 1,
    maxArity: 1,
    description: 'Check if value is a valid credit card number (Luhn algorithm)',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [{ name: 'value', type: 'string', description: 'Card number to validate' }],
    example: '["validate/creditCard", "4111111111111111"]',
  },
  'validate/date': {
    module: 'validate',
    category: 'std-validate',
    minArity: 1,
    maxArity: 1,
    description: 'Check if value is a valid date',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [{ name: 'value', type: 'any', description: 'Value to check' }],
    example: '["validate/date", "2024-01-18"]',
  },
  'validate/minLength': {
    module: 'validate',
    category: 'std-validate',
    minArity: 2,
    maxArity: 2,
    description: 'Check if string/array has minimum length',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [
      { name: 'value', type: 'string | array', description: 'Value to check' },
      { name: 'min', type: 'number', description: 'Minimum length' },
    ],
    example: '["validate/minLength", "password123", 8]',
  },
  'validate/maxLength': {
    module: 'validate',
    category: 'std-validate',
    minArity: 2,
    maxArity: 2,
    description: 'Check if string/array has maximum length',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [
      { name: 'value', type: 'string | array', description: 'Value to check' },
      { name: 'max', type: 'number', description: 'Maximum length' },
    ],
    example: '["validate/maxLength", "Ann", 50]',
  },
  'validate/length': {
    module: 'validate',
    category: 'std-validate',
    minArity: 2,
    maxArity: 2,
    description: 'Check if string/array has exact length',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [
      { name: 'value', type: 'string | array', description: 'Value to check' },
      { name: 'exact', type: 'number', description: 'Required length' },
    ],
    example: '["validate/length", "ABC123", 6]',
  },
  'validate/min': {
    module: 'validate',
    category: 'std-validate',
    minArity: 2,
    maxArity: 2,
    description: 'Check if number is >= minimum',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [
      { name: 'value', type: 'number', description: 'Number to check' },
      { name: 'min', type: 'number', description: 'Minimum value' },
    ],
    example: '["validate/min", 21, 18]',
  },
  'validate/max': {
    module: 'validate',
    category: 'std-validate',
    minArity: 2,
    maxArity: 2,
    description: 'Check if number is <= maximum',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [
      { name: 'value', type: 'number', description: 'Number to check' },
      { name: 'max', type: 'number', description: 'Maximum value' },
    ],
    example: '["validate/max", 50, 100]',
  },
  'validate/range': {
    module: 'validate',
    category: 'std-validate',
    minArity: 3,
    maxArity: 3,
    description: 'Check if number is within range [min, max]',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [
      { name: 'value', type: 'number', description: 'Number to check' },
      { name: 'min', type: 'number', description: 'Minimum value' },
      { name: 'max', type: 'number', description: 'Maximum value' },
    ],
    example: '["validate/range", 4, 1, 5]',
  },
  'validate/pattern': {
    module: 'validate',
    category: 'std-validate',
    minArity: 2,
    maxArity: 2,
    description: 'Check if string matches regex pattern',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [
      { name: 'value', type: 'string', description: 'String to check' },
      { name: 'regex', type: 'string', description: 'Regex pattern' },
    ],
    example: '["validate/pattern", "ABC123", "^[A-Z]{3}[0-9]{3}$"]',
  },
  'validate/oneOf': {
    module: 'validate',
    category: 'std-validate',
    minArity: 2,
    maxArity: 2,
    description: 'Check if value is in list of allowed values',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [
      { name: 'value', type: 'any', description: 'Value to check' },
      { name: 'options', type: 'array', description: 'Allowed values' },
    ],
    example: '["validate/oneOf", "admin", ["admin", "user", "guest"]]',
  },
  'validate/noneOf': {
    module: 'validate',
    category: 'std-validate',
    minArity: 2,
    maxArity: 2,
    description: 'Check if value is not in list of disallowed values',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [
      { name: 'value', type: 'any', description: 'Value to check' },
      { name: 'options', type: 'array', description: 'Disallowed values' },
    ],
    example: '["validate/noneOf", "alice", ["admin", "root", "system"]]',
  },
  'validate/equals': {
    module: 'validate',
    category: 'std-validate',
    minArity: 2,
    maxArity: 2,
    description: 'Deep equality check',
    hasSideEffects: false,
    returnType: 'boolean',
    params: [
      { name: 'a', type: 'any', description: 'First value' },
      { name: 'b', type: 'any', description: 'Second value' },
    ],
    example: '["validate/equals", "secret", "secret"]',
  },
  'validate/check': {
    module: 'validate',
    category: 'std-validate',
    minArity: 2,
    maxArity: 2,
    description: 'Run multiple validation rules, return { valid, errors }',
    hasSideEffects: false,
    returnType: 'any',
    params: [
      { name: 'value', type: 'any', description: 'Value or object to validate' },
      { name: 'rules', type: 'object', description: 'Validation rules by field' },
    ],
    example: '["validate/check", {"name": "Ann", "email": "ann@example.com", "age": 20}, {"name": [["required"], ["minLength", 2], ["maxLength", 50]], "email": [["required"], ["email"]], "age": [["number"]]}]',
  },
};

/**
 * Get all validate operator names.
 */
export function getValidateOperators(): string[] {
  return Object.keys(VALIDATE_OPERATORS);
}
