/**
 * std-learn-live-sim — Generic continuous particle-dynamics instrument — the live-integration sibling of std-physics-projectile: config-declared initial bodies (position, velocity, radius, color) fall under gravity, lose speed to damping, and bounce off the world bounds every tick while Run is engaged; Pause freezes the simulation and Reset restores the initial bodies. Gravity and damping are each exposed as a range-slider so the learner can retune the dynamics live, with a readout of elapsed ticks and a sample body's current speed. So the same mechanism serves any bouncing-particle domain (gas molecules, falling objects, orbit sketches, and beyond) on a physics-canvas. Standalone by default; behind a lab router set matchMode and it renders only when MODE_SELECTED matches.
 *
 * Autogenerated by almadar-sync std-ts from
 * packages/almadar-std/behaviors/registry/atoms/std-learn-live-sim.orb.
 *
 * This is a thin descriptor layer over the canonical .orb. The exported
 * functions return TraitReference / PageRefObject / OrbitalDefinition
 * payloads that reference the sibling .orb via `uses:` + `ref:`. The
 * compiler's inline phase materialises the real trait at build time.
 *
 * Do not hand-edit — regenerate via
 *   npx almadar-sync std-ts --only=std-learn-live-sim
 *
 * @level atom
 * @packageDocumentation
 */

import type { TraitReference, PageRefObject, OrbitalDefinition, Entity, EntityRef, EntityField, EntityPersistence, TraitConfig, TraitFieldRef, EntityRow, SExpr, TraitEventListener, Trait, StateMachine, Page, PatternValue } from '@almadar/core/types';
import type { MakeTraitRefOpts } from '@almadar/core/builders';
import { makeTraitRef, makePageRef, makeOrbitalWithUses } from '@almadar/core/builders';
import { mergeCallSiteConfigOverrides } from '../../../../../factory-runtime/apply-params-to-orb.js';

const BEHAVIOR_PATH = 'std/behaviors/std-learn-live-sim';
const ALIAS = 'LearnLiveSim';

/**
 * Closed set of event keys this trait recognises —
 * derived from the .orb's `stateMachine.events[]` block
 * (transition triggers + emit names). Use as the key type
 * when passing an `events:` rename map at the call site.
 */
export type StdLearnLiveSimEventKey = 'INIT' | 'MODE_SELECTED' | 'PAUSE' | 'RESET' | 'RUN' | 'RUN_TOGGLED' | 'SET_DAMPING' | 'SET_GRAVITY' | 'SIM_RESET';

/**
 * Payload shape for the `RUN_TOGGLED` event.
 */
export interface StdLearnLiveSimRunToggledPayload {
  running?: boolean;
}

/**
 * Payload shape for the `SIM_RESET` event.
 */
export interface StdLearnLiveSimSimResetPayload {
  bodyCount?: number;
}

/**
 * Typed call-site config block for this trait — every
 * field maps to a `config { ... }` entry in the source
 * .lolo. The agent fills these to specialise the trait
 * without modifying its state-machine topology.
 */
export interface StdLearnLiveSimConfig {
  /** Default: `"#f8fafc"` */
  backgroundColor?: string;
  /** Default: `[{"color":"#2563eb","id":"ball-a","radius":14,"vx":4,"vy":0,"x":100,"y":60},{"color":"#16a34a","id":"ball-b","radius":18,"vx":-3,"vy":2,"x":260,"y":90},{"color":"#f59e0b","id":"ball-c","radius":11,"vx":2,"vy":-1,"x":420,"y":40}]` */
  bodies?: EntityRow[];
  /** Default: `0.995` */
  damping?: number;
  /** Default: `0.4` */
  gravity?: number;
  /** Default: `400` */
  height?: number;
  /** Default: `""` */
  matchMode?: string;
  /** Default: `0.78` */
  restitution?: number;
  /** Default: `false` */
  running?: boolean;
  /** Default: `true` */
  showVelocity?: boolean;
  /** Default: `"Live Sim"` */
  title?: string;
  /** Default: `8` */
  velocityScale?: number;
  /** Default: `600` */
  width?: number;
}

/**
 * Params for the std-learn-live-sim descriptor helpers.
 *
 * `entityName` binds every trait/page reference's `linkedEntity`.
 * The optional override fields mirror TraitReference / PageRefObject
 * fields and are forwarded to `makeTraitRef` / `makePageRef`.
 */
export interface StdLearnLiveSimParams {
  entityName: string;
  /** Extra fields to add to the orbital-scoped entity clone. */
  fields?: EntityField[];
  /** Rename the inlined trait at the call site. */
  traitName?: string;
  /** Per-key event rename map. Keys narrow to the trait's declared emit names. */
  events?: Partial<Record<StdLearnLiveSimEventKey, string>>;
  /** Per-event effect replacement (keys are POST-rename event names). */
  effects?: Record<string, SExpr[]>;
  /** Replace the imported trait's `listens` array entirely. */
  listens?: TraitEventListener[];
  /** Set every emit's scope. */
  emitsScope?: 'internal' | 'external';
  /** Typed call-site config block — see the per-field interface. */
  config?: StdLearnLiveSimConfig;
  /** URL path override for the (first) page. */
  pagePath?: string;
}

/** Trait descriptor: `LearnLiveSim.traits.LiveSimSim`. */
export function stdLearnLiveSimTrait(params: StdLearnLiveSimParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.LiveSimSim`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Page descriptor: `LearnLiveSim.pages.LearnLiveSimPage`. */
export function stdLearnLiveSimPage(params: StdLearnLiveSimParams): PageRefObject {
  return makePageRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.pages.LearnLiveSimPage`,
    ...(params.pagePath !== undefined ? { path: params.pagePath } : {}),
    linkedEntity: params.entityName,
  });
}

/** Whole-orbital descriptor. */
export function stdLearnLiveSim(params: StdLearnLiveSimParams): OrbitalDefinition {
  const entity: Entity = {
    name: params.entityName,
    fields: params.fields ?? [],
    persistence: 'runtime',
  };
  return makeOrbitalWithUses({
    name: 'LearnLiveSimOrbital',
    uses: [{ from: BEHAVIOR_PATH, as: ALIAS }],
    entity,
    traits: [
      stdLearnLiveSimTrait(params),
    ],
    pages: [
      stdLearnLiveSimPage(params),
    ],
  });
}
