/**
 * std-patient — std-patient — patient record management with PHI handling, consent gating, and status lifecycle. Listens for SET_STATUS so std-lifecycle can drive transitions.
 *
 * Autogenerated by almadar-sync std-ts from
 * packages/almadar-std/behaviors/registry/atoms/std-patient.orb.
 *
 * This is a thin descriptor layer over the canonical .orb. The exported
 * functions return TraitReference / PageRefObject / OrbitalDefinition
 * payloads that reference the sibling .orb via `uses:` + `ref:`. The
 * compiler's inline phase materialises the real trait at build time.
 *
 * Do not hand-edit — regenerate via
 *   npx almadar-sync std-ts --only=std-patient
 *
 * @level atom
 * @packageDocumentation
 */

import type { TraitReference, PageRefObject, OrbitalDefinition, Entity, EntityField, EntityPersistence, TraitConfig, TraitFieldRef, EntityRow, SExpr, TraitEventListener, Trait, StateMachine } from '@almadar/core/types';
import type { MakeTraitRefOpts } from '@almadar/core/builders';
import { makeTraitRef, makePageRef, makeOrbitalWithUses } from '@almadar/core/builders';
import { rebindInlineTraitEntity } from '../../../../factory-runtime/apply-params-to-orb.js';

const BEHAVIOR_PATH = 'std/behaviors/std-patient';
const ALIAS = 'Patient';

/**
 * Closed set of event keys this trait recognises —
 * derived from the .orb's `stateMachine.events[]` block
 * (transition triggers + emit names). Use as the key type
 * when passing an `events:` rename map at the call site.
 */
export type StdPatientEventKey = 'CLOSE_VIEW' | 'DEACTIVATE' | 'INIT' | 'OPEN_PATIENT' | 'PatientLoadFailed' | 'PatientLoaded' | 'PatientUpdateFailed' | 'PatientUpdated' | 'SET_STATUS';

/**
 * Payload shape for the `OPEN_PATIENT` event.
 */
export interface StdPatientOpenPatientPayload {
  id: string;
  row?: {
    id: string;
    firstName: string;
    lastName: string;
    dateOfBirth?: string;
    consentType?: string;
    mrn?: string;
    primaryProvider?: string;
    status?: string;
    createdAt?: string;
    updatedAt?: string;
  };
}

/**
 * Payload shape for the `DEACTIVATE` event.
 */
export interface StdPatientDeactivatePayload {
  id: string;
}

/**
 * Payload shape for the `PatientLoaded` event.
 */
export interface StdPatientPatientLoadedPayload {
  data?: EntityRow[];
}

/**
 * Payload shape for the `PatientLoadFailed` event.
 */
export interface StdPatientPatientLoadFailedPayload {
  error?: string;
  code?: string;
}

/**
 * Payload shape for the `PatientUpdated` event.
 */
export interface StdPatientPatientUpdatedPayload {
  row?: {
    id: string;
    firstName: string;
    lastName: string;
    dateOfBirth?: string;
    consentType?: string;
    mrn?: string;
    primaryProvider?: string;
    status?: string;
    createdAt?: string;
    updatedAt?: string;
  };
}

/**
 * Payload shape for the `PatientUpdateFailed` event.
 */
export interface StdPatientPatientUpdateFailedPayload {
  error?: string;
  code?: string;
}

/**
 * Typed call-site config block for this trait — every
 * field maps to a `config { ... }` entry in the source
 * .lolo. The agent fills these to specialise the trait
 * without modifying its state-machine topology.
 */
export interface StdPatientConfig {
  /** Default: `["emergency-physician","oncall-attending"]` */
  breakGlassRolesAllowed?: string[];
  /** Default: `[{"label":"Open","icon":"arrow-right","variant":"primary","event":"OPEN_PATIENT"},{"variant":"danger","label":"Deactivate","icon":"x","event":"DEACTIVATE"}]` */
  itemActions?: EntityRow[];
  /** Default: `"MRN-####-####"` */
  mrnFormat?: string;
  /** Default: `[{"label":"First name","name":"firstName","variant":"caption"},{"name":"lastName","variant":"caption","label":"Last name"},{"name":"mrn","label":"MRN","variant":"caption"},{"name":"primaryProvider","label":"Provider","variant":"caption"},{"name":"consentType","label":"Consent","variant":"badge"},{"label":"Status","variant":"badge","name":"status"}]` */
  fields?: EntityRow[];
  /** Default: `7` */
  defaultRecordRetentionYears?: number;
  /** Default: `["hipaa","treatment"]` */
  consentTypesRequired?: string[];
  /** Default: `true` */
  phiDisclosureLogRequired?: boolean;
  /** Default: `18` */
  parentalConsentMinorThresholdYears?: number;
  /** Default: `"household"` */
  dependentLinkagePolicy?: 'none' | 'household' | 'guardian';
  /** Default: `"Patients"` */
  title?: string;
  /** Default: `true` */
  pseudonymizeOnExport?: boolean;
}

/**
 * Params for the std-patient descriptor helpers.
 *
 * `entityName` binds every trait/page reference's `linkedEntity`.
 * The optional override fields mirror TraitReference / PageRefObject
 * fields and are forwarded to `makeTraitRef` / `makePageRef`.
 */
export interface StdPatientParams {
  entityName: string;
  /** Extra fields to add to the orbital-scoped entity clone. */
  fields?: EntityField[];
  /** Entity persistence mode. Defaults to `persistent` when omitted.
   *  See @almadar/core EntityPersistence: persistent | runtime | singleton | instance | local. */
  persistence?: EntityPersistence;
  /** Rename the inlined trait at the call site. */
  traitName?: string;
  /** Per-key event rename map. Keys narrow to the trait's declared emit names. */
  events?: Partial<Record<StdPatientEventKey, string>>;
  /** Per-event effect replacement (keys are POST-rename event names). */
  effects?: Record<string, SExpr[]>;
  /** Replace the imported trait's `listens` array entirely. */
  listens?: TraitEventListener[];
  /** Set every emit's scope. */
  emitsScope?: 'internal' | 'external';
  /** Typed call-site config block — see the per-field interface. */
  config?: StdPatientConfig;
  /** URL path override for the (first) page. */
  pagePath?: string;
}

/** Trait descriptor: `Patient.traits.PatientManage`. */
export function stdPatientTrait(params: StdPatientParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.PatientManage`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Page descriptor: `Patient.pages.PatientManagePage`. */
export function stdPatientPage(params: StdPatientParams): PageRefObject {
  return makePageRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.pages.PatientManagePage`,
    ...(params.pagePath !== undefined ? { path: params.pagePath } : {}),
    linkedEntity: params.entityName,
  });
}

/** Whole-orbital descriptor. */
export function stdPatient(params: StdPatientParams): OrbitalDefinition {
  const entity: Entity = {
    name: params.entityName,
    fields: params.fields ?? [],
    ...(params.persistence !== undefined ? { persistence: params.persistence } : {}),
  };
  return makeOrbitalWithUses({
    name: 'PatientOrbital',
    uses: [{ from: BEHAVIOR_PATH, as: ALIAS }],
    entity,
    traits: [
      stdPatientTrait(params),
    ],
    pages: [
      stdPatientPage(params),
    ],
  });
}
