/**
 * std-platformer-app — Platformer game: levels, score, and collectibles. Pick for side-scroller arcade games.
 *
 * Autogenerated by almadar-sync std-ts from
 * packages/almadar-std/behaviors/registry/organisms/std-platformer-app.orb.
 *
 * This is a thin descriptor layer over the canonical .orb. The exported
 * functions return TraitReference / PageRefObject / OrbitalDefinition
 * payloads that reference the sibling .orb via `uses:` + `ref:`. The
 * compiler's inline phase materialises the real trait at build time.
 *
 * Do not hand-edit — regenerate via
 *   npx almadar-sync std-ts --only=std-platformer-app
 *
 * @level organism
 * @packageDocumentation
 */

import type { TraitReference, PageRefObject, OrbitalDefinition, Entity, EntityField, EntityPersistence, TraitConfig, TraitFieldRef, EntityRow, SExpr, TraitEventListener, Trait, StateMachine } from '@almadar/core/types';
import type { MakeTraitRefOpts } from '@almadar/core/builders';
import { makeTraitRef, makePageRef, makeOrbitalWithUses } from '@almadar/core/builders';
import { rebindInlineTraitEntity } from '../../../../factory-runtime/apply-params-to-orb.js';

const BEHAVIOR_PATH = 'std/behaviors/std-platformer-app';
const ALIAS = 'PlatformerApp';

/**
 * Closed set of event keys this trait recognises —
 * derived from the .orb's `stateMachine.events[]` block
 * (transition triggers + emit names). Use as the key type
 * when passing an `events:` rename map at the call site.
 */
export type StdPlatformerAppEventKey = 'CLOSE' | 'CollectibleDeleteFailed' | 'CollectibleDeleted' | 'CollectibleSaveFailed' | 'CollectibleSaved' | 'CollectibleUpdateFailed' | 'CollectibleUpdated' | 'GAME_OVER' | 'INIT' | 'JUMP' | 'LEFT' | 'NAVIGATE' | 'PAUSE' | 'PlatLevelLoadFailed' | 'PlatLevelLoaded' | 'RESTART' | 'RESUME' | 'RIGHT' | 'START' | 'STOP';

/**
 * Payload shape for the `PlatLevelLoaded` event.
 */
export interface StdPlatformerAppPlatLevelLoadedPayload {
  data?: EntityRow[];
}

/**
 * Payload shape for the `PlatLevelLoadFailed` event.
 */
export interface StdPlatformerAppPlatLevelLoadFailedPayload {
  error?: string;
  code?: string;
}

/**
 * Payload shape for the `CollectibleSaved` event.
 */
export interface StdPlatformerAppCollectibleSavedPayload {
  id?: string;
}

/**
 * Payload shape for the `CollectibleSaveFailed` event.
 */
export interface StdPlatformerAppCollectibleSaveFailedPayload {
  error?: string;
  code?: string;
}

/**
 * Payload shape for the `CollectibleUpdated` event.
 */
export interface StdPlatformerAppCollectibleUpdatedPayload {
  id?: string;
}

/**
 * Payload shape for the `CollectibleUpdateFailed` event.
 */
export interface StdPlatformerAppCollectibleUpdateFailedPayload {
  error?: string;
  code?: string;
}

/**
 * Payload shape for the `CollectibleDeleted` event.
 */
export interface StdPlatformerAppCollectibleDeletedPayload {
  id?: string;
}

/**
 * Payload shape for the `CollectibleDeleteFailed` event.
 */
export interface StdPlatformerAppCollectibleDeleteFailedPayload {
  error?: string;
  code?: string;
}

/**
 * Tunable params for the PlatLevelOrbital orbital.
 *
 * Canonical entity: PlatLevel — overridable via
 * `entityName`. The factory threads the effective name through every
 * trait's `linkedEntity` binding; the `.orb` compiler's inline phase
 * auto-rewrites every `@Entity.x`, `["ref",X]`, `["fetch",X,…]`,
 * `["persist",…,X,…]` and payload type string accordingly.
 *
 * Override surface (mirrors `.lolo`'s native overrides 1:1):
 *   fields         — extra entity fields (appended)
 *   pagePath       — first-page URL override
 *   persistence    — entity persistence mode
 *   entityName     — rename the canonical entity
 *   collection     — override the derived collection key
 *   traitOverrides — per-imported-trait `config`, `linkedEntity`,
 *                    `events`, `name`, `emitsScope`, `listens`.
 *                    `effects` is NOT exposed — `.lolo` removed it
 *                    in Phase 9.5.H. Use `listens` via a sibling
 *                    trait to react to atom events.
 */
export interface StdPlatformerAppPlatLevelOrbitalParams {
  /** Extra fields appended to the canonical entity. */
  fields?: EntityField[];
  /** URL path override for the orbital's first page. */
  pagePath?: string;
  /** Override the canonical entity persistence mode. */
  persistence?: EntityPersistence;
  /** Rename the canonical entity (PascalCase singular, ≤32 chars). */
  entityName?: string;
  /** Override derived collection key (defaults to plural(entityName).toLowerCase()). */
  collection?: string;
  /**
   * Per-imported-trait override surface keyed on each imported
   * trait's canonical `name`. Accepts every override `.lolo`
   * natively supports: `config`, `linkedEntity`, `events`,
   * `name`, `emitsScope`, `listens`. `effects` is excluded —
   * atom-owned (use `listens` via a sibling trait instead).
   */
  traitOverrides?: Partial<Record<
    'PlatLevelPlatformerFlow' | 'PlatLevelPlatformerCanvas',
    Pick<MakeTraitRefOpts, 'config' | 'linkedEntity' | 'events' | 'name' | 'emitsScope' | 'listens'>
  >>;
}

/** Per-orbital factory: builds the PlatLevelOrbital orbital with consumer params. */
export function stdPlatformerAppPlatLevelOrbital(params: StdPlatformerAppPlatLevelOrbitalParams = {}): OrbitalDefinition {
  const canonicalName = params.entityName ?? 'PlatLevel';
  const built = makeOrbitalWithUses({
    name: 'PlatLevelOrbital',
    uses: [],
    entity: {
      name: canonicalName,
      persistence: params.persistence ?? 'runtime',
      fields: ((): EntityField[] => {
        const canonical: EntityField[] = [
          {
            'name': 'id',
            'type': 'string',
            'required': true,
          },
          {
            'name': 'level',
            'type': 'number',
            'default': 1,
          },
          {
            'name': 'score',
            'type': 'number',
            'default': 0,
          },
          {
            'name': 'lives',
            'type': 'number',
            'default': 3,
          },
          {
            'name': 'time',
            'type': 'number',
            'default': 0,
          },
          {
            'name': 'player',
            'type': 'object',
            'properties': {
              'facingRight': {
                'name': 'facingRight',
                'type': 'boolean',
                'required': false,
              },
              'grounded': {
                'name': 'grounded',
                'type': 'boolean',
                'required': false,
              },
              'vy': {
                'name': 'vy',
                'type': 'number',
                'required': false,
              },
              'height': {
                'name': 'height',
                'type': 'number',
                'required': false,
              },
              'x': {
                'name': 'x',
                'type': 'number',
                'required': false,
              },
              'y': {
                'name': 'y',
                'type': 'number',
                'required': false,
              },
              'width': {
                'name': 'width',
                'type': 'number',
                'required': false,
              },
              'vx': {
                'name': 'vx',
                'type': 'number',
                'required': false,
              },
            },
          },
          {
            'name': 'platforms',
            'type': 'array',
            'default': [],
            'items': {
              'type': 'object',
              'properties': {
                'height': {
                  'name': 'height',
                  'type': 'number',
                  'required': false,
                },
                'type': {
                  'name': 'type',
                  'type': 'string',
                  'required': false,
                },
                'y': {
                  'name': 'y',
                  'type': 'number',
                  'required': false,
                },
                'width': {
                  'name': 'width',
                  'type': 'number',
                  'required': false,
                },
                'x': {
                  'name': 'x',
                  'type': 'number',
                  'required': false,
                },
              },
            },
          },
        ];
        const extras = params.fields ?? [];
        if (extras.length === 0) return canonical;
        const extraNames = new Set(extras.map((f) => f.name));
        return [...canonical.filter((f) => !extraNames.has(f.name)), ...extras];
      })(),
    } as Entity,
    traits: [
      rebindInlineTraitEntity({
        'name': 'PlatLevelPlatformerFlow',
        'category': 'interaction',
        'linkedEntity': 'PlatLevel',
        'emits': [
          {
            'event': 'PlatLevelLoaded',
            'description': 'Fired when PlatLevel finishes loading',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'data',
                'type': '[PlatLevel]',
              },
            ],
          },
          {
            'event': 'PlatLevelLoadFailed',
            'description': 'Fired when PlatLevel fails to load',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'CollectibleSaved',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'id',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'CollectibleSaveFailed',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'CollectibleUpdated',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'id',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'CollectibleUpdateFailed',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'CollectibleDeleted',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'id',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'CollectibleDeleteFailed',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
          },
        ],
        'stateMachine': {
          'states': [
            {
              'name': 'menu',
              'isInitial': true,
            },
            {
              'name': 'playing',
            },
            {
              'name': 'paused',
            },
            {
              'name': 'gameover',
            },
          ],
          'events': [
            {
              'key': 'INIT',
              'name': 'Initialize',
            },
            {
              'key': 'START',
              'name': 'Start',
            },
            {
              'key': 'NAVIGATE',
              'name': 'Navigate',
            },
            {
              'key': 'LEFT',
              'name': 'Left',
            },
            {
              'key': 'RIGHT',
              'name': 'Right',
            },
            {
              'key': 'JUMP',
              'name': 'Jump',
            },
            {
              'key': 'STOP',
              'name': 'Stop',
            },
            {
              'key': 'PAUSE',
              'name': 'Pause',
            },
            {
              'key': 'GAME_OVER',
              'name': 'Game Over',
            },
            {
              'key': 'RESUME',
              'name': 'Resume',
            },
            {
              'key': 'CLOSE',
              'name': 'Close',
            },
            {
              'key': 'RESTART',
              'name': 'Restart',
            },
            {
              'key': 'PlatLevelLoaded',
              'name': 'PlatLevel loaded',
              'payloadSchema': [
                {
                  'name': 'data',
                  'type': '[PlatLevel]',
                },
              ],
            },
            {
              'key': 'PlatLevelLoadFailed',
              'name': 'PlatLevel load failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CollectibleSaved',
              'name': 'Collectible saved',
              'payloadSchema': [
                {
                  'name': 'id',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CollectibleSaveFailed',
              'name': 'Collectible save failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CollectibleUpdated',
              'name': 'Collectible updated',
              'payloadSchema': [
                {
                  'name': 'id',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CollectibleUpdateFailed',
              'name': 'Collectible update failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CollectibleDeleted',
              'name': 'Collectible deleted',
              'payloadSchema': [
                {
                  'name': 'id',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CollectibleDeleteFailed',
              'name': 'Collectible delete failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
            },
          ],
          'transitions': [
            {
              'from': 'menu',
              'to': 'menu',
              'event': 'INIT',
              'effects': [
                [
                  'set',
                  '@entity.lives',
                  3,
                ],
                [
                  'set',
                  '@entity.score',
                  0,
                ],
                [
                  'fetch',
                  'PlatLevel',
                  {
                    'emit': {
                      'success': 'PlatLevelLoaded',
                      'failure': 'PlatLevelLoadFailed',
                    },
                  },
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'type': 'game-shell',
                    'appName': 'Platformer App',
                    'children': [
                      {
                        'type': 'game-menu',
                        'title': 'Platformer',
                        'menuItems': [
                          {
                            'variant': 'primary',
                            'label': 'Start Game',
                            'event': 'START',
                          },
                        ],
                        'subtitle': 'Side-Scrolling Adventure',
                      },
                    ],
                    'showTopBar': true,
                  },
                ],
              ],
            },
            {
              'from': 'menu',
              'to': 'playing',
              'event': 'START',
              'effects': [
                [
                  'render-ui',
                  'main',
                  {
                    'type': 'game-shell',
                    'appName': 'Platformer App',
                    'showTopBar': true,
                    'children': [
                      {
                        'bgColor': '#1a1a2e',
                        'worldWidth': 2400,
                        'worldHeight': 400,
                        'canvasWidth': 800,
                        'leftEvent': 'LEFT',
                        'rightEvent': 'RIGHT',
                        'jumpEvent': 'JUMP',
                        'followCamera': true,
                        'type': 'platformer-canvas',
                        'canvasHeight': 400,
                        'stopEvent': 'STOP',
                      },
                    ],
                  },
                ],
              ],
            },
            {
              'from': 'menu',
              'to': 'menu',
              'event': 'NAVIGATE',
            },
            {
              'from': 'playing',
              'to': 'playing',
              'event': 'LEFT',
            },
            {
              'from': 'playing',
              'to': 'playing',
              'event': 'RIGHT',
            },
            {
              'from': 'playing',
              'to': 'playing',
              'event': 'JUMP',
            },
            {
              'from': 'playing',
              'to': 'playing',
              'event': 'STOP',
            },
            {
              'from': 'playing',
              'to': 'paused',
              'event': 'PAUSE',
              'effects': [
                [
                  'render-ui',
                  'modal',
                  {
                    'type': 'game-menu',
                    'title': 'Paused',
                    'menuItems': [
                      {
                        'variant': 'primary',
                        'event': 'RESUME',
                        'label': 'Resume',
                      },
                      {
                        'label': 'Quit',
                        'event': 'RESTART',
                        'variant': 'ghost',
                      },
                    ],
                  },
                ],
              ],
            },
            {
              'from': 'playing',
              'to': 'gameover',
              'event': 'GAME_OVER',
              'effects': [
                [
                  'render-ui',
                  'main',
                  {
                    'showTopBar': true,
                    'children': [
                      {
                        'menuItems': [
                          {
                            'label': 'Play Again',
                            'variant': 'primary',
                            'event': 'RESTART',
                          },
                          {
                            'label': 'Main Menu',
                            'event': 'RESTART',
                            'variant': 'secondary',
                          },
                        ],
                        'title': 'Game Over',
                        'type': 'game-over-screen',
                        'stats': [
                          {
                            'label': 'Score',
                            'value': '@entity.score',
                          },
                          {
                            'value': '@entity.lives',
                            'label': 'Lives',
                          },
                        ],
                      },
                    ],
                    'type': 'game-shell',
                    'appName': 'Platformer App',
                  },
                ],
              ],
            },
            {
              'from': 'paused',
              'to': 'paused',
              'event': 'NAVIGATE',
            },
            {
              'from': 'paused',
              'to': 'playing',
              'event': 'RESUME',
              'effects': [
                [
                  'render-ui',
                  'modal',
                  null,
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'type': 'game-shell',
                    'appName': 'Platformer App',
                    'showTopBar': true,
                    'children': [
                      {
                        'worldWidth': 2400,
                        'jumpEvent': 'JUMP',
                        'rightEvent': 'RIGHT',
                        'worldHeight': 400,
                        'canvasHeight': 400,
                        'bgColor': '#1a1a2e',
                        'followCamera': true,
                        'leftEvent': 'LEFT',
                        'stopEvent': 'STOP',
                        'type': 'platformer-canvas',
                        'canvasWidth': 800,
                      },
                    ],
                  },
                ],
              ],
            },
            {
              'from': 'paused',
              'to': 'playing',
              'event': 'CLOSE',
              'effects': [
                [
                  'render-ui',
                  'modal',
                  null,
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'appName': 'Platformer App',
                    'showTopBar': true,
                    'children': [
                      {
                        'bgColor': '#1a1a2e',
                        'jumpEvent': 'JUMP',
                        'stopEvent': 'STOP',
                        'canvasHeight': 400,
                        'type': 'platformer-canvas',
                        'rightEvent': 'RIGHT',
                        'followCamera': true,
                        'leftEvent': 'LEFT',
                        'canvasWidth': 800,
                        'worldHeight': 400,
                        'worldWidth': 2400,
                      },
                    ],
                    'type': 'game-shell',
                  },
                ],
              ],
            },
            {
              'from': 'paused',
              'to': 'menu',
              'event': 'RESTART',
              'effects': [
                [
                  'render-ui',
                  'modal',
                  null,
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'appName': 'Platformer App',
                    'type': 'game-shell',
                    'showTopBar': true,
                    'children': [
                      {
                        'title': 'Platformer',
                        'subtitle': 'Side-Scrolling Adventure',
                        'menuItems': [
                          {
                            'variant': 'primary',
                            'label': 'Start Game',
                            'event': 'START',
                          },
                        ],
                        'type': 'game-menu',
                      },
                    ],
                  },
                ],
              ],
            },
            {
              'from': 'gameover',
              'to': 'menu',
              'event': 'RESTART',
              'effects': [
                [
                  'render-ui',
                  'main',
                  {
                    'appName': 'Platformer App',
                    'children': [
                      {
                        'type': 'game-menu',
                        'title': 'Platformer',
                        'subtitle': 'Side-Scrolling Adventure',
                        'menuItems': [
                          {
                            'variant': 'primary',
                            'event': 'START',
                            'label': 'Start Game',
                          },
                        ],
                      },
                    ],
                    'type': 'game-shell',
                    'showTopBar': true,
                  },
                ],
              ],
            },
          ],
        },
        'scope': 'collection',
      } as never, 'PlatLevel', canonicalName) as never,
      rebindInlineTraitEntity({
        'name': 'PlatLevelPlatformerCanvas',
        'category': 'interaction',
        'linkedEntity': 'PlatLevel',
        'emits': [
          {
            'event': 'PlatLevelLoaded',
            'description': 'Fired when PlatLevel finishes loading',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'data',
                'type': '[PlatLevel]',
              },
            ],
          },
          {
            'event': 'PlatLevelLoadFailed',
            'description': 'Fired when PlatLevel fails to load',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
          },
        ],
        'stateMachine': {
          'states': [
            {
              'name': 'idle',
              'isInitial': true,
            },
            {
              'name': 'running',
            },
          ],
          'events': [
            {
              'key': 'INIT',
              'name': 'Initialize',
            },
            {
              'key': 'START',
              'name': 'Start',
            },
            {
              'key': 'LEFT',
              'name': 'Left',
            },
            {
              'key': 'RIGHT',
              'name': 'Right',
            },
            {
              'key': 'JUMP',
              'name': 'Jump',
            },
            {
              'key': 'STOP',
              'name': 'Stop',
            },
            {
              'key': 'PlatLevelLoaded',
              'name': 'PlatLevel loaded',
              'payloadSchema': [
                {
                  'name': 'data',
                  'type': '[PlatLevel]',
                },
              ],
            },
            {
              'key': 'PlatLevelLoadFailed',
              'name': 'PlatLevel load failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
            },
          ],
          'transitions': [
            {
              'from': 'idle',
              'to': 'idle',
              'event': 'INIT',
              'effects': [
                [
                  'set',
                  '@entity.platforms',
                  [],
                ],
                [
                  'set',
                  '@entity.player',
                  {
                    'y': 0,
                    'vx': 0,
                    'width': 32,
                    'grounded': true,
                    'height': 32,
                    'x': 0,
                    'vy': 0,
                    'facingRight': true,
                  },
                ],
                [
                  'fetch',
                  'PlatLevel',
                  {
                    'emit': {
                      'failure': 'PlatLevelLoadFailed',
                      'success': 'PlatLevelLoaded',
                    },
                  },
                ],
              ],
            },
            {
              'from': 'idle',
              'to': 'running',
              'event': 'START',
              'effects': [
                [
                  'render-ui',
                  'main',
                  {
                    'children': [
                      {
                        'canvasWidth': 800,
                        'followCamera': true,
                        'bgColor': '#1a1a2e',
                        'jumpEvent': 'JUMP',
                        'worldHeight': 400,
                        'type': 'platformer-canvas',
                        'rightEvent': 'RIGHT',
                        'platforms': '@entity.platforms',
                        'stopEvent': 'STOP',
                        'player': '@entity.player',
                        'canvasHeight': 400,
                        'leftEvent': 'LEFT',
                        'worldWidth': 2400,
                      },
                    ],
                    'showTopBar': true,
                    'appName': 'Platformer App',
                    'type': 'game-shell',
                  },
                ],
              ],
            },
            {
              'from': 'running',
              'to': 'running',
              'event': 'LEFT',
            },
            {
              'from': 'running',
              'to': 'running',
              'event': 'RIGHT',
            },
            {
              'from': 'running',
              'to': 'running',
              'event': 'JUMP',
            },
            {
              'from': 'running',
              'to': 'idle',
              'event': 'STOP',
              'effects': [
                [
                  'render-ui',
                  'main',
                  {
                    'appName': 'Platformer App',
                    'type': 'game-shell',
                    'showTopBar': true,
                    'children': [
                      {
                        'worldWidth': 2400,
                        'type': 'platformer-canvas',
                        'followCamera': true,
                        'rightEvent': 'RIGHT',
                        'worldHeight': 400,
                        'canvasWidth': 800,
                        'player': '@entity.player',
                        'canvasHeight': 400,
                        'leftEvent': 'LEFT',
                        'jumpEvent': 'JUMP',
                        'stopEvent': 'STOP',
                        'bgColor': '#1a1a2e',
                        'platforms': '@entity.platforms',
                      },
                    ],
                  },
                ],
              ],
            },
          ],
        },
        'scope': 'collection',
      } as never, 'PlatLevel', canonicalName) as never,
    ],
    pages: [
      {
        'name': 'GamePage',
        'path': '/game',
        'traits': [
          {
            'ref': 'PlatLevelPlatformerFlow',
          },
          {
            'ref': 'PlatLevelPlatformerCanvas',
          },
        ],
      } as never,
    ],
  });
  type _OrbTrait = OrbitalDefinition["traits"][number];
  type _OrbPage = NonNullable<OrbitalDefinition["pages"]>[number];
  type _RefOverride = Pick<MakeTraitRefOpts, "config" | "linkedEntity" | "events" | "name" | "emitsScope" | "listens">;
  if (built.traits && params.traitOverrides !== undefined) {
    built.traits = (built.traits as _OrbTrait[]).map((t): _OrbTrait => {
      if (!t || typeof t !== "object") return t;
      const tr = t as TraitReference & { name?: string };
      // Match by name so inline traits (no `ref`) and
      // reference traits (with `ref`) both pick up the
      // override surface keyed on the trait's `name`.
      if (typeof tr.name !== "string") return t;
      const overrides = params.traitOverrides as Record<string, _RefOverride | undefined> | undefined;
      const override = overrides?.[tr.name];
      if (!override) return t;
      const merged: TraitReference = { ...tr };
      if (override.config !== undefined) merged.config = { ...(tr.config ?? {}), ...override.config };
      if (override.linkedEntity !== undefined) merged.linkedEntity = override.linkedEntity;
      if (override.events !== undefined) merged.events = { ...(tr.events ?? {}), ...override.events };
      if (override.name !== undefined) merged.name = override.name;
      if (override.emitsScope !== undefined) merged.emitsScope = override.emitsScope;
      if (override.listens !== undefined) merged.listens = override.listens;
      return merged;
    });
  }
  if (built.pages && params.pagePath !== undefined) {
    built.pages = (built.pages as _OrbPage[]).map((p, idx) => {
      if (!p || typeof p !== "object") return p;
      if (idx !== 0) return p;
      const out = { ...p } as _OrbPage & { path?: string };
      out.path = params.pagePath;
      return out;
    });
  }
  return built;
}

/** Manifest — describes the params surface of stdPlatformerAppPlatLevelOrbital. */
export const StdPlatformerAppPlatLevelOrbitalManifest = {
  organism: 'std-platformer-app',
  orbitalName: 'PlatLevelOrbital',
  paramFields: [
    { name: 'fields', type: 'EntityField[]', description: 'Extra fields appended to the canonical entity.' },
    { name: 'pagePath', type: 'string', description: 'URL override for the orbital first page.' },
    { name: 'persistence', type: "'persistent' | 'runtime' | 'singleton' | 'instance' | 'local'", description: 'Override the canonical entity persistence mode.' },
    { name: 'entityName', type: 'string', description: 'Rename the canonical entity. PascalCase singular, ≤32 chars. Threads through every trait\'s linkedEntity binding; compiler rewrites @Entity.x refs.' },
    { name: 'collection', type: 'string', description: 'Override derived collection key. Defaults to plural(entityName).toLowerCase().' },
    { name: 'traitOverrides', type: "Partial<Record<TraitName, { config?, linkedEntity?, events?, name?, emitsScope?, listens? }>>", description: 'Per-imported-trait overrides — mirrors .lolo\'s native trait-composition surface 1:1. effects is excluded (atom-owned; use listens via a sibling trait).' },
  ] as const,
  traitNames: [
  ] as const,
  inlineTraitNames: [
    'PlatLevelPlatformerFlow',
    'PlatLevelPlatformerCanvas',
  ] as const,
};

/** Typed guard — runtime validates StdPlatformerAppPlatLevelOrbitalParams keys. */
export function isStdPlatformerAppPlatLevelOrbitalParams(p: object): p is StdPlatformerAppPlatLevelOrbitalParams {
  type _OverrideRecord = NonNullable<StdPlatformerAppPlatLevelOrbitalParams['traitOverrides']>;
  const obj = p as { traitOverrides?: _OverrideRecord };
  if (obj.traitOverrides !== undefined) {
    if (typeof obj.traitOverrides !== "object" || obj.traitOverrides === null) return false;
    const allowed: readonly string[] = [
      ...StdPlatformerAppPlatLevelOrbitalManifest.traitNames,
      ...StdPlatformerAppPlatLevelOrbitalManifest.inlineTraitNames,
    ];
    for (const k of Object.keys(obj.traitOverrides)) {
      if (!allowed.includes(k)) return false;
    }
  }
  return true;
}

/**
 * Tunable params for the PlatScoreOrbital orbital.
 *
 * Canonical entity: PlatScore — overridable via
 * `entityName`. The factory threads the effective name through every
 * trait's `linkedEntity` binding; the `.orb` compiler's inline phase
 * auto-rewrites every `@Entity.x`, `["ref",X]`, `["fetch",X,…]`,
 * `["persist",…,X,…]` and payload type string accordingly.
 *
 * Override surface (mirrors `.lolo`'s native overrides 1:1):
 *   fields         — extra entity fields (appended)
 *   pagePath       — first-page URL override
 *   persistence    — entity persistence mode
 *   entityName     — rename the canonical entity
 *   collection     — override the derived collection key
 *   traitOverrides — per-imported-trait `config`, `linkedEntity`,
 *                    `events`, `name`, `emitsScope`, `listens`.
 *                    `effects` is NOT exposed — `.lolo` removed it
 *                    in Phase 9.5.H. Use `listens` via a sibling
 *                    trait to react to atom events.
 */
export interface StdPlatformerAppPlatScoreOrbitalParams {
  /** Extra fields appended to the canonical entity. */
  fields?: EntityField[];
  /** URL path override for the orbital's first page. */
  pagePath?: string;
  /** Override the canonical entity persistence mode. */
  persistence?: EntityPersistence;
  /** Rename the canonical entity (PascalCase singular, ≤32 chars). */
  entityName?: string;
  /** Override derived collection key (defaults to plural(entityName).toLowerCase()). */
  collection?: string;
  /**
   * Per-imported-trait override surface keyed on each imported
   * trait's canonical `name`. Accepts every override `.lolo`
   * natively supports: `config`, `linkedEntity`, `events`,
   * `name`, `emitsScope`, `listens`. `effects` is excluded —
   * atom-owned (use `listens` via a sibling trait instead).
   */
  traitOverrides?: Partial<Record<
    'PlatScoreScoreBoard',
    Pick<MakeTraitRefOpts, 'config' | 'linkedEntity' | 'events' | 'name' | 'emitsScope' | 'listens'>
  >>;
}

/** Per-orbital factory: builds the PlatScoreOrbital orbital with consumer params. */
export function stdPlatformerAppPlatScoreOrbital(params: StdPlatformerAppPlatScoreOrbitalParams = {}): OrbitalDefinition {
  const canonicalName = params.entityName ?? 'PlatScore';
  const built = makeOrbitalWithUses({
    name: 'PlatScoreOrbital',
    uses: [],
    entity: {
      name: canonicalName,
      persistence: params.persistence ?? 'runtime',
      fields: ((): EntityField[] => {
        const canonical: EntityField[] = [
          {
            'name': 'id',
            'type': 'string',
            'required': true,
          },
          {
            'name': 'playerName',
            'type': 'string',
            'required': true,
          },
          {
            'name': 'score',
            'type': 'number',
            'required': true,
            'default': 0,
          },
          {
            'name': 'level',
            'type': 'number',
            'default': 1,
          },
          {
            'name': 'completedAt',
            'type': 'string',
          },
          {
            'name': 'highScore',
            'type': 'number',
          },
          {
            'name': 'combo',
            'type': 'number',
          },
          {
            'name': 'multiplier',
            'type': 'number',
          },
        ];
        const extras = params.fields ?? [];
        if (extras.length === 0) return canonical;
        const extraNames = new Set(extras.map((f) => f.name));
        return [...canonical.filter((f) => !extraNames.has(f.name)), ...extras];
      })(),
    } as Entity,
    traits: [
      rebindInlineTraitEntity({
        'name': 'PlatScoreScoreBoard',
        'category': 'interaction',
        'linkedEntity': 'PlatScore',
        'emits': [
          {
            'event': 'PlatScoreLoaded',
            'description': 'Fired when PlatScore finishes loading',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'data',
                'type': '[PlatScore]',
              },
            ],
          },
          {
            'event': 'PlatScoreLoadFailed',
            'description': 'Fired when PlatScore fails to load',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
          },
        ],
        'stateMachine': {
          'states': [
            {
              'name': 'idle',
              'isInitial': true,
            },
          ],
          'events': [
            {
              'key': 'INIT',
              'name': 'Initialize',
            },
            {
              'key': 'ADD_SCORE',
              'name': 'Add Score',
              'payloadSchema': [
                {
                  'name': 'points',
                  'type': 'number',
                },
              ],
            },
            {
              'key': 'COMBO',
              'name': 'Combo',
              'payloadSchema': [
                {
                  'name': 'multiplier',
                  'type': 'number',
                },
              ],
            },
            {
              'key': 'RESET',
              'name': 'Reset',
            },
            {
              'key': 'PlatScoreLoaded',
              'name': 'PlatScore loaded',
              'payloadSchema': [
                {
                  'name': 'data',
                  'type': '[PlatScore]',
                },
              ],
            },
            {
              'key': 'PlatScoreLoadFailed',
              'name': 'PlatScore load failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
            },
          ],
          'transitions': [
            {
              'from': 'idle',
              'to': 'idle',
              'event': 'INIT',
              'effects': [
                [
                  'set',
                  '@entity.highScore',
                  0,
                ],
                [
                  'set',
                  '@entity.level',
                  1,
                ],
                [
                  'fetch',
                  'PlatScore',
                  {
                    'emit': {
                      'success': 'PlatScoreLoaded',
                      'failure': 'PlatScoreLoadFailed',
                    },
                  },
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'type': 'game-shell',
                    'appName': 'Platformer App',
                    'children': [
                      {
                        'score': '@entity.score',
                        'type': 'score-board',
                        'combo': '@entity.combo',
                        'highScore': '@entity.highScore',
                        'multiplier': '@entity.multiplier',
                        'level': '@entity.level',
                      },
                    ],
                    'showTopBar': true,
                  },
                ],
              ],
            },
            {
              'from': 'idle',
              'to': 'idle',
              'event': 'ADD_SCORE',
              'effects': [
                [
                  'set',
                  '@entity.score',
                  [
                    '+',
                    '@entity.score',
                    '@payload.points',
                  ],
                ],
                [
                  'set',
                  '@entity.combo',
                  [
                    '+',
                    '@entity.combo',
                    1,
                  ],
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'children': [
                      {
                        'combo': '@entity.combo',
                        'highScore': '@entity.highScore',
                        'level': '@entity.level',
                        'score': '@entity.score',
                        'multiplier': '@entity.multiplier',
                        'type': 'score-board',
                      },
                    ],
                    'showTopBar': true,
                    'type': 'game-shell',
                    'appName': 'Platformer App',
                  },
                ],
              ],
            },
            {
              'from': 'idle',
              'to': 'idle',
              'event': 'COMBO',
              'effects': [
                [
                  'set',
                  '@entity.multiplier',
                  '@payload.multiplier',
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'showTopBar': true,
                    'appName': 'Platformer App',
                    'type': 'game-shell',
                    'children': [
                      {
                        'type': 'score-board',
                        'score': '@entity.score',
                        'highScore': '@entity.highScore',
                        'multiplier': '@entity.multiplier',
                        'level': '@entity.level',
                        'combo': '@entity.combo',
                      },
                    ],
                  },
                ],
              ],
            },
            {
              'from': 'idle',
              'to': 'idle',
              'event': 'RESET',
              'effects': [
                [
                  'set',
                  '@entity.score',
                  0,
                ],
                [
                  'set',
                  '@entity.combo',
                  0,
                ],
                [
                  'set',
                  '@entity.multiplier',
                  1,
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'appName': 'Platformer App',
                    'showTopBar': true,
                    'type': 'game-shell',
                    'children': [
                      {
                        'type': 'score-board',
                        'score': '@entity.score',
                        'level': '@entity.level',
                        'multiplier': '@entity.multiplier',
                        'combo': '@entity.combo',
                        'highScore': '@entity.highScore',
                      },
                    ],
                  },
                ],
              ],
            },
          ],
        },
        'scope': 'collection',
      } as never, 'PlatScore', canonicalName) as never,
    ],
    pages: [
      {
        'name': 'Scores',
        'path': '/scores',
        'traits': [
          {
            'ref': 'PlatScoreScoreBoard',
          },
        ],
      } as never,
    ],
  });
  type _OrbTrait = OrbitalDefinition["traits"][number];
  type _OrbPage = NonNullable<OrbitalDefinition["pages"]>[number];
  type _RefOverride = Pick<MakeTraitRefOpts, "config" | "linkedEntity" | "events" | "name" | "emitsScope" | "listens">;
  if (built.traits && params.traitOverrides !== undefined) {
    built.traits = (built.traits as _OrbTrait[]).map((t): _OrbTrait => {
      if (!t || typeof t !== "object") return t;
      const tr = t as TraitReference & { name?: string };
      // Match by name so inline traits (no `ref`) and
      // reference traits (with `ref`) both pick up the
      // override surface keyed on the trait's `name`.
      if (typeof tr.name !== "string") return t;
      const overrides = params.traitOverrides as Record<string, _RefOverride | undefined> | undefined;
      const override = overrides?.[tr.name];
      if (!override) return t;
      const merged: TraitReference = { ...tr };
      if (override.config !== undefined) merged.config = { ...(tr.config ?? {}), ...override.config };
      if (override.linkedEntity !== undefined) merged.linkedEntity = override.linkedEntity;
      if (override.events !== undefined) merged.events = { ...(tr.events ?? {}), ...override.events };
      if (override.name !== undefined) merged.name = override.name;
      if (override.emitsScope !== undefined) merged.emitsScope = override.emitsScope;
      if (override.listens !== undefined) merged.listens = override.listens;
      return merged;
    });
  }
  if (built.pages && params.pagePath !== undefined) {
    built.pages = (built.pages as _OrbPage[]).map((p, idx) => {
      if (!p || typeof p !== "object") return p;
      if (idx !== 0) return p;
      const out = { ...p } as _OrbPage & { path?: string };
      out.path = params.pagePath;
      return out;
    });
  }
  return built;
}

/** Manifest — describes the params surface of stdPlatformerAppPlatScoreOrbital. */
export const StdPlatformerAppPlatScoreOrbitalManifest = {
  organism: 'std-platformer-app',
  orbitalName: 'PlatScoreOrbital',
  paramFields: [
    { name: 'fields', type: 'EntityField[]', description: 'Extra fields appended to the canonical entity.' },
    { name: 'pagePath', type: 'string', description: 'URL override for the orbital first page.' },
    { name: 'persistence', type: "'persistent' | 'runtime' | 'singleton' | 'instance' | 'local'", description: 'Override the canonical entity persistence mode.' },
    { name: 'entityName', type: 'string', description: 'Rename the canonical entity. PascalCase singular, ≤32 chars. Threads through every trait\'s linkedEntity binding; compiler rewrites @Entity.x refs.' },
    { name: 'collection', type: 'string', description: 'Override derived collection key. Defaults to plural(entityName).toLowerCase().' },
    { name: 'traitOverrides', type: "Partial<Record<TraitName, { config?, linkedEntity?, events?, name?, emitsScope?, listens? }>>", description: 'Per-imported-trait overrides — mirrors .lolo\'s native trait-composition surface 1:1. effects is excluded (atom-owned; use listens via a sibling trait).' },
  ] as const,
  traitNames: [
  ] as const,
  inlineTraitNames: [
    'PlatScoreScoreBoard',
  ] as const,
};

/** Typed guard — runtime validates StdPlatformerAppPlatScoreOrbitalParams keys. */
export function isStdPlatformerAppPlatScoreOrbitalParams(p: object): p is StdPlatformerAppPlatScoreOrbitalParams {
  type _OverrideRecord = NonNullable<StdPlatformerAppPlatScoreOrbitalParams['traitOverrides']>;
  const obj = p as { traitOverrides?: _OverrideRecord };
  if (obj.traitOverrides !== undefined) {
    if (typeof obj.traitOverrides !== "object" || obj.traitOverrides === null) return false;
    const allowed: readonly string[] = [
      ...StdPlatformerAppPlatScoreOrbitalManifest.traitNames,
      ...StdPlatformerAppPlatScoreOrbitalManifest.inlineTraitNames,
    ];
    for (const k of Object.keys(obj.traitOverrides)) {
      if (!allowed.includes(k)) return false;
    }
  }
  return true;
}

/**
 * Tunable params for the CollectibleOrbital orbital.
 *
 * Canonical entity: Collectible — overridable via
 * `entityName`. The factory threads the effective name through every
 * trait's `linkedEntity` binding; the `.orb` compiler's inline phase
 * auto-rewrites every `@Entity.x`, `["ref",X]`, `["fetch",X,…]`,
 * `["persist",…,X,…]` and payload type string accordingly.
 *
 * Override surface (mirrors `.lolo`'s native overrides 1:1):
 *   fields         — extra entity fields (appended)
 *   pagePath       — first-page URL override
 *   persistence    — entity persistence mode
 *   entityName     — rename the canonical entity
 *   collection     — override the derived collection key
 *   traitOverrides — per-imported-trait `config`, `linkedEntity`,
 *                    `events`, `name`, `emitsScope`, `listens`.
 *                    `effects` is NOT exposed — `.lolo` removed it
 *                    in Phase 9.5.H. Use `listens` via a sibling
 *                    trait to react to atom events.
 */
export interface StdPlatformerAppCollectibleOrbitalParams {
  /** Extra fields appended to the canonical entity. */
  fields?: EntityField[];
  /** URL path override for the orbital's first page. */
  pagePath?: string;
  /** Override the canonical entity persistence mode. */
  persistence?: EntityPersistence;
  /** Rename the canonical entity (PascalCase singular, ≤32 chars). */
  entityName?: string;
  /** Override derived collection key (defaults to plural(entityName).toLowerCase()). */
  collection?: string;
  /**
   * Per-imported-trait override surface keyed on each imported
   * trait's canonical `name`. Accepts every override `.lolo`
   * natively supports: `config`, `linkedEntity`, `events`,
   * `name`, `emitsScope`, `listens`. `effects` is excluded —
   * atom-owned (use `listens` via a sibling trait instead).
   */
  traitOverrides?: Partial<Record<
    'CollectibleBrowse' | 'CollectibleAdd' | 'CollectibleUse' | 'CollectibleDrop',
    Pick<MakeTraitRefOpts, 'config' | 'linkedEntity' | 'events' | 'name' | 'emitsScope' | 'listens'>
  >>;
}

/** Per-orbital factory: builds the CollectibleOrbital orbital with consumer params. */
export function stdPlatformerAppCollectibleOrbital(params: StdPlatformerAppCollectibleOrbitalParams = {}): OrbitalDefinition {
  const canonicalName = params.entityName ?? 'Collectible';
  const collectionName = params.collection
    ?? (params.entityName ? `${params.entityName.toLowerCase()}s` : 'collectibles');
  const built = makeOrbitalWithUses({
    name: 'CollectibleOrbital',
    uses: [],
    entity: {
      name: canonicalName,
      collection: collectionName,
      persistence: params.persistence ?? 'persistent',
      fields: ((): EntityField[] => {
        const canonical: EntityField[] = [
          {
            'name': 'id',
            'type': 'string',
            'required': true,
          },
          {
            'name': 'name',
            'type': 'string',
            'required': true,
          },
          {
            'name': 'type',
            'type': 'string',
            'required': true,
          },
          {
            'name': 'quantity',
            'type': 'number',
          },
          {
            'name': 'rarity',
            'type': 'string',
          },
          {
            'name': 'pendingId',
            'type': 'string',
          },
        ];
        const extras = params.fields ?? [];
        if (extras.length === 0) return canonical;
        const extraNames = new Set(extras.map((f) => f.name));
        return [...canonical.filter((f) => !extraNames.has(f.name)), ...extras];
      })(),
    } as Entity,
    traits: [
      rebindInlineTraitEntity({
        'name': 'CollectibleBrowse',
        'category': 'interaction',
        'linkedEntity': 'Collectible',
        'emits': [
          {
            'event': 'ADD_ITEM',
          },
          {
            'event': 'USE_ITEM',
            'payloadSchema': [
              {
                'name': 'id',
                'type': 'string',
                'required': true,
              },
              {
                'name': 'row.id',
                'type': 'string',
                'required': true,
              },
              {
                'name': 'row.name',
                'type': 'string',
                'required': true,
              },
              {
                'name': 'row.type',
                'type': 'string',
                'required': true,
              },
              {
                'name': 'row.quantity',
                'type': 'number',
              },
              {
                'name': 'row.rarity',
                'type': 'string',
              },
              {
                'name': 'row.pendingId',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'DROP',
            'payloadSchema': [
              {
                'name': 'id',
                'type': 'string',
                'required': true,
              },
              {
                'name': 'row.id',
                'type': 'string',
                'required': true,
              },
              {
                'name': 'row.name',
                'type': 'string',
                'required': true,
              },
              {
                'name': 'row.type',
                'type': 'string',
                'required': true,
              },
              {
                'name': 'row.quantity',
                'type': 'number',
              },
              {
                'name': 'row.rarity',
                'type': 'string',
              },
              {
                'name': 'row.pendingId',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'CollectibleLoaded',
            'description': 'Fired when Collectible finishes loading',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'data',
                'type': '[Collectible]',
              },
            ],
          },
          {
            'event': 'CollectibleLoadFailed',
            'description': 'Fired when Collectible fails to load',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
          },
        ],
        'listens': [
          {
            'event': 'ITEM_ADDED',
            'triggers': 'INIT',
            'source': {
              'kind': 'trait',
              'trait': 'CollectibleAdd',
            },
          },
          {
            'event': 'ITEM_USED',
            'triggers': 'INIT',
            'source': {
              'kind': 'trait',
              'trait': 'CollectibleUse',
            },
          },
          {
            'event': 'CONFIRM_DROP',
            'triggers': 'INIT',
            'source': {
              'kind': 'trait',
              'trait': 'CollectibleDrop',
            },
          },
        ],
        'stateMachine': {
          'states': [
            {
              'name': 'browsing',
              'isInitial': true,
            },
          ],
          'events': [
            {
              'key': 'INIT',
              'name': 'Initialize',
            },
            {
              'key': 'CollectibleLoaded',
              'name': 'Collectible loaded',
              'payloadSchema': [
                {
                  'name': 'data',
                  'type': '[Collectible]',
                },
              ],
            },
            {
              'key': 'CollectibleLoadFailed',
              'name': 'Collectible load failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'ADD_ITEM',
              'name': 'Add Item',
            },
            {
              'key': 'USE_ITEM',
              'name': 'Use Item',
            },
            {
              'key': 'DROP',
              'name': 'Drop',
            },
          ],
          'transitions': [
            {
              'from': 'browsing',
              'to': 'browsing',
              'event': 'INIT',
              'effects': [
                [
                  'fetch',
                  'Collectible',
                  {
                    'emit': {
                      'success': 'CollectibleLoaded',
                      'failure': 'CollectibleLoadFailed',
                    },
                  },
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'direction': 'vertical',
                    'align': 'center',
                    'className': 'py-12',
                    'type': 'stack',
                    'gap': 'md',
                    'children': [
                      {
                        'type': 'spinner',
                      },
                      {
                        'variant': 'caption',
                        'type': 'typography',
                        'color': 'muted',
                        'content': 'Loading…',
                      },
                    ],
                  },
                ],
              ],
            },
            {
              'from': 'browsing',
              'to': 'browsing',
              'event': 'CollectibleLoaded',
              'effects': [
                [
                  'render-ui',
                  'main',
                  {
                    'type': 'game-shell',
                    'appName': 'Platformer App',
                    'showTopBar': true,
                    'children': [
                      {
                        'type': 'stack',
                        'className': 'max-w-5xl mx-auto w-full',
                        'gap': 'lg',
                        'children': [
                          {
                            'direction': 'horizontal',
                            'align': 'center',
                            'children': [
                              {
                                'type': 'stack',
                                'direction': 'horizontal',
                                'children': [
                                  {
                                    'type': 'icon',
                                    'name': 'package',
                                  },
                                  {
                                    'content': 'Collectibles',
                                    'variant': 'h2',
                                    'type': 'typography',
                                  },
                                ],
                                'gap': 'sm',
                                'align': 'center',
                              },
                              {
                                'gap': 'sm',
                                'type': 'stack',
                                'children': [
                                  {
                                    'action': 'ADD_ITEM',
                                    'variant': 'primary',
                                    'type': 'button',
                                    'icon': 'plus',
                                    'label': 'Add Collectible',
                                  },
                                ],
                                'direction': 'horizontal',
                              },
                            ],
                            'gap': 'md',
                            'type': 'stack',
                            'justify': 'between',
                          },
                          {
                            'type': 'divider',
                          },
                          {
                            'type': 'data-grid',
                            'itemActions': [
                              {
                                'label': 'Use',
                                'event': 'USE_ITEM',
                                'variant': 'ghost',
                              },
                              {
                                'label': 'Drop',
                                'variant': 'danger',
                                'event': 'DROP',
                              },
                            ],
                            'entity': '@payload.data',
                            'fields': [
                              {
                                'name': 'name',
                                'variant': 'h4',
                                'icon': 'package',
                                'label': 'Name',
                              },
                              {
                                'name': 'type',
                                'colorMap': {
                                  'completed': 'success',
                                  'disabled': 'neutral',
                                  'failed': 'destructive',
                                  'pending': 'warning',
                                  'scheduled': 'warning',
                                  'inactive': 'neutral',
                                  'draft': 'warning',
                                  'archived': 'neutral',
                                  'error': 'destructive',
                                  'cancelled': 'destructive',
                                  'active': 'success',
                                  'done': 'success',
                                },
                                'variant': 'badge',
                                'label': 'Type',
                              },
                              {
                                'name': 'quantity',
                                'label': 'Quantity',
                                'variant': 'caption',
                              },
                            ],
                          },
                        ],
                        'direction': 'vertical',
                      },
                    ],
                  },
                ],
              ],
            },
            {
              'from': 'browsing',
              'to': 'browsing',
              'event': 'CollectibleLoadFailed',
              'effects': [
                [
                  'render-ui',
                  'main',
                  {
                    'gap': 'md',
                    'className': 'py-12',
                    'direction': 'vertical',
                    'type': 'stack',
                    'children': [
                      {
                        'type': 'icon',
                        'name': 'alert-triangle',
                        'color': 'destructive',
                      },
                      {
                        'variant': 'h3',
                        'content': 'Failed to load collectible',
                        'type': 'typography',
                      },
                      {
                        'type': 'typography',
                        'content': '@payload.error',
                        'color': 'muted',
                        'variant': 'body',
                      },
                      {
                        'action': 'INIT',
                        'type': 'button',
                        'variant': 'primary',
                        'icon': 'rotate-ccw',
                        'label': 'Retry',
                      },
                    ],
                    'align': 'center',
                  },
                ],
              ],
            },
          ],
        },
        'scope': 'collection',
      } as never, 'Collectible', canonicalName) as never,
      rebindInlineTraitEntity({
        'name': 'CollectibleAdd',
        'category': 'interaction',
        'linkedEntity': 'Collectible',
        'emits': [
          {
            'event': 'ITEM_ADDED',
          },
          {
            'event': 'CollectibleLoadFailed',
            'description': 'Fired when Collectible fails to load',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'CollectibleLoaded',
            'description': 'Fired when Collectible finishes loading',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'data',
                'type': '[Collectible]',
              },
            ],
          },
          {
            'event': 'CollectibleSaveFailed',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'CollectibleSaved',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'id',
                'type': 'string',
              },
            ],
          },
        ],
        'listens': [
          {
            'event': 'ADD_ITEM',
            'triggers': 'ADD_ITEM',
            'source': {
              'kind': 'trait',
              'trait': 'CollectibleBrowse',
            },
          },
        ],
        'stateMachine': {
          'states': [
            {
              'name': 'closed',
              'isInitial': true,
            },
            {
              'name': 'open',
            },
          ],
          'events': [
            {
              'key': 'INIT',
              'name': 'Initialize',
            },
            {
              'key': 'ADD_ITEM',
              'name': 'Add Item',
            },
            {
              'key': 'CLOSE',
              'name': 'Close',
            },
            {
              'key': 'SAVE',
              'name': 'Save',
              'payloadSchema': [
                {
                  'name': 'data',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'ITEM_ADDED',
              'name': 'Item Added',
            },
            {
              'key': 'CollectibleLoadFailed',
              'name': 'Collectible load failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CollectibleLoaded',
              'name': 'Collectible loaded',
              'payloadSchema': [
                {
                  'name': 'data',
                  'type': '[Collectible]',
                },
              ],
            },
            {
              'key': 'CollectibleSaveFailed',
              'name': 'Collectible save failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CollectibleSaved',
              'name': 'Collectible saved',
              'payloadSchema': [
                {
                  'name': 'id',
                  'type': 'string',
                },
              ],
            },
          ],
          'transitions': [
            {
              'from': 'closed',
              'to': 'closed',
              'event': 'INIT',
              'effects': [
                [
                  'fetch',
                  'Collectible',
                  {
                    'emit': {
                      'success': 'CollectibleLoaded',
                      'failure': 'CollectibleLoadFailed',
                    },
                  },
                ],
              ],
            },
            {
              'from': 'closed',
              'to': 'open',
              'event': 'ADD_ITEM',
              'effects': [
                [
                  'fetch',
                  'Collectible',
                  {
                    'emit': {
                      'success': 'CollectibleLoaded',
                      'failure': 'CollectibleLoadFailed',
                    },
                  },
                ],
                [
                  'render-ui',
                  'modal',
                  {
                    'type': 'stack',
                    'children': [
                      {
                        'type': 'stack',
                        'direction': 'horizontal',
                        'children': [
                          {
                            'type': 'icon',
                            'name': 'plus-circle',
                          },
                          {
                            'content': 'Add Collectible',
                            'variant': 'h3',
                            'type': 'typography',
                          },
                        ],
                        'gap': 'sm',
                      },
                      {
                        'type': 'divider',
                      },
                      {
                        'type': 'form-section',
                        'fields': [
                          'name',
                          'type',
                          'quantity',
                          'rarity',
                        ],
                        'cancelEvent': 'CLOSE',
                        'submitEvent': 'SAVE',
                        'mode': 'create',
                      },
                    ],
                    'direction': 'vertical',
                    'gap': 'md',
                  },
                ],
              ],
            },
            {
              'from': 'open',
              'to': 'closed',
              'event': 'CLOSE',
              'effects': [
                [
                  'render-ui',
                  'modal',
                  null,
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'type': 'box',
                  },
                ],
                [
                  'notify',
                  'Cancelled',
                  'info',
                ],
              ],
            },
            {
              'from': 'open',
              'to': 'closed',
              'event': 'SAVE',
              'effects': [
                [
                  'persist',
                  'create',
                  'Collectible',
                  '@payload.data',
                  {
                    'emit': {
                      'success': 'CollectibleSaved',
                      'failure': 'CollectibleSaveFailed',
                    },
                  },
                ],
                [
                  'render-ui',
                  'modal',
                  null,
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'type': 'box',
                  },
                ],
                [
                  'emit',
                  'ITEM_ADDED',
                ],
              ],
            },
          ],
        },
        'scope': 'collection',
      } as never, 'Collectible', canonicalName) as never,
      rebindInlineTraitEntity({
        'name': 'CollectibleUse',
        'category': 'interaction',
        'linkedEntity': 'Collectible',
        'emits': [
          {
            'event': 'ITEM_USED',
          },
          {
            'event': 'CollectibleLoadFailed',
            'description': 'Fired when Collectible fails to load',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'CollectibleLoaded',
            'description': 'Fired when Collectible finishes loading',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'data',
                'type': '[Collectible]',
              },
            ],
          },
          {
            'event': 'CollectibleUpdateFailed',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'CollectibleUpdated',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'id',
                'type': 'string',
              },
            ],
          },
        ],
        'listens': [
          {
            'event': 'USE_ITEM',
            'triggers': 'USE_ITEM',
            'source': {
              'kind': 'trait',
              'trait': 'CollectibleBrowse',
            },
          },
        ],
        'stateMachine': {
          'states': [
            {
              'name': 'closed',
              'isInitial': true,
            },
            {
              'name': 'open',
            },
          ],
          'events': [
            {
              'key': 'INIT',
              'name': 'Initialize',
            },
            {
              'key': 'USE_ITEM',
              'name': 'Use Item',
              'payloadSchema': [
                {
                  'name': 'id',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CLOSE',
              'name': 'Close',
            },
            {
              'key': 'SAVE',
              'name': 'Save',
              'payloadSchema': [
                {
                  'name': 'data',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'ITEM_USED',
              'name': 'Item Used',
            },
            {
              'key': 'CollectibleLoadFailed',
              'name': 'Collectible load failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CollectibleLoaded',
              'name': 'Collectible loaded',
              'payloadSchema': [
                {
                  'name': 'data',
                  'type': '[Collectible]',
                },
              ],
            },
            {
              'key': 'CollectibleUpdateFailed',
              'name': 'Collectible update failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CollectibleUpdated',
              'name': 'Collectible updated',
              'payloadSchema': [
                {
                  'name': 'id',
                  'type': 'string',
                },
              ],
            },
          ],
          'transitions': [
            {
              'from': 'closed',
              'to': 'closed',
              'event': 'INIT',
              'effects': [
                [
                  'set',
                  '@entity.name',
                  '',
                ],
                [
                  'fetch',
                  'Collectible',
                  {
                    'emit': {
                      'success': 'CollectibleLoaded',
                      'failure': 'CollectibleLoadFailed',
                    },
                  },
                ],
              ],
            },
            {
              'from': 'closed',
              'to': 'open',
              'event': 'USE_ITEM',
              'effects': [
                [
                  'fetch',
                  'Collectible',
                  {
                    'emit': {
                      'success': 'CollectibleLoaded',
                      'failure': 'CollectibleLoadFailed',
                    },
                    'id': '@payload.id',
                  },
                ],
                [
                  'render-ui',
                  'modal',
                  {
                    'children': [
                      {
                        'gap': 'sm',
                        'children': [
                          {
                            'type': 'icon',
                            'name': 'zap',
                          },
                          {
                            'content': 'Use Collectible',
                            'variant': 'h3',
                            'type': 'typography',
                          },
                        ],
                        'align': 'center',
                        'type': 'stack',
                        'direction': 'horizontal',
                      },
                      {
                        'type': 'divider',
                      },
                      {
                        'type': 'typography',
                        'variant': 'body',
                        'content': '@entity.name',
                      },
                      {
                        'gap': 'sm',
                        'direction': 'horizontal',
                        'children': [
                          {
                            'action': 'CLOSE',
                            'label': 'Cancel',
                            'type': 'button',
                            'variant': 'ghost',
                          },
                          {
                            'label': 'Confirm Use',
                            'type': 'button',
                            'variant': 'primary',
                            'action': 'SAVE',
                            'icon': 'check',
                          },
                        ],
                        'type': 'stack',
                        'justify': 'center',
                      },
                    ],
                    'gap': 'md',
                    'direction': 'vertical',
                    'type': 'stack',
                    'align': 'center',
                  },
                ],
              ],
            },
            {
              'from': 'open',
              'to': 'closed',
              'event': 'CLOSE',
              'effects': [
                [
                  'render-ui',
                  'modal',
                  null,
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'type': 'box',
                  },
                ],
                [
                  'notify',
                  'Cancelled',
                  'info',
                ],
              ],
            },
            {
              'from': 'open',
              'to': 'closed',
              'event': 'SAVE',
              'effects': [
                [
                  'persist',
                  'update',
                  'Collectible',
                  '@payload.data',
                  {
                    'emit': {
                      'failure': 'CollectibleUpdateFailed',
                      'success': 'CollectibleUpdated',
                    },
                  },
                ],
                [
                  'render-ui',
                  'modal',
                  null,
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'type': 'box',
                  },
                ],
                [
                  'emit',
                  'ITEM_USED',
                ],
              ],
            },
          ],
        },
        'scope': 'collection',
      } as never, 'Collectible', canonicalName) as never,
      rebindInlineTraitEntity({
        'name': 'CollectibleDrop',
        'category': 'interaction',
        'linkedEntity': 'Collectible',
        'emits': [
          {
            'event': 'CONFIRM_DROP',
          },
          {
            'event': 'CollectibleDeleteFailed',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'CollectibleDeleted',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'id',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'CollectibleLoadFailed',
            'description': 'Fired when Collectible fails to load',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
          },
          {
            'event': 'CollectibleLoaded',
            'description': 'Fired when Collectible finishes loading',
            'scope': 'internal',
            'payloadSchema': [
              {
                'name': 'data',
                'type': '[Collectible]',
              },
            ],
          },
        ],
        'listens': [
          {
            'event': 'DROP',
            'triggers': 'DROP',
            'source': {
              'kind': 'trait',
              'trait': 'CollectibleBrowse',
            },
          },
        ],
        'stateMachine': {
          'states': [
            {
              'name': 'idle',
              'isInitial': true,
            },
            {
              'name': 'confirming',
            },
          ],
          'events': [
            {
              'key': 'INIT',
              'name': 'Initialize',
            },
            {
              'key': 'DROP',
              'name': 'Drop',
              'payloadSchema': [
                {
                  'name': 'id',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CONFIRM_DROP',
              'name': 'Confirm Drop',
            },
            {
              'key': 'CANCEL',
              'name': 'Cancel',
            },
            {
              'key': 'CLOSE',
              'name': 'Close',
            },
            {
              'key': 'CollectibleDeleteFailed',
              'name': 'Collectible delete failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CollectibleDeleted',
              'name': 'Collectible deleted',
              'payloadSchema': [
                {
                  'name': 'id',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CollectibleLoadFailed',
              'name': 'Collectible load failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
            },
            {
              'key': 'CollectibleLoaded',
              'name': 'Collectible loaded',
              'payloadSchema': [
                {
                  'name': 'data',
                  'type': '[Collectible]',
                },
              ],
            },
          ],
          'transitions': [
            {
              'from': 'idle',
              'to': 'idle',
              'event': 'INIT',
              'effects': [
                [
                  'fetch',
                  'Collectible',
                  {
                    'emit': {
                      'success': 'CollectibleLoaded',
                      'failure': 'CollectibleLoadFailed',
                    },
                  },
                ],
              ],
            },
            {
              'from': 'idle',
              'to': 'confirming',
              'event': 'DROP',
              'effects': [
                [
                  'set',
                  '@entity.pendingId',
                  '@payload.id',
                ],
                [
                  'fetch',
                  'Collectible',
                  {
                    'id': '@payload.id',
                    'emit': {
                      'success': 'CollectibleLoaded',
                      'failure': 'CollectibleLoadFailed',
                    },
                  },
                ],
                [
                  'render-ui',
                  'modal',
                  {
                    'children': [
                      {
                        'children': [
                          {
                            'type': 'icon',
                            'name': 'alert-triangle',
                          },
                          {
                            'content': 'Drop Collectible',
                            'variant': 'h3',
                            'type': 'typography',
                          },
                        ],
                        'type': 'stack',
                        'direction': 'horizontal',
                        'gap': 'sm',
                        'align': 'center',
                      },
                      {
                        'type': 'divider',
                      },
                      {
                        'variant': 'error',
                        'message': 'Are you sure you want to drop this collectible?',
                        'type': 'alert',
                      },
                      {
                        'justify': 'end',
                        'type': 'stack',
                        'direction': 'horizontal',
                        'gap': 'sm',
                        'children': [
                          {
                            'action': 'CANCEL',
                            'label': 'Cancel',
                            'variant': 'ghost',
                            'type': 'button',
                          },
                          {
                            'label': 'Drop',
                            'icon': 'check',
                            'action': 'CONFIRM_DROP',
                            'type': 'button',
                            'variant': 'danger',
                          },
                        ],
                      },
                    ],
                    'direction': 'vertical',
                    'gap': 'md',
                    'type': 'stack',
                  },
                ],
              ],
            },
            {
              'from': 'confirming',
              'to': 'idle',
              'event': 'CONFIRM_DROP',
              'effects': [
                [
                  'persist',
                  'delete',
                  'Collectible',
                  '@entity.pendingId',
                  {
                    'emit': {
                      'success': 'CollectibleDeleted',
                      'failure': 'CollectibleDeleteFailed',
                    },
                  },
                ],
                [
                  'render-ui',
                  'modal',
                  null,
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'type': 'box',
                  },
                ],
                [
                  'fetch',
                  'Collectible',
                  {
                    'emit': {
                      'failure': 'CollectibleLoadFailed',
                      'success': 'CollectibleLoaded',
                    },
                  },
                ],
              ],
            },
            {
              'from': 'confirming',
              'to': 'idle',
              'event': 'CANCEL',
              'effects': [
                [
                  'render-ui',
                  'modal',
                  null,
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'type': 'box',
                  },
                ],
                [
                  'fetch',
                  'Collectible',
                  {
                    'emit': {
                      'failure': 'CollectibleLoadFailed',
                      'success': 'CollectibleLoaded',
                    },
                  },
                ],
              ],
            },
            {
              'from': 'confirming',
              'to': 'idle',
              'event': 'CLOSE',
              'effects': [
                [
                  'render-ui',
                  'modal',
                  null,
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'type': 'box',
                  },
                ],
                [
                  'fetch',
                  'Collectible',
                  {
                    'emit': {
                      'failure': 'CollectibleLoadFailed',
                      'success': 'CollectibleLoaded',
                    },
                  },
                ],
              ],
            },
          ],
        },
        'scope': 'collection',
      } as never, 'Collectible', canonicalName) as never,
    ],
    pages: [
      {
        'name': 'Collectibles',
        'path': '/collectibles',
        'traits': [
          {
            'ref': 'CollectibleBrowse',
          },
          {
            'ref': 'CollectibleAdd',
          },
          {
            'ref': 'CollectibleUse',
          },
          {
            'ref': 'CollectibleDrop',
          },
        ],
      } as never,
    ],
  });
  type _OrbTrait = OrbitalDefinition["traits"][number];
  type _OrbPage = NonNullable<OrbitalDefinition["pages"]>[number];
  type _RefOverride = Pick<MakeTraitRefOpts, "config" | "linkedEntity" | "events" | "name" | "emitsScope" | "listens">;
  if (built.traits && params.traitOverrides !== undefined) {
    built.traits = (built.traits as _OrbTrait[]).map((t): _OrbTrait => {
      if (!t || typeof t !== "object") return t;
      const tr = t as TraitReference & { name?: string };
      // Match by name so inline traits (no `ref`) and
      // reference traits (with `ref`) both pick up the
      // override surface keyed on the trait's `name`.
      if (typeof tr.name !== "string") return t;
      const overrides = params.traitOverrides as Record<string, _RefOverride | undefined> | undefined;
      const override = overrides?.[tr.name];
      if (!override) return t;
      const merged: TraitReference = { ...tr };
      if (override.config !== undefined) merged.config = { ...(tr.config ?? {}), ...override.config };
      if (override.linkedEntity !== undefined) merged.linkedEntity = override.linkedEntity;
      if (override.events !== undefined) merged.events = { ...(tr.events ?? {}), ...override.events };
      if (override.name !== undefined) merged.name = override.name;
      if (override.emitsScope !== undefined) merged.emitsScope = override.emitsScope;
      if (override.listens !== undefined) merged.listens = override.listens;
      return merged;
    });
  }
  if (built.pages && params.pagePath !== undefined) {
    built.pages = (built.pages as _OrbPage[]).map((p, idx) => {
      if (!p || typeof p !== "object") return p;
      if (idx !== 0) return p;
      const out = { ...p } as _OrbPage & { path?: string };
      out.path = params.pagePath;
      return out;
    });
  }
  return built;
}

/** Manifest — describes the params surface of stdPlatformerAppCollectibleOrbital. */
export const StdPlatformerAppCollectibleOrbitalManifest = {
  organism: 'std-platformer-app',
  orbitalName: 'CollectibleOrbital',
  paramFields: [
    { name: 'fields', type: 'EntityField[]', description: 'Extra fields appended to the canonical entity.' },
    { name: 'pagePath', type: 'string', description: 'URL override for the orbital first page.' },
    { name: 'persistence', type: "'persistent' | 'runtime' | 'singleton' | 'instance' | 'local'", description: 'Override the canonical entity persistence mode.' },
    { name: 'entityName', type: 'string', description: 'Rename the canonical entity. PascalCase singular, ≤32 chars. Threads through every trait\'s linkedEntity binding; compiler rewrites @Entity.x refs.' },
    { name: 'collection', type: 'string', description: 'Override derived collection key. Defaults to plural(entityName).toLowerCase().' },
    { name: 'traitOverrides', type: "Partial<Record<TraitName, { config?, linkedEntity?, events?, name?, emitsScope?, listens? }>>", description: 'Per-imported-trait overrides — mirrors .lolo\'s native trait-composition surface 1:1. effects is excluded (atom-owned; use listens via a sibling trait).' },
  ] as const,
  traitNames: [
  ] as const,
  inlineTraitNames: [
    'CollectibleBrowse',
    'CollectibleAdd',
    'CollectibleUse',
    'CollectibleDrop',
  ] as const,
};

/** Typed guard — runtime validates StdPlatformerAppCollectibleOrbitalParams keys. */
export function isStdPlatformerAppCollectibleOrbitalParams(p: object): p is StdPlatformerAppCollectibleOrbitalParams {
  type _OverrideRecord = NonNullable<StdPlatformerAppCollectibleOrbitalParams['traitOverrides']>;
  const obj = p as { traitOverrides?: _OverrideRecord };
  if (obj.traitOverrides !== undefined) {
    if (typeof obj.traitOverrides !== "object" || obj.traitOverrides === null) return false;
    const allowed: readonly string[] = [
      ...StdPlatformerAppCollectibleOrbitalManifest.traitNames,
      ...StdPlatformerAppCollectibleOrbitalManifest.inlineTraitNames,
    ];
    for (const k of Object.keys(obj.traitOverrides)) {
      if (!allowed.includes(k)) return false;
    }
  }
  return true;
}

/**
 * Bundled params for std-platformer-app — one optional entry per orbital.
 * Each entry maps to its per-orbital factory above.
 */
export interface StdPlatformerAppParams {
  PlatLevel?: StdPlatformerAppPlatLevelOrbitalParams;
  PlatScore?: StdPlatformerAppPlatScoreOrbitalParams;
  Collectible?: StdPlatformerAppCollectibleOrbitalParams;
}

/** Whole-organism descriptor (3 orbitals). Composes per-orbital factories. */
export function stdPlatformerApp(params: StdPlatformerAppParams = {}): OrbitalDefinition[] {
  return [
    stdPlatformerAppPlatLevelOrbital(params.PlatLevel ?? {}),
    stdPlatformerAppPlatScoreOrbital(params.PlatScore ?? {}),
    stdPlatformerAppCollectibleOrbital(params.Collectible ?? {}),
  ];
}
