/**
 * ui-law-reference-tooltip — LawReferenceTooltip — UI factory (1:1 with the @almadar/ui law-reference-tooltip pattern).
 *
 * Autogenerated by almadar-sync std-ts from
 * packages/almadar-std/behaviors/registry/atoms/ui-law-reference-tooltip.orb.
 *
 * This is a thin descriptor layer over the canonical .orb. The exported
 * functions return TraitReference / PageRefObject / OrbitalDefinition
 * payloads that reference the sibling .orb via `uses:` + `ref:`. The
 * compiler's inline phase materialises the real trait at build time.
 *
 * Do not hand-edit — regenerate via
 *   npx almadar-sync std-ts --only=ui-law-reference-tooltip
 *
 * @level atom
 * @packageDocumentation
 */

import type { TraitReference, PageRefObject, OrbitalDefinition, Entity, EntityField, EntityPersistence, TraitConfig, TraitFieldRef, EntityRow, SExpr, TraitEventListener, Trait, StateMachine } from '@almadar/core/types';
import type { MakeTraitRefOpts } from '@almadar/core/builders';
import { makeTraitRef, makePageRef, makeOrbitalWithUses } from '@almadar/core/builders';
import { rebindInlineTraitEntity } from '../../../../../factory-runtime/apply-params-to-orb.js';

const BEHAVIOR_PATH = 'std/behaviors/ui-law-reference-tooltip';
const ALIAS = 'UiLawReferenceTooltip';

/**
 * Closed set of event keys this trait recognises —
 * derived from the .orb's `stateMachine.events[]` block
 * (transition triggers + emit names). Use as the key type
 * when passing an `events:` rename map at the call site.
 */
export type StdUiLawReferenceTooltipEventKey = 'INIT';

/**
 * Typed call-site config block for this trait — every
 * field maps to a `config { ... }` entry in the source
 * .lolo. The agent fills these to specialise the trait
 * without modifying its state-machine topology.
 */
export interface StdUiLawReferenceTooltipConfig {
  /** Default: `{"law":"","article":""}` */
  reference?: EntityRow;
  /** Default: `"top"` */
  position?: 'top' | 'bottom' | 'left' | 'right';
  /** Default: `""` */
  className?: string;
}

/**
 * Params for the ui-law-reference-tooltip descriptor helpers.
 *
 * `entityName` binds every trait/page reference's `linkedEntity`.
 * The optional override fields mirror TraitReference / PageRefObject
 * fields and are forwarded to `makeTraitRef` / `makePageRef`.
 */
export interface StdUiLawReferenceTooltipParams {
  entityName: string;
  /** Extra fields to add to the orbital-scoped entity clone. */
  fields?: EntityField[];
  /** Entity persistence mode. Defaults to `persistent` when omitted.
   *  See @almadar/core EntityPersistence: persistent | runtime | singleton | instance | local. */
  persistence?: EntityPersistence;
  /** Rename the inlined trait at the call site. */
  traitName?: string;
  /** Per-key event rename map. Keys narrow to the trait's declared emit names. */
  events?: Partial<Record<StdUiLawReferenceTooltipEventKey, string>>;
  /** Per-event effect replacement (keys are POST-rename event names). */
  effects?: Record<string, SExpr[]>;
  /** Replace the imported trait's `listens` array entirely. */
  listens?: TraitEventListener[];
  /** Set every emit's scope. */
  emitsScope?: 'internal' | 'external';
  /** Typed call-site config block — see the per-field interface. */
  config?: StdUiLawReferenceTooltipConfig;
  /** URL path override for the (first) page. */
  pagePath?: string;
}

/** Trait descriptor: `UiLawReferenceTooltip.traits.LawReferenceTooltipRender`. */
export function stdUiLawReferenceTooltipTrait(params: StdUiLawReferenceTooltipParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.LawReferenceTooltipRender`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Page descriptor: `UiLawReferenceTooltip.pages.LawReferenceTooltipPage`. */
export function stdUiLawReferenceTooltipPage(params: StdUiLawReferenceTooltipParams): PageRefObject {
  return makePageRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.pages.LawReferenceTooltipPage`,
    ...(params.pagePath !== undefined ? { path: params.pagePath } : {}),
    linkedEntity: params.entityName,
  });
}

/** Whole-orbital descriptor. */
export function stdUiLawReferenceTooltip(params: StdUiLawReferenceTooltipParams): OrbitalDefinition {
  const entity: Entity = {
    name: params.entityName,
    fields: params.fields ?? [],
    ...(params.persistence !== undefined ? { persistence: params.persistence } : {}),
  };
  return makeOrbitalWithUses({
    name: 'LawReferenceTooltipOrbital',
    uses: [{ from: BEHAVIOR_PATH, as: ALIAS }],
    entity,
    traits: [
      stdUiLawReferenceTooltipTrait(params),
    ],
    pages: [
      stdUiLawReferenceTooltipPage(params),
    ],
  });
}
