/**
 * Entity Types
 *
 * TypeScript interfaces for all entities. Each extends `EntityRow`
 * from `@almadar/core` so generated rows flow into the canonical
 * persisted-entity shape without casts.
 *
 * Auto-generated by Orbital Compiler.
 *
 * @packageDocumentation
 */

import type { EntityRow, FieldValue } from '@almadar/core';

export type WizardViewCategory = 'marketing' | 'engineering' | 'design' | 'operations' | '';

export type WizardViewPriority = 'low' | 'medium' | 'high' | 'urgent' | '';

/**
 * WizardView entity
 */
export interface WizardView extends EntityRow {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  title: string;
  description: string;
  category: WizardViewCategory;
  priority: WizardViewPriority;
  notes: string;
  wizardSteps: { description?: string; id: string; title: string }[];
  currentStepIndex: number;
  totalSteps: number;
  currentStepLabel: string;
  currentStepDescription: string;
  currentStepIcon: string;
  currentFields: string[];
  isFirstStep: boolean;
  isLastStep: boolean;
  primaryActionLabel: string;
  primaryActionIcon: string;
  completionMessage: string;
  cancelReason: string;
  errorMessage: string;
}
/**
 * WizardView input (for creation)
 */
export interface WizardViewInput {
  title: string;
  description: string;
  category: 'marketing' | 'engineering' | 'design' | 'operations' | '';
  priority: 'low' | 'medium' | 'high' | 'urgent' | '';
  notes: string;
  wizardSteps: { description?: string; id: string; title: string }[];
  currentStepIndex: number;
  totalSteps: number;
  currentStepLabel: string;
  currentStepDescription: string;
  currentStepIcon: string;
  currentFields: string[];
  isFirstStep: boolean;
  isLastStep: boolean;
  primaryActionLabel: string;
  primaryActionIcon: string;
  completionMessage: string;
  cancelReason: string;
  errorMessage: string;
}

/**
 * WizardView update (partial)
 */
export type WizardViewUpdate = Partial<WizardViewInput>;

