/**
 * ui-battle-template — BattleTemplate — UI factory (1:1 with the @almadar/ui battle-template pattern).
 *
 * Autogenerated by almadar-sync std-ts from
 * packages/almadar-std/behaviors/registry/templates/ui-battle-template.orb.
 *
 * This is a thin descriptor layer over the canonical .orb. The exported
 * functions return TraitReference / PageRefObject / OrbitalDefinition
 * payloads that reference the sibling .orb via `uses:` + `ref:`. The
 * compiler's inline phase materialises the real trait at build time.
 *
 * Do not hand-edit — regenerate via
 *   npx almadar-sync std-ts --only=ui-battle-template
 *
 * @level template
 * @packageDocumentation
 */

import type { TraitReference, PageRefObject, OrbitalDefinition, Entity, EntityField, EntityPersistence, TraitConfig, TraitFieldRef, EntityRow, SExpr, TraitEventListener, Trait, StateMachine } from '@almadar/core/types';
import type { MakeTraitRefOpts } from '@almadar/core/builders';
import { makeTraitRef, makePageRef, makeOrbitalWithUses } from '@almadar/core/builders';
import { rebindInlineTraitEntity } from '../../../../../factory-runtime/apply-params-to-orb.js';

const BEHAVIOR_PATH = 'std/behaviors/ui-battle-template';
const ALIAS = 'UiBattleTemplate';

/**
 * Closed set of event keys this trait recognises —
 * derived from the .orb's `stateMachine.events[]` block
 * (transition triggers + emit names). Use as the key type
 * when passing an `events:` rename map at the call site.
 */
export type StdUiBattleTemplateEventKey = 'INIT';

/**
 * Typed call-site config block for this trait — every
 * field maps to a `config { ... }` entry in the source
 * .lolo. The agent fills these to specialise the trait
 * without modifying its state-machine topology.
 */
export interface StdUiBattleTemplateConfig {
  /** Default: `[{"x":0,"terrain":"stone","y":0,"passable":false},{"passable":false,"x":1,"terrain":"stone","y":0},{"terrain":"stone","x":2,"passable":false,"y":0},{"x":3,"y":0,"terrain":"stone","passable":false},{"terrain":"stone","passable":false,"x":4,"y":0},{"terrain":"stone","y":1,"x":0,"passable":false},{"x":1,"passable":true,"terrain":"dirt","y":1},{"y":1,"x":2,"terrain":"grass","passable":true},{"terrain":"grass","passable":true,"y":1,"x":3},{"passable":false,"x":4,"y":1,"terrain":"stone"},{"passable":false,"terrain":"stone","x":0,"y":2},{"x":1,"terrain":"grass","passable":true,"y":2},{"y":2,"x":2,"terrain":"dirt","passable":true},{"terrain":"grass","y":2,"x":3,"passable":true},{"passable":false,"terrain":"stone","x":4,"y":2},{"passable":false,"x":0,"terrain":"stone","y":3},{"x":1,"terrain":"grass","passable":true,"y":3},{"x":2,"terrain":"grass","y":3,"passable":true},{"x":3,"y":3,"passable":true,"terrain":"dirt"},{"passable":false,"x":4,"terrain":"stone","y":3},{"x":0,"y":4,"terrain":"stone","passable":false},{"passable":false,"y":4,"terrain":"stone","x":1},{"passable":false,"terrain":"stone","y":4,"x":2},{"terrain":"stone","x":3,"passable":false,"y":4},{"x":4,"y":4,"passable":false,"terrain":"stone"}]` */
  tiles?: EntityRow[];
  /** Default: `0.45` */
  scale?: number;
  /** Default: `[{"id":"f1","y":2,"type":"gold_mine","x":2},{"y":1,"id":"f2","x":3,"type":"portal"}]` */
  features?: EntityRow[];
  /** Default: `""` */
  assetManifest?: string;
  /** Default: `[{"maxHealth":10,"unitType":"worker","name":"Worker","team":"player","id":"u1","position":{"x":1,"y":1},"health":10},{"position":{"x":3,"y":3},"health":8,"unitType":"guardian","name":"Guardian","team":"enemy","id":"u2","maxHealth":10}]` */
  units?: EntityRow[];
  /** Default: `""` */
  className?: string;
  /** Default: `1` */
  unitScale?: number;
}

/**
 * Params for the ui-battle-template descriptor helpers.
 *
 * `entityName` binds every trait/page reference's `linkedEntity`.
 * The optional override fields mirror TraitReference / PageRefObject
 * fields and are forwarded to `makeTraitRef` / `makePageRef`.
 */
export interface StdUiBattleTemplateParams {
  entityName: string;
  /** Extra fields to add to the orbital-scoped entity clone. */
  fields?: EntityField[];
  /** Entity persistence mode. Defaults to `persistent` when omitted.
   *  See @almadar/core EntityPersistence: persistent | runtime | singleton | instance | local. */
  persistence?: EntityPersistence;
  /** Rename the inlined trait at the call site. */
  traitName?: string;
  /** Per-key event rename map. Keys narrow to the trait's declared emit names. */
  events?: Partial<Record<StdUiBattleTemplateEventKey, string>>;
  /** Per-event effect replacement (keys are POST-rename event names). */
  effects?: Record<string, SExpr[]>;
  /** Replace the imported trait's `listens` array entirely. */
  listens?: TraitEventListener[];
  /** Set every emit's scope. */
  emitsScope?: 'internal' | 'external';
  /** Typed call-site config block — see the per-field interface. */
  config?: StdUiBattleTemplateConfig;
  /** URL path override for the (first) page. */
  pagePath?: string;
}

/** Trait descriptor: `UiBattleTemplate.traits.BattleTemplateRender`. */
export function stdUiBattleTemplateTrait(params: StdUiBattleTemplateParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.BattleTemplateRender`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Page descriptor: `UiBattleTemplate.pages.BattleTemplatePage`. */
export function stdUiBattleTemplatePage(params: StdUiBattleTemplateParams): PageRefObject {
  return makePageRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.pages.BattleTemplatePage`,
    ...(params.pagePath !== undefined ? { path: params.pagePath } : {}),
    linkedEntity: params.entityName,
  });
}

/** Whole-orbital descriptor. */
export function stdUiBattleTemplate(params: StdUiBattleTemplateParams): OrbitalDefinition {
  const entity: Entity = {
    name: params.entityName,
    fields: params.fields ?? [],
    ...(params.persistence !== undefined ? { persistence: params.persistence } : {}),
  };
  return makeOrbitalWithUses({
    name: 'BattleTemplateOrbital',
    uses: [{ from: BEHAVIOR_PATH, as: ALIAS }],
    entity,
    traits: [
      stdUiBattleTemplateTrait(params),
    ],
    pages: [
      stdUiBattleTemplatePage(params),
    ],
  });
}
