/**
 * ui-graph-canvas — GraphCanvas — UI factory (1:1 with the @almadar/ui graph-canvas pattern).
 *
 * Autogenerated by almadar-sync std-ts from
 * packages/almadar-std/behaviors/registry/organisms/ui-graph-canvas.orb.
 *
 * This is a thin descriptor layer over the canonical .orb. The exported
 * functions return TraitReference / PageRefObject / OrbitalDefinition
 * payloads that reference the sibling .orb via `uses:` + `ref:`. The
 * compiler's inline phase materialises the real trait at build time.
 *
 * Do not hand-edit — regenerate via
 *   npx almadar-sync std-ts --only=ui-graph-canvas
 *
 * @level organism
 * @packageDocumentation
 */

import type { TraitReference, PageRefObject, OrbitalDefinition, Entity, EntityField, EntityPersistence, TraitConfig, TraitFieldRef, EntityRow, SExpr, TraitEventListener, Trait, StateMachine } from '@almadar/core/types';
import type { MakeTraitRefOpts } from '@almadar/core/builders';
import { makeTraitRef, makePageRef, makeOrbitalWithUses } from '@almadar/core/builders';
import { rebindInlineTraitEntity } from '../../../../../factory-runtime/apply-params-to-orb.js';

const BEHAVIOR_PATH = 'std/behaviors/ui-graph-canvas';
const ALIAS = 'UiGraphCanvas';

/**
 * Closed set of event keys this trait recognises —
 * derived from the .orb's `stateMachine.events[]` block
 * (transition triggers + emit names). Use as the key type
 * when passing an `events:` rename map at the call site.
 */
export type StdUiGraphCanvasEventKey = 'INIT' | 'NODE_CLICK';

/**
 * Payload shape for the `NODE_CLICK` event.
 */
export interface StdUiGraphCanvasNodeClickPayload {
  node?: EntityRow;
  id: string;
}

/**
 * Typed call-site config block for this trait — every
 * field maps to a `config { ... }` entry in the source
 * .lolo. The agent fills these to specialise the trait
 * without modifying its state-machine topology.
 */
export interface StdUiGraphCanvasConfig {
  /** Default: `false` */
  isLoading?: boolean;
  /** Default: `""` */
  className?: string;
  /** Default: `[]` */
  actions?: EntityRow[];
  /** Default: `true` */
  interactive?: boolean;
  error?: EntityRow;
  /** Default: `[]` */
  edges?: EntityRow[];
  /** Default: `400` */
  height?: number;
  /** Default: `[]` */
  nodes?: EntityRow[];
  /** Default: `true` */
  showLabels?: boolean;
  /** Default: `""` */
  title?: string;
  /** Default: `true` */
  draggable?: boolean;
  /** Default: `"force"` */
  layout?: 'force' | 'circular' | 'grid';
}

/**
 * Tunable params for the GraphCanvasOrbital orbital.
 *
 * Canonical entity: GraphCanvasItem — overridable via
 * `entityName`. The factory threads the effective name through every
 * trait's `linkedEntity` binding; the `.orb` compiler's inline phase
 * auto-rewrites every `@Entity.x`, `["ref",X]`, `["fetch",X,…]`,
 * `["persist",…,X,…]` and payload type string accordingly.
 *
 * Override surface (mirrors `.lolo`'s native overrides 1:1):
 *   fields         — extra entity fields (appended)
 *   pagePath       — first-page URL override
 *   persistence    — entity persistence mode
 *   entityName     — rename the canonical entity
 *   collection     — override the derived collection key
 *   traitOverrides — per-imported-trait `config`, `linkedEntity`,
 *                    `events`, `name`, `emitsScope`, `listens`.
 *                    `effects` is NOT exposed — `.lolo` removed it
 *                    in Phase 9.5.H. Use `listens` via a sibling
 *                    trait to react to atom events.
 */
export interface StdUiGraphCanvasGraphCanvasOrbitalParams {
  /** Extra fields appended to the canonical entity. */
  fields?: EntityField[];
  /** URL path override for the orbital's first page. */
  pagePath?: string;
  /** Override the canonical entity persistence mode. */
  persistence?: EntityPersistence;
  /** Rename the canonical entity (PascalCase singular, ≤32 chars). */
  entityName?: string;
  /** Override derived collection key (defaults to plural(entityName).toLowerCase()). */
  collection?: string;
  /**
   * Per-imported-trait override surface keyed on each imported
   * trait's canonical `name`. Accepts every override `.lolo`
   * natively supports: `config`, `linkedEntity`, `events`,
   * `name`, `emitsScope`, `listens`. `effects` is excluded —
   * atom-owned (use `listens` via a sibling trait instead).
   */
  traitOverrides?: Partial<Record<
    'GraphCanvasRender',
    Pick<MakeTraitRefOpts, 'config' | 'linkedEntity' | 'events' | 'name' | 'emitsScope' | 'listens'>
  >>;
}

/** Per-orbital factory: builds the GraphCanvasOrbital orbital with consumer params. */
export function stdUiGraphCanvasGraphCanvasOrbital(params: StdUiGraphCanvasGraphCanvasOrbitalParams = {}): OrbitalDefinition {
  const canonicalName = params.entityName ?? 'GraphCanvasItem';
  const built = makeOrbitalWithUses({
    name: 'GraphCanvasOrbital',
    uses: [],
    entity: {
      name: canonicalName,
      persistence: params.persistence ?? 'runtime',
      fields: ((): EntityField[] => {
        const canonical: EntityField[] = [
          {
            'name': 'id',
            'type': 'string',
            'required': true,
          },
        ];
        const extras = params.fields ?? [];
        if (extras.length === 0) return canonical;
        const extraNames = new Set(extras.map((f) => f.name));
        return [...canonical.filter((f) => !extraNames.has(f.name)), ...extras];
      })(),
    } as Entity,
    traits: [
      rebindInlineTraitEntity({
        'name': 'GraphCanvasRender',
        'entityRebindable': true,
        'entityContract': {
          'requires': [],
          'provides': [],
        },
        'category': 'interaction',
        'linkedEntity': 'GraphCanvasItem',
        'emits': [
          {
            'event': 'NODE_CLICK',
            'description': 'On node click',
            'tier': 'essential',
            'scope': 'external',
            'payloadSchema': [
              {
                'name': 'node',
                'type': 'object',
              },
              {
                'name': 'id',
                'type': 'string',
                'required': true,
              },
            ],
          },
        ],
        'stateMachine': {
          'states': [
            {
              'name': 'idle',
              'isInitial': true,
            },
          ],
          'events': [
            {
              'key': 'INIT',
              'name': 'Initialize',
            },
            {
              'key': 'NODE_CLICK',
              'name': 'Node Click',
              'description': 'On node click',
              'tier': 'essential',
            },
          ],
          'transitions': [
            {
              'from': 'idle',
              'to': 'idle',
              'event': 'INIT',
              'effects': [
                [
                  'fetch',
                  'GraphCanvasItem',
                  {},
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'showLabels': '@config.showLabels',
                    'draggable': '@config.draggable',
                    'height': '@config.height',
                    'title': '@config.title',
                    'edges': '@config.edges',
                    'nodes': '@config.nodes',
                    'nodeClickEvent': 'NODE_CLICK',
                    'layout': '@config.layout',
                    'entity': 'GraphCanvasItem',
                    'className': '@config.className',
                    'onNodeClick': 'NODE_CLICK',
                    'error': '@config.error',
                    'interactive': '@config.interactive',
                    'actions': '@config.actions',
                    'isLoading': '@config.isLoading',
                    'type': 'graph-canvas',
                  },
                ],
              ],
            },
          ],
        },
        'config': {
          'isLoading': {
            'type': 'boolean',
            'default': false,
            'label': 'Is Loading',
            'description': 'Loading state',
            'tier': 'presentation',
          },
          'className': {
            'type': 'string',
            'default': '',
            'label': 'Class Name',
            'description': 'Additional CSS classes',
            'tier': 'presentation',
          },
          'actions': {
            'type': '[GraphCanvasActionsItem]',
            'default': [],
            'label': 'Actions',
            'description': 'Actions',
            'tier': 'presentation',
            'items': {
              'type': 'object',
              'properties': {
                'variant': {
                  'name': 'variant',
                  'type': 'string',
                  'required': false,
                  'values': [
                    'primary',
                    'secondary',
                    'ghost',
                  ],
                },
                'label': {
                  'name': 'label',
                  'type': 'string',
                  'required': true,
                },
                'event': {
                  'name': 'event',
                  'type': 'string',
                  'required': false,
                },
                'navigatesTo': {
                  'name': 'navigatesTo',
                  'type': 'string',
                  'required': false,
                },
              },
            },
          },
          'interactive': {
            'type': 'boolean',
            'default': true,
            'label': 'Interactive',
            'description': 'Enable zoom/pan',
            'tier': 'presentation',
          },
          'error': {
            'type': 'GraphCanvasError',
            'label': 'Error',
            'description': 'Error state',
            'tier': 'presentation',
            'properties': {
              'code': {
                'name': 'code',
                'type': 'string',
                'required': false,
              },
              'name': {
                'name': 'name',
                'type': 'string',
                'required': false,
              },
              'stack': {
                'name': 'stack',
                'type': 'string',
                'required': false,
              },
              'message': {
                'name': 'message',
                'type': 'string',
                'required': true,
              },
            },
          },
          'edges': {
            'type': '[GraphCanvasEdgesItem]',
            'default': [],
            'label': 'Edges',
            'description': 'Graph edges',
            'tier': 'presentation',
            'items': {
              'type': 'object',
              'properties': {
                'weight': {
                  'name': 'weight',
                  'type': 'number',
                  'required': false,
                },
                'color': {
                  'name': 'color',
                  'type': 'string',
                  'required': false,
                },
                'label': {
                  'name': 'label',
                  'type': 'string',
                  'required': false,
                },
                'target': {
                  'name': 'target',
                  'type': 'string',
                  'required': true,
                },
                'source': {
                  'name': 'source',
                  'type': 'string',
                  'required': true,
                },
              },
            },
          },
          'height': {
            'type': 'number',
            'default': 400,
            'label': 'Height',
            'description': 'Canvas height',
            'tier': 'presentation',
          },
          'nodes': {
            'type': '[GraphCanvasNodesItem]',
            'default': [],
            'label': 'Nodes',
            'description': 'Graph nodes',
            'tier': 'presentation',
            'items': {
              'type': 'object',
              'properties': {
                'label': {
                  'name': 'label',
                  'type': 'string',
                  'required': false,
                },
                'y': {
                  'name': 'y',
                  'type': 'number',
                  'required': false,
                },
                'size': {
                  'name': 'size',
                  'type': 'number',
                  'required': false,
                },
                'x': {
                  'name': 'x',
                  'type': 'number',
                  'required': false,
                },
                'id': {
                  'name': 'id',
                  'type': 'string',
                  'required': true,
                },
                'group': {
                  'name': 'group',
                  'type': 'string',
                  'required': false,
                },
                'color': {
                  'name': 'color',
                  'type': 'string',
                  'required': false,
                },
              },
            },
          },
          'showLabels': {
            'type': 'boolean',
            'default': true,
            'label': 'Show Labels',
            'description': 'Show node labels',
            'tier': 'presentation',
          },
          'title': {
            'type': 'string',
            'default': '',
            'label': 'Title',
            'description': 'Graph title',
            'tier': 'presentation',
          },
          'draggable': {
            'type': 'boolean',
            'default': true,
            'label': 'Draggable',
            'description': 'Enable node dragging',
            'tier': 'presentation',
          },
          'layout': {
            'type': 'string',
            'default': 'force',
            'label': 'Layout',
            'description': 'Layout algorithm',
            'tier': 'presentation',
            'values': [
              'force',
              'circular',
              'grid',
            ],
          },
        },
        'scope': 'instance',
      } as never, 'GraphCanvasItem', canonicalName) as never,
    ],
    pages: [
      {
        'name': 'GraphCanvasPage',
        'path': '/graph-canvas',
        'traits': [
          {
            'ref': 'GraphCanvasRender',
          },
        ],
      } as never,
    ],
  });
  type _OrbTrait = OrbitalDefinition["traits"][number];
  type _OrbPage = NonNullable<OrbitalDefinition["pages"]>[number];
  type _RefOverride = Pick<MakeTraitRefOpts, "config" | "linkedEntity" | "events" | "name" | "emitsScope" | "listens">;
  if (built.traits && params.traitOverrides !== undefined) {
    built.traits = (built.traits as _OrbTrait[]).map((t): _OrbTrait => {
      if (!t || typeof t !== "object") return t;
      const tr = t as TraitReference & { name?: string };
      // Match by name so inline traits (no `ref`) and
      // reference traits (with `ref`) both pick up the
      // override surface keyed on the trait's `name`.
      if (typeof tr.name !== "string") return t;
      const overrides = params.traitOverrides as Record<string, _RefOverride | undefined> | undefined;
      const override = overrides?.[tr.name];
      if (!override) return t;
      const merged: TraitReference = { ...tr };
      if (override.config !== undefined) merged.config = { ...(tr.config ?? {}), ...override.config };
      if (override.linkedEntity !== undefined) merged.linkedEntity = override.linkedEntity;
      if (override.events !== undefined) merged.events = { ...(tr.events ?? {}), ...override.events };
      if (override.name !== undefined) merged.name = override.name;
      if (override.emitsScope !== undefined) merged.emitsScope = override.emitsScope;
      if (override.listens !== undefined) merged.listens = override.listens;
      return merged;
    });
  }
  if (built.pages && params.pagePath !== undefined) {
    built.pages = (built.pages as _OrbPage[]).map((p, idx) => {
      if (!p || typeof p !== "object") return p;
      if (idx !== 0) return p;
      const out = { ...p } as _OrbPage & { path?: string };
      out.path = params.pagePath;
      return out;
    });
  }
  return built;
}

/** Manifest — describes the params surface of stdUiGraphCanvasGraphCanvasOrbital. */
export const StdUiGraphCanvasGraphCanvasOrbitalManifest = {
  organism: 'ui-graph-canvas',
  orbitalName: 'GraphCanvasOrbital',
  paramFields: [
    { name: 'fields', type: 'EntityField[]', description: 'Extra fields appended to the canonical entity.' },
    { name: 'pagePath', type: 'string', description: 'URL override for the orbital first page.' },
    { name: 'persistence', type: "'persistent' | 'runtime' | 'singleton' | 'instance' | 'local'", description: 'Override the canonical entity persistence mode.' },
    { name: 'entityName', type: 'string', description: 'Rename the canonical entity. PascalCase singular, ≤32 chars. Threads through every trait\'s linkedEntity binding; compiler rewrites @Entity.x refs.' },
    { name: 'collection', type: 'string', description: 'Override derived collection key. Defaults to plural(entityName).toLowerCase().' },
    { name: 'traitOverrides', type: "Partial<Record<TraitName, { config?, linkedEntity?, events?, name?, emitsScope?, listens? }>>", description: 'Per-imported-trait overrides — mirrors .lolo\'s native trait-composition surface 1:1. effects is excluded (atom-owned; use listens via a sibling trait).' },
  ] as const,
  traitNames: [
  ] as const,
  inlineTraitNames: [
    'GraphCanvasRender',
  ] as const,
};

/** Typed guard — runtime validates StdUiGraphCanvasGraphCanvasOrbitalParams keys. */
export function isStdUiGraphCanvasGraphCanvasOrbitalParams(p: object): p is StdUiGraphCanvasGraphCanvasOrbitalParams {
  type _OverrideRecord = NonNullable<StdUiGraphCanvasGraphCanvasOrbitalParams['traitOverrides']>;
  const obj = p as { traitOverrides?: _OverrideRecord };
  if (obj.traitOverrides !== undefined) {
    if (typeof obj.traitOverrides !== "object" || obj.traitOverrides === null) return false;
    const allowed: readonly string[] = [
      ...StdUiGraphCanvasGraphCanvasOrbitalManifest.traitNames,
      ...StdUiGraphCanvasGraphCanvasOrbitalManifest.inlineTraitNames,
    ];
    for (const k of Object.keys(obj.traitOverrides)) {
      if (!allowed.includes(k)) return false;
    }
  }
  return true;
}

/**
 * Bundled params for ui-graph-canvas — one optional entry per orbital.
 * Each entry maps to its per-orbital factory above.
 */
export interface StdUiGraphCanvasParams {
  GraphCanvas?: StdUiGraphCanvasGraphCanvasOrbitalParams;
}

/** Whole-organism descriptor (1 orbitals). Composes per-orbital factories. */
export function stdUiGraphCanvas(params: StdUiGraphCanvasParams = {}): OrbitalDefinition[] {
  return [
    stdUiGraphCanvasGraphCanvasOrbital(params.GraphCanvas ?? {}),
  ];
}
