/**
 * std-score — Headless scoring mechanic: awards points when the enemy survivor count drops on a UNITS_CHANGED signal. Owns only score (+ its kill baseline); renders nothing.
 *
 * Autogenerated by almadar-sync std-ts from
 * packages/almadar-std/behaviors/registry/atoms/std-score.orb.
 *
 * This is a thin descriptor layer over the canonical .orb. The exported
 * functions return TraitReference / PageRefObject / OrbitalDefinition
 * payloads that reference the sibling .orb via `uses:` + `ref:`. The
 * compiler's inline phase materialises the real trait at build time.
 *
 * Do not hand-edit — regenerate via
 *   npx almadar-sync std-ts --only=std-score
 *
 * @level atom
 * @packageDocumentation
 */

import type { TraitReference, PageRefObject, OrbitalDefinition, Entity, EntityField, EntityPersistence, TraitConfig, TraitFieldRef, EntityRow, SExpr, TraitEventListener, Trait, StateMachine, Page } from '@almadar/core/types';
import type { MakeTraitRefOpts } from '@almadar/core/builders';
import { makeTraitRef, makePageRef, makeOrbitalWithUses } from '@almadar/core/builders';
import { rebindInlineTraitEntity, mergeCallSiteConfigOverrides } from '../../../../../factory-runtime/apply-params-to-orb.js';

const BEHAVIOR_PATH = 'std/behaviors/std-score';
const ALIAS = 'Score';

/**
 * Closed set of event keys this trait recognises —
 * derived from the .orb's `stateMachine.events[]` block
 * (transition triggers + emit names). Use as the key type
 * when passing an `events:` rename map at the call site.
 */
export type StdScoreEventKey = 'INIT' | 'UNITS_CHANGED';

/**
 * Typed call-site config block for this trait — every
 * field maps to a `config { ... }` entry in the source
 * .lolo. The agent fills these to specialise the trait
 * without modifying its state-machine topology.
 */
export interface StdScoreConfig {
  /** Default: `0` */
  initialEnemies?: number;
  /** Default: `10` */
  pointsPerKill?: number;
  /** Default: `true` */
  running?: boolean;
  /** Default: `0` */
  startScore?: number;
}

/**
 * Params for the std-score descriptor helpers.
 *
 * `entityName` binds every trait/page reference's `linkedEntity`.
 * The optional override fields mirror TraitReference / PageRefObject
 * fields and are forwarded to `makeTraitRef` / `makePageRef`.
 */
export interface StdScoreParams {
  entityName: string;
  /** Extra fields to add to the orbital-scoped entity clone. */
  fields?: EntityField[];
  /** Rename the inlined trait at the call site. */
  traitName?: string;
  /** Per-key event rename map. Keys narrow to the trait's declared emit names. */
  events?: Partial<Record<StdScoreEventKey, string>>;
  /** Per-event effect replacement (keys are POST-rename event names). */
  effects?: Record<string, SExpr[]>;
  /** Replace the imported trait's `listens` array entirely. */
  listens?: TraitEventListener[];
  /** Set every emit's scope. */
  emitsScope?: 'internal' | 'external';
  /** Typed call-site config block — see the per-field interface. */
  config?: StdScoreConfig;
  /** URL path override for the (first) page. */
  pagePath?: string;
}

/** Trait descriptor: `Score.traits.ScoreKeeper`. */
export function stdScoreTrait(params: StdScoreParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.ScoreKeeper`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Page descriptor: `Score.pages.ScorePage`. */
export function stdScorePage(params: StdScoreParams): PageRefObject {
  return makePageRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.pages.ScorePage`,
    ...(params.pagePath !== undefined ? { path: params.pagePath } : {}),
    linkedEntity: params.entityName,
  });
}

/** Whole-orbital descriptor. */
export function stdScore(params: StdScoreParams): OrbitalDefinition {
  const entity: Entity = {
    name: params.entityName,
    fields: params.fields ?? [],
    persistence: 'runtime',
  };
  return makeOrbitalWithUses({
    name: 'ScoreOrbital',
    uses: [{ from: BEHAVIOR_PATH, as: ALIAS }],
    entity,
    traits: [
      stdScoreTrait(params),
    ],
    pages: [
      stdScorePage(params),
    ],
  });
}
