/**
 * ui-visual-novel-board — VisualNovelBoard — game-shell composition: dialogue-bubble atom for speaker/text/portrait; LOLO drives CHOOSE/ADVANCE.
 *
 * Autogenerated by almadar-sync std-ts from
 * packages/almadar-std/behaviors/registry/organisms/ui-visual-novel-board.orb.
 *
 * This is a thin descriptor layer over the canonical .orb. The exported
 * functions return TraitReference / PageRefObject / OrbitalDefinition
 * payloads that reference the sibling .orb via `uses:` + `ref:`. The
 * compiler's inline phase materialises the real trait at build time.
 *
 * Do not hand-edit — regenerate via
 *   npx almadar-sync std-ts --only=ui-visual-novel-board
 *
 * @level organism
 * @packageDocumentation
 */

import type { TraitReference, PageRefObject, OrbitalDefinition, Entity, EntityField, EntityPersistence, TraitConfig, TraitFieldRef, EntityRow, SExpr, TraitEventListener, Trait, StateMachine, Page } from '@almadar/core/types';
import type { MakeTraitRefOpts } from '@almadar/core/builders';
import { makeTraitRef, makePageRef, makeOrbitalWithUses } from '@almadar/core/builders';
import { mergeCallSiteConfigOverrides } from '../../../../../factory-runtime/apply-params-to-orb.js';

const BEHAVIOR_PATH = 'std/behaviors/ui-visual-novel-board';
const ALIAS = 'UiVisualNovelBoard';

/**
 * Closed set of event keys this trait recognises —
 * derived from the .orb's `stateMachine.events[]` block
 * (transition triggers + emit names). Use as the key type
 * when passing an `events:` rename map at the call site.
 */
export type StdUiVisualNovelBoardEventKey = 'ADVANCE' | 'CHOOSE' | 'INIT' | 'RESTART';

/**
 * Payload shape for the `CHOOSE` event.
 */
export interface StdUiVisualNovelBoardChoosePayload {
  nextId: string;
}

/**
 * Payload shape for the `ADVANCE` event.
 */
export interface StdUiVisualNovelBoardAdvancePayload {
  id?: string;
}

/**
 * Payload shape for the `RESTART` event.
 */
export interface StdUiVisualNovelBoardRestartPayload {
  id?: string;
}

/**
 * Typed call-site config block for this trait — every
 * field maps to a `config { ... }` entry in the source
 * .lolo. The agent fills these to specialise the trait
 * without modifying its state-machine topology.
 */
export interface StdUiVisualNovelBoardConfig {
  /** Default: `""` */
  className?: string;
  /** Default: `{"animations":["static"],"aspect":"16:9","category":"core","dimension":"2d","name":"core","role":"decoration","style":"iram","thumbnailUrl":"","url":"https://almadar-iram-assets.web.app/frames/seq-22-resonance/shot-01-start.png","variant":""}` */
  coreBg?: EntityRow;
  /** Default: `{"animations":["static"],"aspect":"16:9","category":"corridor","dimension":"2d","name":"corridor","role":"decoration","style":"iram","thumbnailUrl":"","url":"https://almadar-iram-assets.web.app/frames/seq-01-shift-7421/shot-01-start.png","variant":""}` */
  corridorBg?: EntityRow;
  error?: EntityRow;
  /** Default: `{"animations":["static"],"aspect":"16:9","category":"forge","dimension":"2d","name":"forge","role":"decoration","style":"iram","thumbnailUrl":"","url":"https://almadar-iram-assets.web.app/frames/seq-05-assembly-line/shot-01-start.png","variant":""}` */
  forgeBg?: EntityRow;
  /** Default: `false` */
  isLoading?: boolean;
  /** Default: `[{"backgroundKey":"corridor","choices":[{"label":"Approach the sentinel.","nextId":"meet"},{"label":"Turn back.","nextId":"retreat"}],"id":"start","portraitKey":"guide","speaker":"Narrator","text":"The corridor stretches into shadow. A lone sentinel blocks your path."},{"backgroundKey":"forge","choices":[{"label":"I seek the core.","nextId":"end"},{"label":"I am only passing through.","nextId":"retreat"}],"id":"meet","portraitKey":"rival","speaker":"Sentinel","text":"You carry the old marks. Speak your purpose, traveler."},{"backgroundKey":"corridor","choices":[{"label":"Begin again.","nextId":"start"}],"id":"retreat","portraitKey":"guide","speaker":"Narrator","text":"You withdraw into the dark. The path will wait for braver feet."},{"backgroundKey":"core","choices":[{"label":"Begin again.","nextId":"start"}],"id":"end","portraitKey":"rival","speaker":"Sentinel","text":"Then the way is open. Walk it well."}]` */
  nodes?: EntityRow[];
  /** Default: `1` */
  portraitScale?: number;
  /** Default: `{"animations":["static"],"aspect":"1:2","category":"guide","dimension":"2d","name":"guide","role":"npc","style":"iram","thumbnailUrl":"","url":"https://almadar-iram-assets.web.app/references/amir.png","variant":""}` */
  portraitUrl?: EntityRow;
  /** Default: `"start"` */
  startNodeId?: string;
  /** Default: `30` */
  typewriterSpeed?: number;
}

type _StdUiVisualNovelBoardEntityName = 'VisualNovelBoardItem';
type _StdUiVisualNovelBoardListenTraitName = 'VisualNovelBoardRender';

/**
 * Tunable params for the VisualNovelBoardOrbital orbital.
 *
 * Canonical entity: VisualNovelBoardItem — overridable via
 * `entityName`. The factory threads the effective name through every
 * trait's `linkedEntity` binding; the `.orb` compiler's inline phase
 * auto-rewrites every `@Entity.x`, `["ref",X]`, `["fetch",X,…]`,
 * `["persist",…,X,…]` and payload type string accordingly.
 *
 * Override surface (mirrors `.lolo`'s native overrides 1:1):
 *   fields         — extra entity fields (appended)
 *   pagePath       — first-page URL override
 *   entityName     — rename the canonical entity
 *   traitOverrides — per-imported-trait `config`, `linkedEntity`,
 *                    `events`, `name`, `emitsScope`, `listens`.
 *                    `effects` is NOT exposed — `.lolo` removed it
 *                    in Phase 9.5.H. Use `listens` via a sibling
 *                    trait to react to atom events.
 */
export interface StdUiVisualNovelBoardVisualNovelBoardOrbitalParams {
  /** Extra fields appended to the canonical entity. */
  fields?: EntityField[];
  /** URL path override for the orbital's first page. */
  pagePath?: string;
  /** Rename the canonical entity (PascalCase singular, ≤32 chars). */
  entityName?: string;
  /**
   * Per-imported-trait override surface keyed on each imported
   * trait's canonical `name`. Accepts every override `.lolo`
   * natively supports: `config`, `linkedEntity`, `events`,
   * `name`, `emitsScope`, `listens`. `effects` is excluded —
   * atom-owned (use `listens` via a sibling trait instead).
   */
  traitOverrides?: Partial<Record<
    'VisualNovelBoardRender',
    Pick<MakeTraitRefOpts, 'config' | 'linkedEntity' | 'events' | 'name' | 'emitsScope' | 'listens'>
  >>;
}

/** `'Alias.traits.TraitName'` literal union of every trait VisualNovelBoardOrbital's `uses[]` exports. */
type _StdUiVisualNovelBoardVisualNovelBoardOrbitalUsesRef = never;

/** Per-orbital factory: builds the VisualNovelBoardOrbital orbital with consumer params. */
export function stdUiVisualNovelBoardVisualNovelBoardOrbital(params: StdUiVisualNovelBoardVisualNovelBoardOrbitalParams = {}): OrbitalDefinition {
  const built = makeOrbitalWithUses({
    name: 'VisualNovelBoardOrbital',
    uses: [],
    entity: {
      name: 'VisualNovelBoardItem',
      persistence: 'runtime',
      fields: ((): EntityField[] => {
        const canonical: EntityField[] = [
          {
            'name': 'id',
            'required': true,
            'type': 'string',
          },
          {
            'items': {
              'properties': {
                'backgroundKey': {
                  'name': 'backgroundKey',
                  'required': false,
                  'type': 'string',
                },
                'choices': {
                  'items': {
                    'properties': {
                      'label': {
                        'name': 'label',
                        'required': true,
                        'type': 'string',
                      },
                      'nextId': {
                        'name': 'nextId',
                        'required': true,
                        'type': 'string',
                      },
                    },
                    'type': 'object',
                  },
                  'name': 'choices',
                  'required': false,
                  'type': 'array',
                },
                'id': {
                  'name': 'id',
                  'required': true,
                  'type': 'string',
                },
                'portraitKey': {
                  'name': 'portraitKey',
                  'required': false,
                  'type': 'string',
                },
                'speaker': {
                  'name': 'speaker',
                  'required': true,
                  'type': 'string',
                },
                'text': {
                  'name': 'text',
                  'required': true,
                  'type': 'string',
                },
              },
              'type': 'object',
            },
            'name': 'nodes',
            'type': 'array',
          },
          {
            'default': 'start',
            'name': 'currentNodeId',
            'type': 'string',
          },
          {
            'default': '',
            'name': 'currentSpeaker',
            'type': 'string',
          },
          {
            'default': '',
            'name': 'currentText',
            'type': 'string',
          },
          {
            'default': [],
            'items': {
              'properties': {
                'label': {
                  'name': 'label',
                  'required': true,
                  'type': 'string',
                },
                'nextId': {
                  'name': 'nextId',
                  'required': true,
                  'type': 'string',
                },
              },
              'type': 'object',
            },
            'name': 'currentChoices',
            'type': 'array',
          },
          {
            'default': 0,
            'name': 'revealedChars',
            'type': 'number',
          },
        ];
        const extras = params.fields ?? [];
        if (extras.length === 0) return canonical;
        const extraNames = new Set(extras.map((f) => f.name));
        return [...canonical.filter((f) => !extraNames.has(f.name)), ...extras];
      })(),
    } as Entity,
    traits: [
      {
        'category': 'interaction',
        'config': {
          'className': {
            'default': '',
            'description': 'className prop',
            'label': 'Class Name',
            'tier': 'presentation',
            'type': 'string',
          },
          'coreBg': {
            'default': {
              'animations': [
                'static',
              ],
              'aspect': '16:9',
              'category': 'core',
              'dimension': '2d',
              'name': 'core',
              'role': 'decoration',
              'style': 'iram',
              'thumbnailUrl': '',
              'url': 'https://almadar-iram-assets.web.app/frames/seq-22-resonance/shot-01-start.png',
              'variant': '',
            },
            'description': 'Ancient core scene background (dark teal).',
            'label': 'Core Background',
            'properties': {
              'animations': {
                'items': {
                  'type': 'string',
                },
                'name': 'animations',
                'required': false,
                'type': 'array',
              },
              'aspect': {
                'name': 'aspect',
                'required': false,
                'type': 'string',
              },
              'category': {
                'name': 'category',
                'required': false,
                'type': 'string',
              },
              'dimension': {
                'name': 'dimension',
                'required': false,
                'type': 'string',
              },
              'name': {
                'name': 'name',
                'required': false,
                'type': 'string',
              },
              'role': {
                'name': 'role',
                'required': false,
                'type': 'string',
              },
              'style': {
                'name': 'style',
                'required': false,
                'type': 'string',
              },
              'thumbnailUrl': {
                'name': 'thumbnailUrl',
                'required': false,
                'type': 'string',
              },
              'url': {
                'name': 'url',
                'required': false,
                'type': 'string',
              },
              'variant': {
                'name': 'variant',
                'required': false,
                'type': 'string',
              },
            },
            'tier': 'presentation',
            'type': 'Asset',
          },
          'corridorBg': {
            'default': {
              'animations': [
                'static',
              ],
              'aspect': '16:9',
              'category': 'corridor',
              'dimension': '2d',
              'name': 'corridor',
              'role': 'decoration',
              'style': 'iram',
              'thumbnailUrl': '',
              'url': 'https://almadar-iram-assets.web.app/frames/seq-01-shift-7421/shot-01-start.png',
              'variant': '',
            },
            'description': 'Stone corridor scene background (dark blue-grey).',
            'label': 'Corridor Background',
            'properties': {
              'animations': {
                'items': {
                  'type': 'string',
                },
                'name': 'animations',
                'required': false,
                'type': 'array',
              },
              'aspect': {
                'name': 'aspect',
                'required': false,
                'type': 'string',
              },
              'category': {
                'name': 'category',
                'required': false,
                'type': 'string',
              },
              'dimension': {
                'name': 'dimension',
                'required': false,
                'type': 'string',
              },
              'name': {
                'name': 'name',
                'required': false,
                'type': 'string',
              },
              'role': {
                'name': 'role',
                'required': false,
                'type': 'string',
              },
              'style': {
                'name': 'style',
                'required': false,
                'type': 'string',
              },
              'thumbnailUrl': {
                'name': 'thumbnailUrl',
                'required': false,
                'type': 'string',
              },
              'url': {
                'name': 'url',
                'required': false,
                'type': 'string',
              },
              'variant': {
                'name': 'variant',
                'required': false,
                'type': 'string',
              },
            },
            'tier': 'presentation',
            'type': 'Asset',
          },
          'error': {
            'description': 'Error state (UiError)',
            'label': 'Error',
            'properties': {
              'code': {
                'name': 'code',
                'required': false,
                'type': 'string',
              },
              'message': {
                'name': 'message',
                'required': true,
                'type': 'string',
              },
              'name': {
                'name': 'name',
                'required': false,
                'type': 'string',
              },
              'stack': {
                'name': 'stack',
                'required': false,
                'type': 'string',
              },
            },
            'tier': 'presentation',
            'type': 'VisualNovelBoardError',
          },
          'forgeBg': {
            'default': {
              'animations': [
                'static',
              ],
              'aspect': '16:9',
              'category': 'forge',
              'dimension': '2d',
              'name': 'forge',
              'role': 'decoration',
              'style': 'iram',
              'thumbnailUrl': '',
              'url': 'https://almadar-iram-assets.web.app/frames/seq-05-assembly-line/shot-01-start.png',
              'variant': '',
            },
            'description': 'Forge room scene background (dark orange-red).',
            'label': 'Forge Background',
            'properties': {
              'animations': {
                'items': {
                  'type': 'string',
                },
                'name': 'animations',
                'required': false,
                'type': 'array',
              },
              'aspect': {
                'name': 'aspect',
                'required': false,
                'type': 'string',
              },
              'category': {
                'name': 'category',
                'required': false,
                'type': 'string',
              },
              'dimension': {
                'name': 'dimension',
                'required': false,
                'type': 'string',
              },
              'name': {
                'name': 'name',
                'required': false,
                'type': 'string',
              },
              'role': {
                'name': 'role',
                'required': false,
                'type': 'string',
              },
              'style': {
                'name': 'style',
                'required': false,
                'type': 'string',
              },
              'thumbnailUrl': {
                'name': 'thumbnailUrl',
                'required': false,
                'type': 'string',
              },
              'url': {
                'name': 'url',
                'required': false,
                'type': 'string',
              },
              'variant': {
                'name': 'variant',
                'required': false,
                'type': 'string',
              },
            },
            'tier': 'presentation',
            'type': 'Asset',
          },
          'isLoading': {
            'default': false,
            'description': 'Loading state indicator',
            'label': 'Is Loading',
            'tier': 'presentation',
            'type': 'boolean',
          },
          'nodes': {
            'default': [
              {
                'backgroundKey': 'corridor',
                'choices': [
                  {
                    'label': 'Approach the sentinel.',
                    'nextId': 'meet',
                  },
                  {
                    'label': 'Turn back.',
                    'nextId': 'retreat',
                  },
                ],
                'id': 'start',
                'portraitKey': 'guide',
                'speaker': 'Narrator',
                'text': 'The corridor stretches into shadow. A lone sentinel blocks your path.',
              },
              {
                'backgroundKey': 'forge',
                'choices': [
                  {
                    'label': 'I seek the core.',
                    'nextId': 'end',
                  },
                  {
                    'label': 'I am only passing through.',
                    'nextId': 'retreat',
                  },
                ],
                'id': 'meet',
                'portraitKey': 'rival',
                'speaker': 'Sentinel',
                'text': 'You carry the old marks. Speak your purpose, traveler.',
              },
              {
                'backgroundKey': 'corridor',
                'choices': [
                  {
                    'label': 'Begin again.',
                    'nextId': 'start',
                  },
                ],
                'id': 'retreat',
                'portraitKey': 'guide',
                'speaker': 'Narrator',
                'text': 'You withdraw into the dark. The path will wait for braver feet.',
              },
              {
                'backgroundKey': 'core',
                'choices': [
                  {
                    'label': 'Begin again.',
                    'nextId': 'start',
                  },
                ],
                'id': 'end',
                'portraitKey': 'rival',
                'speaker': 'Sentinel',
                'text': 'Then the way is open. Walk it well.',
              },
            ],
            'description': 'Dialogue graph: each node has speaker text, scene/portrait keys, and branching choices.',
            'items': {
              'properties': {
                'backgroundKey': {
                  'name': 'backgroundKey',
                  'required': false,
                  'type': 'string',
                },
                'choices': {
                  'items': {
                    'properties': {
                      'label': {
                        'name': 'label',
                        'required': true,
                        'type': 'string',
                      },
                      'nextId': {
                        'name': 'nextId',
                        'required': true,
                        'type': 'string',
                      },
                    },
                    'type': 'object',
                  },
                  'name': 'choices',
                  'required': false,
                  'type': 'array',
                },
                'id': {
                  'name': 'id',
                  'required': true,
                  'type': 'string',
                },
                'portraitKey': {
                  'name': 'portraitKey',
                  'required': false,
                  'type': 'string',
                },
                'speaker': {
                  'name': 'speaker',
                  'required': true,
                  'type': 'string',
                },
                'text': {
                  'name': 'text',
                  'required': true,
                  'type': 'string',
                },
              },
              'type': 'object',
            },
            'label': 'Nodes',
            'tier': 'presentation',
            'type': '[VisualNovelBoardNodesItem]',
          },
          'portraitScale': {
            'default': 1,
            'description': 'Character portrait draw-size multiplier',
            'label': 'Portrait Scale',
            'tier': 'presentation',
            'type': 'number',
          },
          'portraitUrl': {
            'default': {
              'animations': [
                'static',
              ],
              'aspect': '1:2',
              'category': 'guide',
              'dimension': '2d',
              'name': 'guide',
              'role': 'npc',
              'style': 'iram',
              'thumbnailUrl': '',
              'url': 'https://almadar-iram-assets.web.app/references/amir.png',
              'variant': '',
            },
            'description': 'Large character portrait rendered standing over the scene.',
            'label': 'Portrait Url',
            'properties': {
              'animations': {
                'items': {
                  'type': 'string',
                },
                'name': 'animations',
                'required': false,
                'type': 'array',
              },
              'aspect': {
                'name': 'aspect',
                'required': false,
                'type': 'string',
              },
              'category': {
                'name': 'category',
                'required': false,
                'type': 'string',
              },
              'dimension': {
                'name': 'dimension',
                'required': false,
                'type': 'string',
              },
              'name': {
                'name': 'name',
                'required': false,
                'type': 'string',
              },
              'role': {
                'name': 'role',
                'required': false,
                'type': 'string',
              },
              'style': {
                'name': 'style',
                'required': false,
                'type': 'string',
              },
              'thumbnailUrl': {
                'name': 'thumbnailUrl',
                'required': false,
                'type': 'string',
              },
              'url': {
                'name': 'url',
                'required': false,
                'type': 'string',
              },
              'variant': {
                'name': 'variant',
                'required': false,
                'type': 'string',
              },
            },
            'tier': 'presentation',
            'type': 'Asset',
          },
          'startNodeId': {
            'default': 'start',
            'description': 'Id of the dialogue node shown first / on restart',
            'label': 'Start Node Id',
            'tier': 'presentation',
            'type': 'string',
          },
          'typewriterSpeed': {
            'default': 30,
            'description': 'Milliseconds per character of dialogue text reveal (0 = instant)',
            'label': 'Typewriter Speed',
            'tier': 'presentation',
            'type': 'number',
          },
        },
        'emits': [
          {
            'description': 'Emits UI:{chooseEvent} with {nextId} when the player selects a branching choice',
            'event': 'CHOOSE',
            'payloadSchema': [
              {
                'name': 'nextId',
                'required': true,
                'type': 'string',
              },
            ],
            'scope': 'external',
            'tier': 'domain',
          },
          {
            'description': 'Emits UI:{advanceEvent} with {} to advance to the next node',
            'event': 'ADVANCE',
            'payloadSchema': [
              {
                'name': 'id',
                'type': 'string',
              },
            ],
            'scope': 'external',
            'tier': 'domain',
          },
          {
            'description': 'Emits UI:{restartEvent} with {} to reset the scene to the start node',
            'event': 'RESTART',
            'payloadSchema': [
              {
                'name': 'id',
                'type': 'string',
              },
            ],
            'scope': 'external',
            'tier': 'domain',
          },
        ],
        'entityContract': {
          'provides': [
            'currentChoices',
            'currentNodeId',
            'currentSpeaker',
            'currentText',
            'nodes',
            'revealedChars',
          ],
          'requires': [],
        },
        'entityRebindable': true,
        'linkedEntity': 'VisualNovelBoardItem',
        'name': 'VisualNovelBoardRender',
        'scope': 'instance',
        'stateMachine': {
          'events': [
            {
              'key': 'INIT',
              'name': 'Initialize',
            },
            {
              'description': 'Emits UI:{chooseEvent} with {nextId} when the player selects a branching choice',
              'key': 'CHOOSE',
              'name': 'Choose',
              'payloadSchema': [
                {
                  'name': 'nextId',
                  'required': true,
                  'type': 'string',
                },
              ],
              'tier': 'domain',
            },
            {
              'description': 'Emits UI:{advanceEvent} with {} to advance to the next node',
              'key': 'ADVANCE',
              'name': 'Advance',
              'payloadSchema': [
                {
                  'name': 'id',
                  'type': 'string',
                },
              ],
              'tier': 'domain',
            },
            {
              'description': 'Emits UI:{restartEvent} with {} to reset the scene to the start node',
              'key': 'RESTART',
              'name': 'Restart',
              'payloadSchema': [
                {
                  'name': 'id',
                  'type': 'string',
                },
              ],
              'tier': 'domain',
            },
          ],
          'states': [
            {
              'isInitial': true,
              'name': 'playing',
            },
          ],
          'transitions': [
            {
              'effects': [
                [
                  'set',
                  '@entity.nodes',
                  '@config.nodes',
                ],
                [
                  'set',
                  '@entity.currentNodeId',
                  '@config.startNodeId',
                ],
                [
                  'set',
                  '@entity.currentSpeaker',
                  [
                    'object/get',
                    [
                      'array/first',
                      [
                        'array/filter',
                        '@entity.nodes',
                        [
                          'fn',
                          'n',
                          [
                            '==',
                            '@n.id',
                            '@entity.currentNodeId',
                          ],
                        ],
                      ],
                    ],
                    'speaker',
                  ],
                ],
                [
                  'set',
                  '@entity.currentText',
                  [
                    'object/get',
                    [
                      'array/first',
                      [
                        'array/filter',
                        '@entity.nodes',
                        [
                          'fn',
                          'n',
                          [
                            '==',
                            '@n.id',
                            '@entity.currentNodeId',
                          ],
                        ],
                      ],
                    ],
                    'text',
                  ],
                ],
                [
                  'set',
                  '@entity.currentChoices',
                  [
                    'object/get',
                    [
                      'array/first',
                      [
                        'array/filter',
                        '@entity.nodes',
                        [
                          'fn',
                          'n',
                          [
                            '==',
                            '@n.id',
                            '@entity.currentNodeId',
                          ],
                        ],
                      ],
                    ],
                    'choices',
                  ],
                ],
                [
                  'set',
                  '@entity.revealedChars',
                  0,
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'backgroundAsset': [
                      'let',
                      [
                        [
                          'bg',
                          [
                            'object/get',
                            [
                              'array/first',
                              [
                                'array/filter',
                                '@entity.nodes',
                                [
                                  'fn',
                                  'n',
                                  [
                                    '==',
                                    '@n.id',
                                    '@entity.currentNodeId',
                                  ],
                                ],
                              ],
                            ],
                            'backgroundKey',
                          ],
                        ],
                      ],
                      [
                        'if',
                        [
                          '==',
                          '@bg',
                          'forge',
                        ],
                        '@config.forgeBg',
                        [
                          'if',
                          [
                            '==',
                            '@bg',
                            'core',
                          ],
                          '@config.coreBg',
                          '@config.corridorBg',
                        ],
                      ],
                    ],
                    'children': [
                      {
                        'portrait': '@config.portraitUrl',
                        'revealedChars': '@entity.revealedChars',
                        'speaker': '@entity.currentSpeaker',
                        'text': '@entity.currentText',
                        'type': 'dialogue-bubble',
                      },
                      {
                        'entity': '@entity.currentChoices',
                        'fields': [],
                        'gap': 'sm',
                        'renderItem': [
                          'fn',
                          'c',
                          {
                            'action': 'CHOOSE',
                            'payload': {
                              'nextId': [
                                'object/get',
                                '@c',
                                'nextId',
                              ],
                            },
                            'text': [
                              'object/get',
                              '@c',
                              'label',
                            ],
                            'type': 'choice-button',
                          },
                        ],
                        'type': 'data-list',
                      },
                    ],
                    'type': 'game-shell',
                  },
                ],
              ],
              'event': 'INIT',
              'from': 'playing',
              'to': 'playing',
            },
            {
              'effects': [
                [
                  'set',
                  '@entity.currentNodeId',
                  '@payload.nextId',
                ],
                [
                  'set',
                  '@entity.currentSpeaker',
                  [
                    'object/get',
                    [
                      'array/first',
                      [
                        'array/filter',
                        '@entity.nodes',
                        [
                          'fn',
                          'n',
                          [
                            '==',
                            '@n.id',
                            '@entity.currentNodeId',
                          ],
                        ],
                      ],
                    ],
                    'speaker',
                  ],
                ],
                [
                  'set',
                  '@entity.currentText',
                  [
                    'object/get',
                    [
                      'array/first',
                      [
                        'array/filter',
                        '@entity.nodes',
                        [
                          'fn',
                          'n',
                          [
                            '==',
                            '@n.id',
                            '@entity.currentNodeId',
                          ],
                        ],
                      ],
                    ],
                    'text',
                  ],
                ],
                [
                  'set',
                  '@entity.currentChoices',
                  [
                    'object/get',
                    [
                      'array/first',
                      [
                        'array/filter',
                        '@entity.nodes',
                        [
                          'fn',
                          'n',
                          [
                            '==',
                            '@n.id',
                            '@entity.currentNodeId',
                          ],
                        ],
                      ],
                    ],
                    'choices',
                  ],
                ],
                [
                  'set',
                  '@entity.revealedChars',
                  0,
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'backgroundAsset': [
                      'let',
                      [
                        [
                          'bg',
                          [
                            'object/get',
                            [
                              'array/first',
                              [
                                'array/filter',
                                '@entity.nodes',
                                [
                                  'fn',
                                  'n',
                                  [
                                    '==',
                                    '@n.id',
                                    '@entity.currentNodeId',
                                  ],
                                ],
                              ],
                            ],
                            'backgroundKey',
                          ],
                        ],
                      ],
                      [
                        'if',
                        [
                          '==',
                          '@bg',
                          'forge',
                        ],
                        '@config.forgeBg',
                        [
                          'if',
                          [
                            '==',
                            '@bg',
                            'core',
                          ],
                          '@config.coreBg',
                          '@config.corridorBg',
                        ],
                      ],
                    ],
                    'children': [
                      {
                        'portrait': '@config.portraitUrl',
                        'revealedChars': '@entity.revealedChars',
                        'speaker': '@entity.currentSpeaker',
                        'text': '@entity.currentText',
                        'type': 'dialogue-bubble',
                      },
                      {
                        'entity': '@entity.currentChoices',
                        'fields': [],
                        'gap': 'sm',
                        'renderItem': [
                          'fn',
                          'c',
                          {
                            'action': 'CHOOSE',
                            'payload': {
                              'nextId': [
                                'object/get',
                                '@c',
                                'nextId',
                              ],
                            },
                            'text': [
                              'object/get',
                              '@c',
                              'label',
                            ],
                            'type': 'choice-button',
                          },
                        ],
                        'type': 'data-list',
                      },
                    ],
                    'type': 'game-shell',
                  },
                ],
              ],
              'event': 'CHOOSE',
              'from': 'playing',
              'to': 'playing',
            },
            {
              'effects': [
                [
                  'set',
                  '@entity.revealedChars',
                  [
                    'str/len',
                    '@entity.currentText',
                  ],
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'backgroundAsset': [
                      'let',
                      [
                        [
                          'bg',
                          [
                            'object/get',
                            [
                              'array/first',
                              [
                                'array/filter',
                                '@entity.nodes',
                                [
                                  'fn',
                                  'n',
                                  [
                                    '==',
                                    '@n.id',
                                    '@entity.currentNodeId',
                                  ],
                                ],
                              ],
                            ],
                            'backgroundKey',
                          ],
                        ],
                      ],
                      [
                        'if',
                        [
                          '==',
                          '@bg',
                          'forge',
                        ],
                        '@config.forgeBg',
                        [
                          'if',
                          [
                            '==',
                            '@bg',
                            'core',
                          ],
                          '@config.coreBg',
                          '@config.corridorBg',
                        ],
                      ],
                    ],
                    'children': [
                      {
                        'portrait': '@config.portraitUrl',
                        'revealedChars': '@entity.revealedChars',
                        'speaker': '@entity.currentSpeaker',
                        'text': '@entity.currentText',
                        'type': 'dialogue-bubble',
                      },
                      {
                        'entity': '@entity.currentChoices',
                        'fields': [],
                        'gap': 'sm',
                        'renderItem': [
                          'fn',
                          'c',
                          {
                            'action': 'CHOOSE',
                            'payload': {
                              'nextId': [
                                'object/get',
                                '@c',
                                'nextId',
                              ],
                            },
                            'text': [
                              'object/get',
                              '@c',
                              'label',
                            ],
                            'type': 'choice-button',
                          },
                        ],
                        'type': 'data-list',
                      },
                    ],
                    'type': 'game-shell',
                  },
                ],
              ],
              'event': 'ADVANCE',
              'from': 'playing',
              'to': 'playing',
            },
            {
              'effects': [
                [
                  'set',
                  '@entity.currentNodeId',
                  '@config.startNodeId',
                ],
                [
                  'set',
                  '@entity.currentSpeaker',
                  [
                    'object/get',
                    [
                      'array/first',
                      [
                        'array/filter',
                        '@entity.nodes',
                        [
                          'fn',
                          'n',
                          [
                            '==',
                            '@n.id',
                            '@entity.currentNodeId',
                          ],
                        ],
                      ],
                    ],
                    'speaker',
                  ],
                ],
                [
                  'set',
                  '@entity.currentText',
                  [
                    'object/get',
                    [
                      'array/first',
                      [
                        'array/filter',
                        '@entity.nodes',
                        [
                          'fn',
                          'n',
                          [
                            '==',
                            '@n.id',
                            '@entity.currentNodeId',
                          ],
                        ],
                      ],
                    ],
                    'text',
                  ],
                ],
                [
                  'set',
                  '@entity.currentChoices',
                  [
                    'object/get',
                    [
                      'array/first',
                      [
                        'array/filter',
                        '@entity.nodes',
                        [
                          'fn',
                          'n',
                          [
                            '==',
                            '@n.id',
                            '@entity.currentNodeId',
                          ],
                        ],
                      ],
                    ],
                    'choices',
                  ],
                ],
                [
                  'set',
                  '@entity.revealedChars',
                  0,
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'backgroundAsset': [
                      'let',
                      [
                        [
                          'bg',
                          [
                            'object/get',
                            [
                              'array/first',
                              [
                                'array/filter',
                                '@entity.nodes',
                                [
                                  'fn',
                                  'n',
                                  [
                                    '==',
                                    '@n.id',
                                    '@entity.currentNodeId',
                                  ],
                                ],
                              ],
                            ],
                            'backgroundKey',
                          ],
                        ],
                      ],
                      [
                        'if',
                        [
                          '==',
                          '@bg',
                          'forge',
                        ],
                        '@config.forgeBg',
                        [
                          'if',
                          [
                            '==',
                            '@bg',
                            'core',
                          ],
                          '@config.coreBg',
                          '@config.corridorBg',
                        ],
                      ],
                    ],
                    'children': [
                      {
                        'portrait': '@config.portraitUrl',
                        'revealedChars': '@entity.revealedChars',
                        'speaker': '@entity.currentSpeaker',
                        'text': '@entity.currentText',
                        'type': 'dialogue-bubble',
                      },
                      {
                        'entity': '@entity.currentChoices',
                        'fields': [],
                        'gap': 'sm',
                        'renderItem': [
                          'fn',
                          'c',
                          {
                            'action': 'CHOOSE',
                            'payload': {
                              'nextId': [
                                'object/get',
                                '@c',
                                'nextId',
                              ],
                            },
                            'text': [
                              'object/get',
                              '@c',
                              'label',
                            ],
                            'type': 'choice-button',
                          },
                        ],
                        'type': 'data-list',
                      },
                    ],
                    'type': 'game-shell',
                  },
                ],
              ],
              'event': 'RESTART',
              'from': 'playing',
              'to': 'playing',
            },
          ],
        },
        'ticks': [
          {
            'effects': [
              [
                'set',
                '@entity.revealedChars',
                [
                  '+',
                  '@entity.revealedChars',
                  1,
                ],
              ],
              [
                'render-ui',
                'main',
                {
                  'backgroundAsset': [
                    'let',
                    [
                      [
                        'bg',
                        [
                          'object/get',
                          [
                            'array/first',
                            [
                              'array/filter',
                              '@entity.nodes',
                              [
                                'fn',
                                'n',
                                [
                                  '==',
                                  '@n.id',
                                  '@entity.currentNodeId',
                                ],
                              ],
                            ],
                          ],
                          'backgroundKey',
                        ],
                      ],
                    ],
                    [
                      'if',
                      [
                        '==',
                        '@bg',
                        'forge',
                      ],
                      '@config.forgeBg',
                      [
                        'if',
                        [
                          '==',
                          '@bg',
                          'core',
                        ],
                        '@config.coreBg',
                        '@config.corridorBg',
                      ],
                    ],
                  ],
                  'children': [
                    {
                      'portrait': '@config.portraitUrl',
                      'revealedChars': '@entity.revealedChars',
                      'speaker': '@entity.currentSpeaker',
                      'text': '@entity.currentText',
                      'type': 'dialogue-bubble',
                    },
                    {
                      'entity': '@entity.currentChoices',
                      'fields': [],
                      'gap': 'sm',
                      'renderItem': [
                        'fn',
                        'c',
                        {
                          'action': 'CHOOSE',
                          'payload': {
                            'nextId': [
                              'object/get',
                              '@c',
                              'nextId',
                            ],
                          },
                          'text': [
                            'object/get',
                            '@c',
                            'label',
                          ],
                          'type': 'choice-button',
                        },
                      ],
                      'type': 'data-list',
                    },
                  ],
                  'type': 'game-shell',
                },
              ],
            ],
            'guard': [
              '<',
              '@entity.revealedChars',
              [
                'str/len',
                '@entity.currentText',
              ],
            ],
            'interval': 30,
            'name': 'typewriterTick',
          },
        ],
      } satisfies Trait,
    ],
    pages: [
      {
        'name': 'VisualNovelBoardPage',
        'path': '/visual-novel-board',
        'traits': [
          {
            'ref': 'VisualNovelBoardRender',
          },
        ],
      } satisfies Page,
    ],
  });
  type _OrbTrait = OrbitalDefinition["traits"][number];
  type _OrbPage = NonNullable<OrbitalDefinition["pages"]>[number];
  type _RefOverride = Pick<MakeTraitRefOpts, "config" | "linkedEntity" | "events" | "name" | "emitsScope" | "listens">;
  if (built.traits && params.traitOverrides !== undefined) {
    built.traits = (built.traits as _OrbTrait[]).map((t): _OrbTrait => {
      if (!t || typeof t !== "object") return t;
      const tr = t as TraitReference & { name?: string };
      // Match by name so inline traits (no `ref`) and
      // reference traits (with `ref`) both pick up the
      // override surface keyed on the trait's `name`.
      if (typeof tr.name !== "string") return t;
      const overrides = params.traitOverrides as Record<string, _RefOverride | undefined> | undefined;
      const override = overrides?.[tr.name];
      if (!override) return t;
      const merged: TraitReference = { ...tr };
      if (override.config !== undefined) {
        merged.config = mergeCallSiteConfigOverrides(tr.config ?? {}, override.config);
      }
      if (override.linkedEntity !== undefined) merged.linkedEntity = override.linkedEntity;
      if (override.events !== undefined) merged.events = { ...(tr.events ?? {}), ...override.events };
      if (override.emitsScope !== undefined) merged.emitsScope = override.emitsScope;
      if (override.listens !== undefined) merged.listens = override.listens;
      return merged;
    });
  }
  if (built.pages && params.pagePath !== undefined) {
    built.pages = (built.pages as _OrbPage[]).map((p, idx) => {
      if (!p || typeof p !== "object") return p;
      if (idx !== 0) return p;
      const out = { ...p } as _OrbPage & { path?: string };
      out.path = params.pagePath;
      return out;
    });
  }
  return built;
}

/** Manifest — describes the params surface of stdUiVisualNovelBoardVisualNovelBoardOrbital. */
export const StdUiVisualNovelBoardVisualNovelBoardOrbitalManifest = {
  organism: 'ui-visual-novel-board',
  orbitalName: 'VisualNovelBoardOrbital',
  paramFields: [
    { name: 'fields', type: 'EntityField[]', description: 'Extra fields appended to the canonical entity.' },
    { name: 'pagePath', type: 'string', description: 'URL override for the orbital first page.' },
    { name: 'entityName', type: 'string', description: 'Rename the canonical entity. PascalCase singular, ≤32 chars. Threads through every trait\'s linkedEntity binding; compiler rewrites @Entity.x refs.' },
    { name: 'traitOverrides', type: "Partial<Record<TraitName, { config?, linkedEntity?, events?, name?, emitsScope?, listens? }>>", description: 'Per-imported-trait overrides — mirrors .lolo\'s native trait-composition surface 1:1. effects is excluded (atom-owned; use listens via a sibling trait).' },
  ] as const,
  traitNames: [
  ] as const,
  inlineTraitNames: [
    'VisualNovelBoardRender',
  ] as const,
};

/** Typed guard — runtime validates StdUiVisualNovelBoardVisualNovelBoardOrbitalParams keys. */
export function isStdUiVisualNovelBoardVisualNovelBoardOrbitalParams(p: object): p is StdUiVisualNovelBoardVisualNovelBoardOrbitalParams {
  type _OverrideRecord = NonNullable<StdUiVisualNovelBoardVisualNovelBoardOrbitalParams['traitOverrides']>;
  const obj = p as { traitOverrides?: _OverrideRecord };
  if (obj.traitOverrides !== undefined) {
    if (typeof obj.traitOverrides !== "object" || obj.traitOverrides === null) return false;
    const allowed: readonly string[] = [
      ...StdUiVisualNovelBoardVisualNovelBoardOrbitalManifest.traitNames,
      ...StdUiVisualNovelBoardVisualNovelBoardOrbitalManifest.inlineTraitNames,
    ];
    for (const k of Object.keys(obj.traitOverrides)) {
      if (!allowed.includes(k)) return false;
    }
  }
  return true;
}

/**
 * Bundled params for ui-visual-novel-board — one optional entry per orbital.
 * Each entry maps to its per-orbital factory above.
 */
export interface StdUiVisualNovelBoardParams {
  VisualNovelBoard?: StdUiVisualNovelBoardVisualNovelBoardOrbitalParams;
}

/** Whole-organism descriptor (1 orbitals). Composes per-orbital factories. */
export function stdUiVisualNovelBoard(params: StdUiVisualNovelBoardParams = {}): OrbitalDefinition[] {
  return [
    stdUiVisualNovelBoardVisualNovelBoardOrbital(params.VisualNovelBoard ?? {}),
  ];
}
