/**
 * Factory-runtime — typed shapes.
 *
 * The factory runtime is the data-driven equivalent of the per-behavior TS
 * factories generated by `scripts/regenerate-std-ts.mjs`. The script bakes
 * the same overlay logic into each emitted factory; the runtime form lifts it
 * out so team-published behaviors (Firestore-stored, not code-published) can
 * flow through the identical code path.
 *
 * Reference: `docs/Almadar_Studio_SDK.md` §7.4.
 *
 * @packageDocumentation
 */

import type { EntityField, EntityPersistence } from '@almadar/core';
import type { MakeTraitRefOpts } from '@almadar/core/builders';

/**
 * The override surface for a single imported trait. Mirrors `.lolo`'s native
 * trait-composition surface 1:1 (see SDK doc §7.4 + the generated
 * `traitOverrides` types in each std factory). `effects` is intentionally
 * NOT exposed — that's atom-owned (use `listens` via a sibling trait to
 * react to atom events).
 */
export type OrbitalTraitOverride = Pick<
  MakeTraitRefOpts,
  'config' | 'linkedEntity' | 'events' | 'name' | 'emitsScope' | 'listens'
>;

/**
 * Strongly-typed params accepted by `applyParamsToOrb`. Same shape as every
 * generated per-orbital `*Params` interface (the codegen narrows
 * `traitOverrides`'s key type to that orbital's `traitNames`; the runtime
 * form keeps it open and validates the keys against the manifest at call
 * time).
 */
export interface OrbitalFactoryParams {
  /** Extra fields appended to the canonical entity (caller wins on name collision). */
  readonly fields?: readonly EntityField[];
  /** URL path override for the orbital's first page. */
  readonly pagePath?: string;
  /** Override the canonical entity persistence mode. */
  readonly persistence?: EntityPersistence;
  /** Rename the canonical entity (PascalCase singular, ≤32 chars). */
  readonly entityName?: string;
  /** Override the derived collection key (defaults to plural-of-entityName). */
  readonly collection?: string;
  /** Per-imported-trait overrides, keyed on the trait's canonical `name`. */
  readonly traitOverrides?: Readonly<Record<string, OrbitalTraitOverride | undefined>>;
}

/**
 * Discriminated failure shape for params validation against a manifest. Each
 * variant carries the smallest information needed for an actionable error
 * message — never a raw thrown `Error`.
 */
export type ParamValidationError =
  | { readonly kind: 'unknown-key'; readonly key: string }
  | {
      readonly kind: 'unknown-trait-override';
      readonly trait: string;
      readonly allowed: readonly string[];
    }
  | { readonly kind: 'not-object'; readonly received: string }
  | { readonly kind: 'trait-overrides-not-object'; readonly received: string };

/** Discriminated result type for validation. Caller never widens. */
export type ParamValidationResult =
  | { readonly ok: true; readonly params: OrbitalFactoryParams }
  | { readonly ok: false; readonly error: ParamValidationError };
