/**
 * std-notification-preferences — std-notification-preferences — per-person notification preference store plus a consultable gate. Owns NotificationPreference rows (one per person + event key: channel override in_app/email/push/slack/sms/webhook, mode instant/digest/off, quiet-hours window 'HH:MM-HH:MM' such as 22:00-07:00). The PreferencesManage trait is standard CRUD over the store (list / create / update / delete, persisted, success/failure cascade arms): a data-grid browse plus ModalRecordModal create/edit forms whose SAVE carries the full row payload (std-list daisy-chain idiom). The PreferenceGate trait is the consult half other notify traits call: emit CHECK_PREFERENCE { personId, eventKey } and the gate fetches the matching row (a row whose eventKey is blank applies to every event) and answers PREFERENCE_RESOLVED { personId, eventKey, channel, mode, suppressed } — suppressed is true only when the row's quietHours window covers the current hour; mode 'digest' rides on the verdict for the caller to defer. Default policy: no matching row — or a failed lookup — resolves fail-open to { channel: in_app, mode: instant, suppressed: false }; the absence of a preference never silences a notification.
 *
 * Autogenerated by almadar-sync std-ts from
 * packages/almadar-std/behaviors/registry/atoms/std-notification-preferences.orb.
 *
 * This is a thin descriptor layer over the canonical .orb. The exported
 * functions return TraitReference / PageRefObject / OrbitalDefinition
 * payloads that reference the sibling .orb via `uses:` + `ref:`. The
 * compiler's inline phase materialises the real trait at build time.
 *
 * Do not hand-edit — regenerate via
 *   npx almadar-sync std-ts --only=std-notification-preferences
 *
 * @level atom
 * @packageDocumentation
 */

import type { TraitReference, PageRefObject, OrbitalDefinition, Entity, EntityRef, EntityField, EntityPersistence, TraitConfig, TraitFieldRef, EntityRow, SExpr, TraitEventListener, Trait, StateMachine, Page, PatternValue } from '@almadar/core/types';
import type { MakeTraitRefOpts } from '@almadar/core/builders';
import { makeTraitRef, makePageRef, makeOrbitalWithUses } from '@almadar/core/builders';
import { mergeCallSiteConfigOverrides } from '../../../../factory-runtime/apply-params-to-orb.js';

const BEHAVIOR_PATH = 'std/behaviors/std-notification-preferences';
const ALIAS = 'NotificationPreferences';

/**
 * Closed set of event keys this trait recognises —
 * derived from the .orb's `stateMachine.events[]` block
 * (transition triggers + emit names). Use as the key type
 * when passing an `events:` rename map at the call site.
 */
export type StdNotificationPreferencesEventKey = 'CREATE' | 'DELETE' | 'DO_CREATE' | 'DO_UPDATE' | 'EDIT' | 'INIT' | 'PreferenceDeleted' | 'PreferenceSaveFailed' | 'PreferenceSaved' | 'PreferencesLoadFailed' | 'PreferencesLoaded' | 'RETRY';

/**
 * Closed set of event keys this trait listens for —
 * derived from the .orb's `listens[]` block.
 */
export type StdNotificationPreferencesListenKey = 'PREFERENCE_CREATED' | 'PREFERENCE_UPDATED';

/**
 * Payload shape for the `EDIT` event.
 */
export interface StdNotificationPreferencesEditPayload {
  id: string;
  row?: EntityRow;
}

/**
 * Payload shape for the `DELETE` event.
 */
export interface StdNotificationPreferencesDeletePayload {
  id: string;
  row?: EntityRow;
}

/**
 * Payload shape for the `PreferencesLoaded` event.
 */
export interface StdNotificationPreferencesPreferencesLoadedPayload {
  data?: EntityRow[];
}

/**
 * Payload shape for the `PreferencesLoadFailed` event.
 */
export interface StdNotificationPreferencesPreferencesLoadFailedPayload {
  error?: string;
  code?: string;
}

/**
 * Payload shape for the `PreferenceSaved` event.
 */
export interface StdNotificationPreferencesPreferenceSavedPayload {
  id: string;
}

/**
 * Payload shape for the `PreferenceSaveFailed` event.
 */
export interface StdNotificationPreferencesPreferenceSaveFailedPayload {
  error?: string;
  code?: string;
}

/**
 * Payload shape for the `PreferenceDeleted` event.
 */
export interface StdNotificationPreferencesPreferenceDeletedPayload {
  id: string;
}

/**
 * Typed call-site config block for this trait — every
 * field maps to a `config { ... }` entry in the source
 * .lolo. The agent fills these to specialise the trait
 * without modifying its state-machine topology.
 */
export interface StdNotificationPreferencesConfig {
  /** Default: `"dense"` */
  tableLook?: 'dense' | 'spacious' | 'striped' | 'borderless' | 'card-rows';
  /** Default: `"Notification preferences"` */
  title?: string;
}

/**
 * Params for the std-notification-preferences descriptor helpers.
 *
 * `entityName` binds every trait/page reference's `linkedEntity`.
 * The optional override fields mirror TraitReference / PageRefObject
 * fields and are forwarded to `makeTraitRef` / `makePageRef`.
 */
export interface StdNotificationPreferencesParams {
  entityName: string;
  /** Extra fields to add to the orbital-scoped entity clone. */
  fields?: EntityField[];
  /** Entity persistence mode. Defaults to `persistent` when omitted.
   *  See @almadar/core EntityPersistence: persistent | runtime. */
  persistence?: EntityPersistence;
  /** Rename the inlined trait at the call site. */
  traitName?: string;
  /** Per-key event rename map. Keys narrow to the trait's declared emit names. */
  events?: Partial<Record<StdNotificationPreferencesEventKey, string>>;
  /** Per-event effect replacement (keys are POST-rename event names). */
  effects?: Record<string, SExpr[]>;
  /** Replace the imported trait's `listens` array entirely. */
  listens?: TraitEventListener[];
  /** Set every emit's scope. */
  emitsScope?: 'internal' | 'external';
  /** Typed call-site config block — see the per-field interface. */
  config?: StdNotificationPreferencesConfig;
  /** URL path override for the (first) page. */
  pagePath?: string;
}

/** Trait descriptor: `NotificationPreferences.traits.PreferencesManage`. */
export function stdNotificationPreferencesPreferencesManageTrait(params: StdNotificationPreferencesParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.PreferencesManage`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Trait descriptor: `NotificationPreferences.traits.PreferenceCreate`. */
export function stdNotificationPreferencesPreferenceCreateTrait(params: StdNotificationPreferencesParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.PreferenceCreate`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Trait descriptor: `NotificationPreferences.traits.PreferenceEdit`. */
export function stdNotificationPreferencesPreferenceEditTrait(params: StdNotificationPreferencesParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.PreferenceEdit`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Trait descriptor: `NotificationPreferences.traits.PreferenceGate`. */
export function stdNotificationPreferencesPreferenceGateTrait(params: StdNotificationPreferencesParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.PreferenceGate`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Page descriptor: `NotificationPreferences.pages.NotificationPreferencesPage`. */
export function stdNotificationPreferencesPage(params: StdNotificationPreferencesParams): PageRefObject {
  return makePageRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.pages.NotificationPreferencesPage`,
    ...(params.pagePath !== undefined ? { path: params.pagePath } : {}),
    linkedEntity: params.entityName,
  });
}

/** Whole-orbital descriptor. */
export function stdNotificationPreferences(params: StdNotificationPreferencesParams): OrbitalDefinition {
  const entity: Entity = {
    name: params.entityName,
    fields: params.fields ?? [],
    ...(params.persistence !== undefined ? { persistence: params.persistence } : {}),
  };
  return makeOrbitalWithUses({
    name: 'NotificationPreferencesOrbital',
    uses: [{ from: BEHAVIOR_PATH, as: ALIAS }],
    entity,
    traits: [
      stdNotificationPreferencesPreferencesManageTrait(params),
      stdNotificationPreferencesPreferenceCreateTrait(params),
      stdNotificationPreferencesPreferenceEditTrait(params),
      stdNotificationPreferencesPreferenceGateTrait(params),
    ],
    pages: [
      stdNotificationPreferencesPage(params),
    ],
  });
}

type _StdNotificationPreferencesEntityName = 'NotificationPreference' | 'GateView' | 'ModalRecord';
type _StdNotificationPreferencesListenTraitName = 'PreferencesManage' | 'PreferenceCreate' | 'PreferenceEdit' | 'PreferenceGate';

/**
 * Tunable params for the NotificationPreferencesOrbital orbital.
 *
 * Canonical entity: NotificationPreference — overridable via
 * `entityName`. The factory threads the effective name through every
 * trait's `linkedEntity` binding; the `.orb` compiler's inline phase
 * auto-rewrites every `@Entity.x`, `["ref",X]`, `["fetch",X,…]`,
 * `["persist",…,X,…]` and payload type string accordingly.
 *
 * Override surface (mirrors `.lolo`'s native overrides 1:1):
 *   fields         — extra entity fields (appended)
 *   pagePath       — first-page URL override
 *   persistence    — entity persistence mode
 *   entityName     — rename the canonical entity
 *   collection     — override the derived collection key
 *   traitOverrides — per-imported-trait `config`, `linkedEntity`,
 *                    `events`, `name`, `emitsScope`, `listens`.
 *                    `effects` is NOT exposed — `.lolo` removed it
 *                    in Phase 9.5.H. Use `listens` via a sibling
 *                    trait to react to atom events.
 */
export interface StdNotificationPreferencesNotificationPreferencesOrbitalParams {
  /** Extra fields appended to the canonical entity. */
  fields?: EntityField[];
  /** URL path override for the orbital's first page. */
  pagePath?: string;
  /** Override the canonical entity persistence mode. */
  persistence?: EntityPersistence;
  /** Rename the canonical entity (PascalCase singular, ≤32 chars). */
  entityName?: string;
  /** Override derived collection key (defaults to plural(entityName).toLowerCase()). */
  collection?: string;
  /**
   * Per-imported-trait override surface keyed on each imported
   * trait's canonical `name`. Accepts every override `.lolo`
   * natively supports: `config`, `linkedEntity`, `events`,
   * `name`, `emitsScope`, `listens`. `effects` is excluded —
   * atom-owned (use `listens` via a sibling trait instead).
   */
  traitOverrides?: Partial<Record<
    'PreferenceCreate' | 'PreferenceEdit' | 'PreferencesManage' | 'PreferenceGate',
    Pick<MakeTraitRefOpts, 'config' | 'linkedEntity' | 'events' | 'name' | 'emitsScope' | 'listens'>
  >>;
}

/** `'Alias.traits.TraitName'` literal union of every trait NotificationPreferencesOrbital's `uses[]` exports. */
type _StdNotificationPreferencesNotificationPreferencesOrbitalUsesRef = 'Modal.traits.ModalRecordModal';

/** Per-orbital factory: builds the NotificationPreferencesOrbital orbital with consumer params. */
export function stdNotificationPreferencesNotificationPreferencesOrbital(params: StdNotificationPreferencesNotificationPreferencesOrbitalParams = {}): OrbitalDefinition {
  const collectionName = params.collection
    ?? (params.entityName ? `${params.entityName.toLowerCase()}s` : 'notificationPreferences');
  const built = makeOrbitalWithUses({
    name: 'NotificationPreferencesOrbital',
    uses: [
      {
        'as': 'Modal',
        'from': 'std/behaviors/std-modal',
      },
    ],
    entity: {
      name: 'NotificationPreference',
      collection: collectionName,
      persistence: params.persistence ?? 'persistent',
      fields: ((): EntityField[] => {
        const canonical: EntityField[] = [
          {
            'name': 'id',
            'required': true,
            'type': 'string',
          },
          {
            'description': 'The person this preference row belongs to.',
            'name': 'personId',
            'required': true,
            'synonyms': 'user, recipient, owner, account',
            'type': 'string',
          },
          {
            'default': '',
            'description': 'Event key this preference applies to (matches a notify listener\'s eventKey); blank = all events.',
            'name': 'eventKey',
            'synonyms': 'event, trigger, topic, subscription',
            'type': 'string',
          },
          {
            'default': 'in_app',
            'description': 'Delivery channel override for this person.',
            'name': 'channel',
            'synonyms': 'preferred channel, delivery method',
            'type': 'string',
            'values': [
              'in_app',
              'email',
              'push',
              'slack',
              'sms',
              'webhook',
            ],
          },
          {
            'default': 'instant',
            'description': 'Delivery mode: instant (default), digest (deferred to a batch cycle), or off (muted).',
            'name': 'mode',
            'synonyms': 'delivery mode, frequency, cadence, mute, defer',
            'type': 'string',
            'values': [
              'instant',
              'digest',
              'off',
            ],
          },
          {
            'default': '',
            'description': 'Quiet-hours window as "HH:MM-HH:MM" (e.g. 22:00-07:00); blank or equal start/end = disabled.',
            'name': 'quietHours',
            'synonyms': 'do not disturb, quiet window, night mode',
            'type': 'string',
          },
          {
            'default': 0,
            'description': 'Timestamp indicating when this preference row was created.',
            'name': 'createdAt',
            'synonyms': 'creation time, created',
            'type': 'number',
          },
          {
            'default': 0,
            'description': 'Timestamp indicating when this preference row was last updated.',
            'name': 'updatedAt',
            'synonyms': 'modified, last updated',
            'type': 'number',
          },
        ];
        const extras = params.fields ?? [];
        if (extras.length === 0) return canonical;
        const extraNames = new Set(extras.map((f) => f.name));
        return [...canonical.filter((f) => !extraNames.has(f.name)), ...extras];
      })(),
    } as Entity,
    auxiliaryEntities: [
      {
        'fields': [
          {
            'name': 'id',
            'required': true,
            'type': 'string',
          },
          {
            'default': '',
            'description': 'Scratch: personId of the consult currently in flight.',
            'name': 'personId',
            'synonyms': 'current person',
            'type': 'string',
          },
          {
            'default': '',
            'description': 'Scratch: effective event key of the consult currently in flight (payload eventKey, or the configured eventKey when the payload is blank).',
            'name': 'eventKey',
            'synonyms': 'current event key',
            'type': 'string',
          },
          {
            'default': '',
            'description': 'Scratch: resolved channel for the current consult.',
            'name': 'channel',
            'synonyms': 'resolved channel',
            'type': 'string',
          },
          {
            'default': '',
            'description': 'Scratch: resolved delivery mode for the current consult.',
            'name': 'mode',
            'synonyms': 'resolved mode',
            'type': 'string',
          },
          {
            'default': '',
            'description': 'Scratch: quiet-hours window of the matched row for the current consult; blank = none.',
            'name': 'quietHours',
            'synonyms': 'resolved quiet hours',
            'type': 'string',
          },
        ],
        'name': 'GateView',
        'persistence': 'runtime',
      },
    ] as EntityRef[],
    traits: [
      {
        'category': 'interaction',
        'config': {
          'tableLook': {
            'default': 'dense',
            'description': 'Layer 2 visual treatment for the preference data table rendered by this atom.',
            'label': 'Table look',
            'tier': 'presentation',
            'type': 'string',
            'values': [
              'dense',
              'spacious',
              'striped',
              'borderless',
              'card-rows',
            ],
          },
          'title': {
            'default': 'Notification preferences',
            'description': 'Heading shown above the preference list',
            'label': 'Section title',
            'tier': 'presentation',
            'type': 'string',
          },
        },
        'effectRow': [
          {
            'kind': 'fetch',
            'resource': 'NotificationPreference',
          },
          {
            'kind': 'persist',
            'resource': 'NotificationPreference',
          },
          {
            'kind': 'render-ui',
            'resource': 'main',
          },
          {
            'kind': 'render-ui',
            'resource': 'toast',
          },
        ],
        'emits': [
          {
            'description': 'Opens the blank preference modal.',
            'event': 'CREATE',
            'synonyms': 'add, new, insert',
            'tier': 'domain',
          },
          {
            'description': 'Opens a preference row in the edit modal.',
            'event': 'EDIT',
            'payloadSchema': [
              {
                'name': 'id',
                'required': true,
                'type': 'string',
              },
              {
                'entity': 'NotificationPreference',
                'name': 'row',
                'properties': [
                  {
                    'name': 'id',
                    'required': true,
                    'type': 'string',
                  },
                  {
                    'name': 'personId',
                    'required': true,
                    'type': 'string',
                  },
                  {
                    'name': 'eventKey',
                    'type': 'string',
                  },
                  {
                    'name': 'channel',
                    'type': 'string',
                  },
                  {
                    'name': 'mode',
                    'type': 'string',
                  },
                  {
                    'name': 'quietHours',
                    'type': 'string',
                  },
                  {
                    'name': 'createdAt',
                    'type': 'number',
                  },
                  {
                    'name': 'updatedAt',
                    'type': 'number',
                  },
                ],
                'type': 'object',
              },
            ],
            'synonyms': 'modify, update, change',
            'tier': 'domain',
          },
          {
            'description': 'Removes a preference row.',
            'event': 'DELETE',
            'payloadSchema': [
              {
                'name': 'id',
                'required': true,
                'type': 'string',
              },
              {
                'entity': 'NotificationPreference',
                'name': 'row',
                'properties': [
                  {
                    'name': 'id',
                    'required': true,
                    'type': 'string',
                  },
                  {
                    'name': 'personId',
                    'required': true,
                    'type': 'string',
                  },
                  {
                    'name': 'eventKey',
                    'type': 'string',
                  },
                  {
                    'name': 'channel',
                    'type': 'string',
                  },
                  {
                    'name': 'mode',
                    'type': 'string',
                  },
                  {
                    'name': 'quietHours',
                    'type': 'string',
                  },
                  {
                    'name': 'createdAt',
                    'type': 'number',
                  },
                  {
                    'name': 'updatedAt',
                    'type': 'number',
                  },
                ],
                'type': 'object',
              },
            ],
            'synonyms': 'remove, discard, clear',
            'tier': 'domain',
          },
          {
            'description': 'The preference collection finished loading.',
            'event': 'PreferencesLoaded',
            'payloadSchema': [
              {
                'entity': 'NotificationPreference',
                'name': 'data',
                'properties': [
                  {
                    'name': 'id',
                    'required': true,
                    'type': 'string',
                  },
                  {
                    'name': 'personId',
                    'required': true,
                    'type': 'string',
                  },
                  {
                    'name': 'eventKey',
                    'type': 'string',
                  },
                  {
                    'name': 'channel',
                    'type': 'string',
                  },
                  {
                    'name': 'mode',
                    'type': 'string',
                  },
                  {
                    'name': 'quietHours',
                    'type': 'string',
                  },
                  {
                    'name': 'createdAt',
                    'type': 'number',
                  },
                  {
                    'name': 'updatedAt',
                    'type': 'number',
                  },
                ],
                'type': '[object]',
              },
            ],
            'synonyms': 'loaded, fetched, retrieved',
            'tier': 'domain',
          },
          {
            'description': 'The preference collection failed to load.',
            'event': 'PreferencesLoadFailed',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
            'synonyms': 'error, failure, load error',
            'tier': 'internal',
          },
          {
            'description': 'A preference row persisted (create or update).',
            'event': 'PreferenceSaved',
            'payloadSchema': [
              {
                'name': 'id',
                'required': true,
                'type': 'string',
              },
            ],
            'synonyms': 'created, updated, persisted',
            'tier': 'domain',
          },
          {
            'description': 'A preference persist failed.',
            'event': 'PreferenceSaveFailed',
            'payloadSchema': [
              {
                'name': 'error',
                'type': 'string',
              },
              {
                'name': 'code',
                'type': 'string',
              },
            ],
            'synonyms': 'failed, error, unsuccessful',
            'tier': 'internal',
          },
          {
            'description': 'A preference row was deleted.',
            'event': 'PreferenceDeleted',
            'payloadSchema': [
              {
                'name': 'id',
                'required': true,
                'type': 'string',
              },
            ],
            'synonyms': 'removed, purged, discarded',
            'tier': 'domain',
          },
        ],
        'linkedEntity': 'NotificationPreference',
        'listens': [
          {
            'event': 'PREFERENCE_CREATED',
            'source': {
              'kind': 'trait',
              'trait': ('PreferenceCreate' satisfies _StdNotificationPreferencesListenTraitName),
            },
            'triggers': 'DO_CREATE',
          },
          {
            'event': 'PREFERENCE_UPDATED',
            'source': {
              'kind': 'trait',
              'trait': ('PreferenceEdit' satisfies _StdNotificationPreferencesListenTraitName),
            },
            'triggers': 'DO_UPDATE',
          },
        ],
        'name': 'PreferencesManage',
        'scope': 'collection',
        'stateMachine': {
          'events': [
            {
              'key': 'INIT',
              'name': 'Initialize',
            },
            {
              'description': 'The preference collection finished loading.',
              'key': 'PreferencesLoaded',
              'name': 'Preferences loaded',
              'payloadSchema': [
                {
                  'entity': 'NotificationPreference',
                  'name': 'data',
                  'properties': [
                    {
                      'name': 'id',
                      'required': true,
                      'type': 'string',
                    },
                    {
                      'name': 'personId',
                      'required': true,
                      'type': 'string',
                    },
                    {
                      'name': 'eventKey',
                      'type': 'string',
                    },
                    {
                      'name': 'channel',
                      'type': 'string',
                    },
                    {
                      'name': 'mode',
                      'type': 'string',
                    },
                    {
                      'name': 'quietHours',
                      'type': 'string',
                    },
                    {
                      'name': 'createdAt',
                      'type': 'number',
                    },
                    {
                      'name': 'updatedAt',
                      'type': 'number',
                    },
                  ],
                  'type': '[object]',
                },
              ],
              'synonyms': 'loaded, fetched, retrieved',
              'tier': 'domain',
            },
            {
              'description': 'The preference collection failed to load.',
              'key': 'PreferencesLoadFailed',
              'name': 'Preferences load failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
              'synonyms': 'error, failure, load error',
              'tier': 'internal',
            },
            {
              'description': 'Removes a preference row.',
              'key': 'DELETE',
              'name': 'Delete',
              'payloadSchema': [
                {
                  'name': 'id',
                  'required': true,
                  'type': 'string',
                },
                {
                  'entity': 'NotificationPreference',
                  'name': 'row',
                  'properties': [
                    {
                      'name': 'id',
                      'required': true,
                      'type': 'string',
                    },
                    {
                      'name': 'personId',
                      'required': true,
                      'type': 'string',
                    },
                    {
                      'name': 'eventKey',
                      'type': 'string',
                    },
                    {
                      'name': 'channel',
                      'type': 'string',
                    },
                    {
                      'name': 'mode',
                      'type': 'string',
                    },
                    {
                      'name': 'quietHours',
                      'type': 'string',
                    },
                    {
                      'name': 'createdAt',
                      'type': 'number',
                    },
                    {
                      'name': 'updatedAt',
                      'type': 'number',
                    },
                  ],
                  'type': 'object',
                },
              ],
              'synonyms': 'remove, discard, clear',
              'tier': 'domain',
            },
            {
              'description': 'Create persist requested; the modal\'s SAVE payload carries the full form row.',
              'key': 'DO_CREATE',
              'name': 'Do Create',
              'payloadSchema': [
                {
                  'entity': 'NotificationPreference',
                  'name': 'data',
                  'properties': [
                    {
                      'name': 'id',
                      'required': true,
                      'type': 'string',
                    },
                    {
                      'name': 'personId',
                      'required': true,
                      'type': 'string',
                    },
                    {
                      'name': 'eventKey',
                      'type': 'string',
                    },
                    {
                      'name': 'channel',
                      'type': 'string',
                    },
                    {
                      'name': 'mode',
                      'type': 'string',
                    },
                    {
                      'name': 'quietHours',
                      'type': 'string',
                    },
                    {
                      'name': 'createdAt',
                      'type': 'number',
                    },
                    {
                      'name': 'updatedAt',
                      'type': 'number',
                    },
                  ],
                  'required': true,
                  'type': 'object',
                },
              ],
              'synonyms': 'add, new, insert',
              'tier': 'internal',
            },
            {
              'description': 'Update persist requested; the modal\'s SAVE payload carries the full form row.',
              'key': 'DO_UPDATE',
              'name': 'Do Update',
              'payloadSchema': [
                {
                  'entity': 'NotificationPreference',
                  'name': 'data',
                  'properties': [
                    {
                      'name': 'id',
                      'required': true,
                      'type': 'string',
                    },
                    {
                      'name': 'personId',
                      'required': true,
                      'type': 'string',
                    },
                    {
                      'name': 'eventKey',
                      'type': 'string',
                    },
                    {
                      'name': 'channel',
                      'type': 'string',
                    },
                    {
                      'name': 'mode',
                      'type': 'string',
                    },
                    {
                      'name': 'quietHours',
                      'type': 'string',
                    },
                    {
                      'name': 'createdAt',
                      'type': 'number',
                    },
                    {
                      'name': 'updatedAt',
                      'type': 'number',
                    },
                  ],
                  'required': true,
                  'type': 'object',
                },
              ],
              'synonyms': 'modified, changed, refreshed',
              'tier': 'internal',
            },
            {
              'description': 'A preference row persisted (create or update).',
              'key': 'PreferenceSaved',
              'name': 'Preference saved',
              'payloadSchema': [
                {
                  'name': 'id',
                  'required': true,
                  'type': 'string',
                },
              ],
              'synonyms': 'created, updated, persisted',
              'tier': 'domain',
            },
            {
              'description': 'A preference row was deleted.',
              'key': 'PreferenceDeleted',
              'name': 'Preference deleted',
              'payloadSchema': [
                {
                  'name': 'id',
                  'required': true,
                  'type': 'string',
                },
              ],
              'synonyms': 'removed, purged, discarded',
              'tier': 'domain',
            },
            {
              'description': 'A preference persist failed.',
              'key': 'PreferenceSaveFailed',
              'name': 'Preference save failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'type': 'string',
                },
                {
                  'name': 'code',
                  'type': 'string',
                },
              ],
              'synonyms': 'failed, error, unsuccessful',
              'tier': 'internal',
            },
            {
              'description': 'Retries loading the preference collection after a failure.',
              'key': 'RETRY',
              'name': 'Retry',
              'synonyms': 'try again, reload',
              'tier': 'presentation',
            },
            {
              'description': 'Opens the blank preference modal.',
              'key': 'CREATE',
              'name': 'Create',
              'synonyms': 'add, new, insert',
              'tier': 'domain',
            },
            {
              'description': 'Opens a preference row in the edit modal.',
              'key': 'EDIT',
              'name': 'Edit',
              'payloadSchema': [
                {
                  'name': 'id',
                  'required': true,
                  'type': 'string',
                },
                {
                  'entity': 'NotificationPreference',
                  'name': 'row',
                  'properties': [
                    {
                      'name': 'id',
                      'required': true,
                      'type': 'string',
                    },
                    {
                      'name': 'personId',
                      'required': true,
                      'type': 'string',
                    },
                    {
                      'name': 'eventKey',
                      'type': 'string',
                    },
                    {
                      'name': 'channel',
                      'type': 'string',
                    },
                    {
                      'name': 'mode',
                      'type': 'string',
                    },
                    {
                      'name': 'quietHours',
                      'type': 'string',
                    },
                    {
                      'name': 'createdAt',
                      'type': 'number',
                    },
                    {
                      'name': 'updatedAt',
                      'type': 'number',
                    },
                  ],
                  'type': 'object',
                },
              ],
              'synonyms': 'modify, update, change',
              'tier': 'domain',
            },
          ],
          'states': [
            {
              'isInitial': true,
              'name': 'loading',
            },
            {
              'name': 'browsing',
            },
            {
              'name': 'error',
            },
          ],
          'transitions': [
            {
              'effects': [
                [
                  'fetch',
                  ('NotificationPreference' satisfies _StdNotificationPreferencesEntityName),
                  {
                    'emit': {
                      'failure': 'PreferencesLoadFailed',
                      'success': 'PreferencesLoaded',
                    },
                  },
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'align': 'center',
                    'children': [
                      {
                        'type': 'spinner',
                      },
                      {
                        'color': 'muted',
                        'content': 'Loading notification preferences…',
                        'type': 'typography',
                        'variant': 'caption',
                      },
                    ],
                    'className': 'py-12',
                    'direction': 'vertical',
                    'gap': 'md',
                    'type': 'stack',
                  },
                ],
              ],
              'event': 'INIT',
              'from': 'loading',
              'to': 'loading',
            },
            {
              'effects': [
                [
                  'render-ui',
                  'main',
                  {
                    'children': [
                      {
                        'children': [
                          {
                            'children': [
                              {
                                'name': 'bell',
                                'size': 'lg',
                                'type': 'icon',
                              },
                              {
                                'content': '@config.title',
                                'type': 'typography',
                                'variant': 'h3',
                              },
                            ],
                            'direction': 'horizontal',
                            'gap': 'sm',
                            'type': 'stack',
                          },
                          {
                            'action': 'CREATE',
                            'icon': 'plus',
                            'label': 'New preference',
                            'type': 'button',
                            'variant': 'primary',
                          },
                        ],
                        'direction': 'horizontal',
                        'gap': 'sm',
                        'justify': 'between',
                        'type': 'stack',
                      },
                      {
                        'type': 'divider',
                      },
                      {
                        'cols': 1,
                        'entity': '@payload.data',
                        'fields': [
                          {
                            'label': 'Person',
                            'name': 'personId',
                            'variant': 'h4',
                          },
                          {
                            'label': 'Event',
                            'name': 'eventKey',
                            'variant': 'caption',
                          },
                          {
                            'label': 'Channel',
                            'name': 'channel',
                            'variant': 'badge',
                          },
                          {
                            'label': 'Mode',
                            'name': 'mode',
                            'variant': 'badge',
                          },
                          {
                            'label': 'Quiet hours',
                            'name': 'quietHours',
                            'variant': 'caption',
                          },
                        ],
                        'gap': 'sm',
                        'itemActions': [
                          {
                            'event': 'EDIT',
                            'icon': 'pencil',
                            'label': 'Edit',
                            'variant': 'secondary',
                          },
                          {
                            'event': 'DELETE',
                            'icon': 'trash-2',
                            'label': 'Delete',
                            'variant': 'danger',
                          },
                        ],
                        'look': '@config.tableLook',
                        'type': 'data-grid',
                      },
                    ],
                    'direction': 'vertical',
                    'gap': 'md',
                    'type': 'stack',
                  },
                ],
              ],
              'event': 'PreferencesLoaded',
              'from': 'loading',
              'to': 'browsing',
            },
            {
              'effects': [
                [
                  'render-ui',
                  'main',
                  {
                    'align': 'center',
                    'children': [
                      {
                        'message': '@payload.error',
                        'type': 'alert',
                        'variant': 'error',
                      },
                      {
                        'action': 'RETRY',
                        'icon': 'rotate-ccw',
                        'label': 'Retry',
                        'type': 'button',
                        'variant': 'primary',
                      },
                    ],
                    'className': 'py-12',
                    'direction': 'vertical',
                    'gap': 'md',
                    'type': 'stack',
                  },
                ],
              ],
              'event': 'PreferencesLoadFailed',
              'from': 'loading',
              'to': 'error',
            },
            {
              'effects': [
                [
                  'fetch',
                  ('NotificationPreference' satisfies _StdNotificationPreferencesEntityName),
                  {
                    'emit': {
                      'failure': 'PreferencesLoadFailed',
                      'success': 'PreferencesLoaded',
                    },
                  },
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'size': 'sm',
                    'type': 'spinner',
                  },
                ],
              ],
              'event': 'INIT',
              'from': 'browsing',
              'to': 'loading',
            },
            {
              'effects': [
                [
                  'persist',
                  'delete',
                  ('NotificationPreference' satisfies _StdNotificationPreferencesEntityName),
                  '@payload.id',
                  {
                    'emit': {
                      'failure': 'PreferenceSaveFailed',
                      'success': 'PreferenceDeleted',
                    },
                  },
                ],
              ],
              'event': 'DELETE',
              'from': 'browsing',
              'to': 'browsing',
            },
            {
              'effects': [
                [
                  'persist',
                  'create',
                  ('NotificationPreference' satisfies _StdNotificationPreferencesEntityName),
                  '@payload.data',
                  {
                    'emit': {
                      'failure': 'PreferenceSaveFailed',
                      'success': 'PreferenceSaved',
                    },
                  },
                ],
              ],
              'event': 'DO_CREATE',
              'from': 'browsing',
              'to': 'browsing',
            },
            {
              'effects': [
                [
                  'persist',
                  'update',
                  ('NotificationPreference' satisfies _StdNotificationPreferencesEntityName),
                  '@payload.data',
                  {
                    'emit': {
                      'failure': 'PreferenceSaveFailed',
                      'success': 'PreferenceSaved',
                    },
                  },
                ],
              ],
              'event': 'DO_UPDATE',
              'from': 'browsing',
              'to': 'browsing',
            },
            {
              'effects': [
                [
                  'render-ui',
                  'toast',
                  {
                    'dismissible': true,
                    'message': 'Notification preference saved',
                    'type': 'alert',
                    'variant': 'success',
                  },
                ],
                [
                  'fetch',
                  ('NotificationPreference' satisfies _StdNotificationPreferencesEntityName),
                  {
                    'emit': {
                      'failure': 'PreferencesLoadFailed',
                      'success': 'PreferencesLoaded',
                    },
                  },
                ],
              ],
              'event': 'PreferenceSaved',
              'from': 'browsing',
              'to': 'loading',
            },
            {
              'effects': [
                [
                  'render-ui',
                  'toast',
                  {
                    'dismissible': true,
                    'message': 'Notification preference removed',
                    'type': 'alert',
                    'variant': 'info',
                  },
                ],
                [
                  'fetch',
                  ('NotificationPreference' satisfies _StdNotificationPreferencesEntityName),
                  {
                    'emit': {
                      'failure': 'PreferencesLoadFailed',
                      'success': 'PreferencesLoaded',
                    },
                  },
                ],
              ],
              'event': 'PreferenceDeleted',
              'from': 'browsing',
              'to': 'loading',
            },
            {
              'effects': [
                [
                  'render-ui',
                  'toast',
                  {
                    'dismissible': true,
                    'message': 'Could not save the notification preference',
                    'type': 'alert',
                    'variant': 'warning',
                  },
                ],
              ],
              'event': 'PreferenceSaveFailed',
              'from': 'browsing',
              'to': 'browsing',
            },
            {
              'effects': [
                [
                  'render-ui',
                  'main',
                  {
                    'align': 'center',
                    'children': [
                      {
                        'message': '@payload.error',
                        'type': 'alert',
                        'variant': 'error',
                      },
                      {
                        'action': 'RETRY',
                        'icon': 'rotate-ccw',
                        'label': 'Retry',
                        'type': 'button',
                        'variant': 'primary',
                      },
                    ],
                    'className': 'py-12',
                    'direction': 'vertical',
                    'gap': 'md',
                    'type': 'stack',
                  },
                ],
              ],
              'event': 'PreferencesLoadFailed',
              'from': 'browsing',
              'to': 'error',
            },
            {
              'effects': [
                [
                  'fetch',
                  ('NotificationPreference' satisfies _StdNotificationPreferencesEntityName),
                  {
                    'emit': {
                      'failure': 'PreferencesLoadFailed',
                      'success': 'PreferencesLoaded',
                    },
                  },
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'size': 'sm',
                    'type': 'spinner',
                  },
                ],
              ],
              'event': 'INIT',
              'from': 'error',
              'to': 'loading',
            },
            {
              'effects': [
                [
                  'fetch',
                  ('NotificationPreference' satisfies _StdNotificationPreferencesEntityName),
                  {
                    'emit': {
                      'failure': 'PreferencesLoadFailed',
                      'success': 'PreferencesLoaded',
                    },
                  },
                ],
                [
                  'render-ui',
                  'main',
                  {
                    'size': 'sm',
                    'type': 'spinner',
                  },
                ],
              ],
              'event': 'RETRY',
              'from': 'error',
              'to': 'loading',
            },
          ],
        },
      } satisfies Trait,
      makeTraitRef({
        'config': {
          'fields': {
            'default': [
              'personId',
              'eventKey',
              'channel',
              'mode',
              'quietHours',
            ],
            'type': 'unknown',
          },
          'icon': {
            'default': 'plus-circle',
            'type': 'unknown',
          },
          'mode': {
            'default': 'create',
            'type': 'unknown',
          },
          'title': {
            'default': 'New notification preference',
            'type': 'unknown',
          },
        },
        'events': {
          'OPEN': 'CREATE',
          'SAVE': 'PREFERENCE_CREATED',
        },
        'linkedEntity': 'NotificationPreference',
        'listens': [
          {
            'event': 'CREATE',
            'source': {
              'kind': 'trait',
              'trait': 'PreferencesManage',
            },
            'triggers': 'CREATE',
          },
        ],
        'name': 'PreferenceCreate',
        'ref': ('Modal.traits.ModalRecordModal' satisfies _StdNotificationPreferencesNotificationPreferencesOrbitalUsesRef),
      }),
      makeTraitRef({
        'config': {
          'fields': {
            'default': [
              'personId',
              'eventKey',
              'channel',
              'mode',
              'quietHours',
            ],
            'type': 'unknown',
          },
          'icon': {
            'default': 'pencil',
            'type': 'unknown',
          },
          'mode': {
            'default': 'edit',
            'type': 'unknown',
          },
          'title': {
            'default': 'Edit notification preference',
            'type': 'unknown',
          },
        },
        'events': {
          'OPEN': 'EDIT',
          'SAVE': 'PREFERENCE_UPDATED',
        },
        'linkedEntity': 'NotificationPreference',
        'listens': [
          {
            'event': 'EDIT',
            'source': {
              'kind': 'trait',
              'trait': 'PreferencesManage',
            },
            'triggers': 'EDIT',
          },
        ],
        'name': 'PreferenceEdit',
        'ref': ('Modal.traits.ModalRecordModal' satisfies _StdNotificationPreferencesNotificationPreferencesOrbitalUsesRef),
      }),
      {
        'category': 'lifecycle',
        'config': {
          'eventKey': {
            'default': '',
            'description': 'Stable key naming the event this gate checks preferences for (e.g. \'BudgetThreshold\' — the std-finance-tracker NotifyOnEventListener convention). A blank CHECK_PREFERENCE payload eventKey falls back to this value. Preference rows whose eventKey is blank apply to every event.',
            'label': 'Event key',
            'synonyms': 'preference key, event name, subscription key, notification topic',
            'tier': 'policy',
            'type': 'string',
          },
        },
        'effectRow': [
          {
            'kind': 'emit',
            'resource': 'PREFERENCE_RESOLVED',
          },
          {
            'kind': 'fetch',
            'resource': 'NotificationPreference',
          },
          {
            'kind': 'render-ui',
            'resource': 'toast',
          },
          {
            'kind': 'set',
            'resource': '@entity.channel',
          },
          {
            'kind': 'set',
            'resource': '@entity.eventKey',
          },
          {
            'kind': 'set',
            'resource': '@entity.mode',
          },
          {
            'kind': 'set',
            'resource': '@entity.personId',
          },
          {
            'kind': 'set',
            'resource': '@entity.quietHours',
          },
        ],
        'emits': [
          {
            'description': 'The gate\'s verdict for a CHECK_PREFERENCE consult: resolved channel and mode, and whether quiet hours suppress delivery right now. Fail-open: no row or failed lookup = { channel: in_app, mode: instant, suppressed: false }.',
            'event': 'PREFERENCE_RESOLVED',
            'payloadSchema': [
              {
                'name': 'personId',
                'type': 'string',
              },
              {
                'name': 'eventKey',
                'type': 'string',
              },
              {
                'name': 'channel',
                'type': 'string',
              },
              {
                'name': 'mode',
                'type': 'string',
              },
              {
                'name': 'suppressed',
                'type': 'boolean',
              },
            ],
            'scope': 'external',
            'synonyms': 'verdict, preference answer, gate result, resolved preference',
            'tier': 'domain',
          },
          {
            'description': 'NotificationPreference rows loaded; the arm filters to the (personId, eventKey) match and resolves the verdict',
            'event': 'PREFERENCE_ROWS_LOADED',
            'payloadSchema': [
              {
                'entity': 'NotificationPreference',
                'name': 'data',
                'properties': [
                  {
                    'name': 'id',
                    'required': true,
                    'type': 'string',
                  },
                  {
                    'name': 'personId',
                    'required': true,
                    'type': 'string',
                  },
                  {
                    'name': 'eventKey',
                    'type': 'string',
                  },
                  {
                    'name': 'channel',
                    'type': 'string',
                  },
                  {
                    'name': 'mode',
                    'type': 'string',
                  },
                  {
                    'name': 'quietHours',
                    'type': 'string',
                  },
                  {
                    'name': 'createdAt',
                    'type': 'number',
                  },
                  {
                    'name': 'updatedAt',
                    'type': 'number',
                  },
                ],
                'type': '[object]',
              },
            ],
            'tier': 'internal',
          },
          {
            'description': 'The preference fetch failed — the arm emits the fail-open verdict',
            'event': 'PREFERENCE_CHECK_FAILED',
            'payloadSchema': [
              {
                'name': 'error',
                'required': true,
                'type': 'string',
              },
            ],
            'tier': 'internal',
          },
        ],
        'linkedEntity': 'GateView',
        'name': 'PreferenceGate',
        'scope': 'instance',
        'stateMachine': {
          'events': [
            {
              'description': 'Consult the gate for a person\'s effective notification preference.',
              'key': 'CHECK_PREFERENCE',
              'name': 'Check Preference',
              'payloadSchema': [
                {
                  'name': 'personId',
                  'type': 'string',
                },
                {
                  'name': 'eventKey',
                  'type': 'string',
                },
              ],
              'synonyms': 'check preference, resolve preference, should notify, gate notification',
              'tier': 'domain',
            },
            {
              'description': 'NotificationPreference rows loaded; the arm filters to the (personId, eventKey) match and resolves the verdict',
              'key': 'PREFERENCE_ROWS_LOADED',
              'name': 'Preference Rows Loaded',
              'payloadSchema': [
                {
                  'entity': 'NotificationPreference',
                  'name': 'data',
                  'properties': [
                    {
                      'name': 'id',
                      'required': true,
                      'type': 'string',
                    },
                    {
                      'name': 'personId',
                      'required': true,
                      'type': 'string',
                    },
                    {
                      'name': 'eventKey',
                      'type': 'string',
                    },
                    {
                      'name': 'channel',
                      'type': 'string',
                    },
                    {
                      'name': 'mode',
                      'type': 'string',
                    },
                    {
                      'name': 'quietHours',
                      'type': 'string',
                    },
                    {
                      'name': 'createdAt',
                      'type': 'number',
                    },
                    {
                      'name': 'updatedAt',
                      'type': 'number',
                    },
                  ],
                  'type': '[object]',
                },
              ],
              'tier': 'internal',
            },
            {
              'description': 'The preference fetch failed — the arm emits the fail-open verdict',
              'key': 'PREFERENCE_CHECK_FAILED',
              'name': 'Preference Check Failed',
              'payloadSchema': [
                {
                  'name': 'error',
                  'required': true,
                  'type': 'string',
                },
              ],
              'tier': 'internal',
            },
            {
              'description': 'The gate\'s verdict for a CHECK_PREFERENCE consult: resolved channel and mode, and whether quiet hours suppress delivery right now. Fail-open: no row or failed lookup = { channel: in_app, mode: instant, suppressed: false }.',
              'key': 'PREFERENCE_RESOLVED',
              'name': 'Preference Resolved',
              'payloadSchema': [
                {
                  'name': 'personId',
                  'type': 'string',
                },
                {
                  'name': 'eventKey',
                  'type': 'string',
                },
                {
                  'name': 'channel',
                  'type': 'string',
                },
                {
                  'name': 'mode',
                  'type': 'string',
                },
                {
                  'name': 'suppressed',
                  'type': 'boolean',
                },
              ],
              'synonyms': 'verdict, preference answer, gate result, resolved preference',
              'tier': 'domain',
            },
          ],
          'states': [
            {
              'isInitial': true,
              'name': 'idle',
            },
          ],
          'transitions': [
            {
              'effects': [
                [
                  'set',
                  '@entity.personId',
                  '@payload.personId',
                ],
                [
                  'set',
                  '@entity.eventKey',
                  [
                    'if',
                    [
                      '=',
                      '@payload.eventKey',
                      '',
                    ],
                    '@config.eventKey',
                    '@payload.eventKey',
                  ],
                ],
                [
                  'fetch',
                  ('NotificationPreference' satisfies _StdNotificationPreferencesEntityName),
                  {
                    'emit': {
                      'failure': 'PREFERENCE_CHECK_FAILED',
                      'success': 'PREFERENCE_ROWS_LOADED',
                    },
                  },
                ],
              ],
              'event': 'CHECK_PREFERENCE',
              'from': 'idle',
              'to': 'idle',
            },
            {
              'effects': [
                [
                  'set',
                  '@entity.channel',
                  [
                    'if',
                    [
                      '=',
                      [
                        'array/len',
                        [
                          'array/filter',
                          '@payload.data',
                          [
                            'fn',
                            'p',
                            [
                              'and',
                              [
                                '=',
                                [
                                  'object/get',
                                  '@p',
                                  'personId',
                                ],
                                '@entity.personId',
                              ],
                              [
                                'or',
                                [
                                  '=',
                                  [
                                    'object/get',
                                    '@p',
                                    'eventKey',
                                  ],
                                  '',
                                ],
                                [
                                  '=',
                                  [
                                    'object/get',
                                    '@p',
                                    'eventKey',
                                  ],
                                  '@entity.eventKey',
                                ],
                              ],
                            ],
                          ],
                        ],
                      ],
                      0,
                    ],
                    'in_app',
                    [
                      'object/get',
                      [
                        'array/first',
                        [
                          'array/filter',
                          '@payload.data',
                          [
                            'fn',
                            'p',
                            [
                              'and',
                              [
                                '=',
                                [
                                  'object/get',
                                  '@p',
                                  'personId',
                                ],
                                '@entity.personId',
                              ],
                              [
                                'or',
                                [
                                  '=',
                                  [
                                    'object/get',
                                    '@p',
                                    'eventKey',
                                  ],
                                  '',
                                ],
                                [
                                  '=',
                                  [
                                    'object/get',
                                    '@p',
                                    'eventKey',
                                  ],
                                  '@entity.eventKey',
                                ],
                              ],
                            ],
                          ],
                        ],
                      ],
                      'channel',
                    ],
                  ],
                ],
                [
                  'set',
                  '@entity.mode',
                  [
                    'if',
                    [
                      '=',
                      [
                        'array/len',
                        [
                          'array/filter',
                          '@payload.data',
                          [
                            'fn',
                            'p',
                            [
                              'and',
                              [
                                '=',
                                [
                                  'object/get',
                                  '@p',
                                  'personId',
                                ],
                                '@entity.personId',
                              ],
                              [
                                'or',
                                [
                                  '=',
                                  [
                                    'object/get',
                                    '@p',
                                    'eventKey',
                                  ],
                                  '',
                                ],
                                [
                                  '=',
                                  [
                                    'object/get',
                                    '@p',
                                    'eventKey',
                                  ],
                                  '@entity.eventKey',
                                ],
                              ],
                            ],
                          ],
                        ],
                      ],
                      0,
                    ],
                    'instant',
                    [
                      'object/get',
                      [
                        'array/first',
                        [
                          'array/filter',
                          '@payload.data',
                          [
                            'fn',
                            'p',
                            [
                              'and',
                              [
                                '=',
                                [
                                  'object/get',
                                  '@p',
                                  'personId',
                                ],
                                '@entity.personId',
                              ],
                              [
                                'or',
                                [
                                  '=',
                                  [
                                    'object/get',
                                    '@p',
                                    'eventKey',
                                  ],
                                  '',
                                ],
                                [
                                  '=',
                                  [
                                    'object/get',
                                    '@p',
                                    'eventKey',
                                  ],
                                  '@entity.eventKey',
                                ],
                              ],
                            ],
                          ],
                        ],
                      ],
                      'mode',
                    ],
                  ],
                ],
                [
                  'set',
                  '@entity.quietHours',
                  [
                    'if',
                    [
                      '=',
                      [
                        'array/len',
                        [
                          'array/filter',
                          '@payload.data',
                          [
                            'fn',
                            'p',
                            [
                              'and',
                              [
                                '=',
                                [
                                  'object/get',
                                  '@p',
                                  'personId',
                                ],
                                '@entity.personId',
                              ],
                              [
                                'or',
                                [
                                  '=',
                                  [
                                    'object/get',
                                    '@p',
                                    'eventKey',
                                  ],
                                  '',
                                ],
                                [
                                  '=',
                                  [
                                    'object/get',
                                    '@p',
                                    'eventKey',
                                  ],
                                  '@entity.eventKey',
                                ],
                              ],
                            ],
                          ],
                        ],
                      ],
                      0,
                    ],
                    '',
                    [
                      'object/get',
                      [
                        'array/first',
                        [
                          'array/filter',
                          '@payload.data',
                          [
                            'fn',
                            'p',
                            [
                              'and',
                              [
                                '=',
                                [
                                  'object/get',
                                  '@p',
                                  'personId',
                                ],
                                '@entity.personId',
                              ],
                              [
                                'or',
                                [
                                  '=',
                                  [
                                    'object/get',
                                    '@p',
                                    'eventKey',
                                  ],
                                  '',
                                ],
                                [
                                  '=',
                                  [
                                    'object/get',
                                    '@p',
                                    'eventKey',
                                  ],
                                  '@entity.eventKey',
                                ],
                              ],
                            ],
                          ],
                        ],
                      ],
                      'quietHours',
                    ],
                  ],
                ],
                [
                  'emit',
                  'PREFERENCE_RESOLVED',
                  {
                    'channel': '@entity.channel',
                    'eventKey': '@entity.eventKey',
                    'mode': '@entity.mode',
                    'personId': '@entity.personId',
                    'suppressed': [
                      'and',
                      [
                        'str/includes',
                        '@entity.quietHours',
                        '-',
                      ],
                      [
                        '!=',
                        [
                          'str/slice',
                          [
                            'array/first',
                            [
                              'str/split',
                              '@entity.quietHours',
                              '-',
                            ],
                          ],
                          0,
                          2,
                        ],
                        [
                          'str/slice',
                          [
                            'array/nth',
                            [
                              'str/split',
                              '@entity.quietHours',
                              '-',
                            ],
                            1,
                          ],
                          0,
                          2,
                        ],
                      ],
                      [
                        'if',
                        [
                          '<',
                          [
                            'str/slice',
                            [
                              'array/first',
                              [
                                'str/split',
                                '@entity.quietHours',
                                '-',
                              ],
                            ],
                            0,
                            2,
                          ],
                          [
                            'str/slice',
                            [
                              'array/nth',
                              [
                                'str/split',
                                '@entity.quietHours',
                                '-',
                              ],
                              1,
                            ],
                            0,
                            2,
                          ],
                        ],
                        [
                          'and',
                          [
                            '>=',
                            [
                              'time/hour',
                              '@now',
                            ],
                            [
                              'str/slice',
                              [
                                'array/first',
                                [
                                  'str/split',
                                  '@entity.quietHours',
                                  '-',
                                ],
                              ],
                              0,
                              2,
                            ],
                          ],
                          [
                            '<',
                            [
                              'time/hour',
                              '@now',
                            ],
                            [
                              'str/slice',
                              [
                                'array/nth',
                                [
                                  'str/split',
                                  '@entity.quietHours',
                                  '-',
                                ],
                                1,
                              ],
                              0,
                              2,
                            ],
                          ],
                        ],
                        [
                          'or',
                          [
                            '>=',
                            [
                              'time/hour',
                              '@now',
                            ],
                            [
                              'str/slice',
                              [
                                'array/first',
                                [
                                  'str/split',
                                  '@entity.quietHours',
                                  '-',
                                ],
                              ],
                              0,
                              2,
                            ],
                          ],
                          [
                            '<',
                            [
                              'time/hour',
                              '@now',
                            ],
                            [
                              'str/slice',
                              [
                                'array/nth',
                                [
                                  'str/split',
                                  '@entity.quietHours',
                                  '-',
                                ],
                                1,
                              ],
                              0,
                              2,
                            ],
                          ],
                        ],
                      ],
                    ],
                  },
                ],
              ],
              'event': 'PREFERENCE_ROWS_LOADED',
              'from': 'idle',
              'to': 'idle',
            },
            {
              'effects': [
                [
                  'emit',
                  'PREFERENCE_RESOLVED',
                  {
                    'channel': 'in_app',
                    'eventKey': '@entity.eventKey',
                    'mode': 'instant',
                    'personId': '@entity.personId',
                    'suppressed': false,
                  },
                ],
                [
                  'render-ui',
                  'toast',
                  {
                    'message': '@payload.error',
                    'type': 'alert',
                    'variant': 'error',
                  },
                ],
              ],
              'event': 'PREFERENCE_CHECK_FAILED',
              'from': 'idle',
              'to': 'idle',
            },
          ],
        },
      } satisfies Trait,
    ],
    pages: [
      {
        'name': 'NotificationPreferencesPage',
        'path': '/notification-preferences',
        'traits': [
          {
            'ref': 'PreferencesManage',
          },
          {
            'ref': 'PreferenceCreate',
          },
          {
            'ref': 'PreferenceEdit',
          },
          {
            'ref': 'PreferenceGate',
          },
        ],
      } satisfies Page,
    ],
  });
  type _OrbTrait = OrbitalDefinition["traits"][number];
  type _OrbPage = NonNullable<OrbitalDefinition["pages"]>[number];
  type _RefOverride = Pick<MakeTraitRefOpts, "config" | "linkedEntity" | "events" | "name" | "emitsScope" | "listens">;
  if (built.traits && params.traitOverrides !== undefined) {
    built.traits = (built.traits as _OrbTrait[]).map((t): _OrbTrait => {
      if (!t || typeof t !== "object") return t;
      const tr = t as TraitReference & { name?: string };
      // Match by name so inline traits (no `ref`) and
      // reference traits (with `ref`) both pick up the
      // override surface keyed on the trait's `name`.
      if (typeof tr.name !== "string") return t;
      const overrides = params.traitOverrides as Record<string, _RefOverride | undefined> | undefined;
      const override = overrides?.[tr.name];
      if (!override) return t;
      const merged: TraitReference = { ...tr };
      if (override.config !== undefined) {
        merged.config = mergeCallSiteConfigOverrides(tr.config ?? {}, override.config);
      }
      if (override.linkedEntity !== undefined) merged.linkedEntity = override.linkedEntity;
      if (override.events !== undefined) merged.events = { ...(tr.events ?? {}), ...override.events };
      if (override.emitsScope !== undefined) merged.emitsScope = override.emitsScope;
      if (override.listens !== undefined) merged.listens = override.listens;
      return merged;
    });
  }
  if (built.pages && params.pagePath !== undefined) {
    built.pages = (built.pages as _OrbPage[]).map((p, idx) => {
      if (!p || typeof p !== "object") return p;
      if (idx !== 0) return p;
      const out = { ...p } as _OrbPage & { path?: string };
      out.path = params.pagePath;
      return out;
    });
  }
  return built;
}

/** Manifest — describes the params surface of stdNotificationPreferencesNotificationPreferencesOrbital. */
export const StdNotificationPreferencesNotificationPreferencesOrbitalManifest = {
  organism: 'std-notification-preferences',
  orbitalName: 'NotificationPreferencesOrbital',
  paramFields: [
    {
      'name': 'fields',
      'type': 'EntityField[]',
      'description': 'Extra fields appended to the canonical entity.',
    },
    {
      'name': 'pagePath',
      'type': 'string',
      'description': 'URL override for the orbital first page.',
    },
    {
      'name': 'persistence',
      'type': '\'persistent\' | \'runtime\'',
      'description': 'Override the canonical entity persistence mode.',
    },
    {
      'name': 'entityName',
      'type': 'string',
      'description': 'Rename the canonical entity. PascalCase singular, ≤32 chars. Threads through every trait\'s linkedEntity binding; compiler rewrites @Entity.x refs.',
    },
    {
      'name': 'collection',
      'type': 'string',
      'description': 'Override derived collection key. Defaults to plural(entityName).toLowerCase().',
    },
    {
      'name': 'traitOverrides',
      'type': 'Partial<Record<TraitName, { config?, linkedEntity?, events?, name?, emitsScope?, listens? }>>',
      'description': '.lolo\'s native trait-composition surface 1:1: per-imported-trait config, linkedEntity, events, name, emitsScope, listens. effects is excluded (atom-owned; use listens via a sibling trait).',
    },
  ] as const,
  traitNames: [
    'PreferenceCreate',
    'PreferenceEdit',
  ] as const,
  inlineTraitNames: [
    'PreferencesManage',
    'PreferenceGate',
  ] as const,
};

/** Typed guard — runtime validates StdNotificationPreferencesNotificationPreferencesOrbitalParams keys. */
export function isStdNotificationPreferencesNotificationPreferencesOrbitalParams(p: object): p is StdNotificationPreferencesNotificationPreferencesOrbitalParams {
  type _OverrideRecord = NonNullable<StdNotificationPreferencesNotificationPreferencesOrbitalParams['traitOverrides']>;
  const obj = p as { traitOverrides?: _OverrideRecord };
  if (obj.traitOverrides !== undefined) {
    if (typeof obj.traitOverrides !== "object" || obj.traitOverrides === null) return false;
    const allowed: readonly string[] = [
      ...StdNotificationPreferencesNotificationPreferencesOrbitalManifest.traitNames,
      ...StdNotificationPreferencesNotificationPreferencesOrbitalManifest.inlineTraitNames,
    ];
    for (const k of Object.keys(obj.traitOverrides)) {
      if (!allowed.includes(k)) return false;
    }
  }
  return true;
}
