/**
 * std-data-erasure — std-data-erasure — GDPR Art. 17 right-to-be-forgotten queue. Tracks ErasureRequest rows through pending → grace → executed lifecycle with Cancel during grace. v1.0 ships the request lifecycle UI + knob set; auto-emit of ExecuteErasure after grace lands in v1.1 (loop-with-emit gap — docs/Almadar_Std_Factories.md). Target app/ atoms then own the actual delete or piiFields scrub via an ExecuteErasure listener.
 *
 * Autogenerated by almadar-sync std-ts from
 * packages/almadar-std/behaviors/registry/atoms/std-data-erasure.orb.
 *
 * This is a thin descriptor layer over the canonical .orb. The exported
 * functions return TraitReference / PageRefObject / OrbitalDefinition
 * payloads that reference the sibling .orb via `uses:` + `ref:`. The
 * compiler's inline phase materialises the real trait at build time.
 *
 * Do not hand-edit — regenerate via
 *   npx almadar-sync std-ts --only=std-data-erasure
 *
 * @level atom
 * @packageDocumentation
 */

import type { TraitReference, PageRefObject, OrbitalDefinition, Entity, EntityField, EntityPersistence, TraitConfig, TraitFieldRef, EntityRow, SExpr, TraitEventListener, Trait, StateMachine, Page } from '@almadar/core/types';
import type { MakeTraitRefOpts } from '@almadar/core/builders';
import { makeTraitRef, makePageRef, makeOrbitalWithUses } from '@almadar/core/builders';
import { mergeCallSiteConfigOverrides } from '../../../../factory-runtime/apply-params-to-orb.js';

const BEHAVIOR_PATH = 'std/behaviors/std-data-erasure';
const ALIAS = 'DataErasure';

/**
 * Closed set of event keys this trait recognises —
 * derived from the .orb's `stateMachine.events[]` block
 * (transition triggers + emit names). Use as the key type
 * when passing an `events:` rename map at the call site.
 */
export type StdDataErasureEventKey = 'CANCEL_ERASURE' | 'CLOSE' | 'ErasureLoadFailed' | 'ErasureLoaded' | 'ErasureSaveFailed' | 'ErasureSaved' | 'ExecScanFailed' | 'ExecScanLoaded' | 'ExecStepped' | 'ExecuteErasure' | 'INIT' | 'OPEN';

/**
 * Payload shape for the `CANCEL_ERASURE` event.
 */
export interface StdDataErasureCancelErasurePayload {
  id: string;
  row?: EntityRow;
}

/**
 * Payload shape for the `ErasureLoaded` event.
 */
export interface StdDataErasureErasureLoadedPayload {
  data?: EntityRow[];
}

/**
 * Payload shape for the `ErasureLoadFailed` event.
 */
export interface StdDataErasureErasureLoadFailedPayload {
  error?: string;
  code?: string;
}

/**
 * Payload shape for the `ErasureSaved` event.
 */
export interface StdDataErasureErasureSavedPayload {
  row?: EntityRow;
}

/**
 * Payload shape for the `ErasureSaveFailed` event.
 */
export interface StdDataErasureErasureSaveFailedPayload {
  error?: string;
  code?: string;
}

/**
 * Payload shape for the `ExecuteErasure` event.
 */
export interface StdDataErasureExecuteErasurePayload {
  requestId?: string;
  targetEntity?: string;
  subjectId?: string;
}

/**
 * Payload shape for the `ExecScanLoaded` event.
 */
export interface StdDataErasureExecScanLoadedPayload {
  data?: EntityRow[];
}

/**
 * Payload shape for the `ExecScanFailed` event.
 */
export interface StdDataErasureExecScanFailedPayload {
  error?: string;
  code?: string;
}

/**
 * Payload shape for the `ExecStepped` event.
 */
export interface StdDataErasureExecSteppedPayload {
  id?: string;
}

/**
 * Typed call-site config block for this trait — every
 * field maps to a `config { ... }` entry in the source
 * .lolo. The agent fills these to specialise the trait
 * without modifying its state-machine topology.
 */
export interface StdDataErasureConfig {
  /** Default: `"anonymize"` */
  anonymizeVsDelete?: 'anonymize' | 'delete';
  /** Default: `false` */
  enabled?: boolean;
  /** Default: `30` */
  gracePeriodDays?: number;
  /** Default: `[]` */
  piiFields?: string[];
  /** Default: `"modal"` */
  reviewSlot?: unknown;
  /** Default: `"dense"` */
  tableLook?: 'dense' | 'spacious' | 'striped' | 'borderless' | 'card-rows';
  /** Default: `""` */
  targetEntity?: string;
}

/**
 * Params for the std-data-erasure descriptor helpers.
 *
 * `entityName` binds every trait/page reference's `linkedEntity`.
 * The optional override fields mirror TraitReference / PageRefObject
 * fields and are forwarded to `makeTraitRef` / `makePageRef`.
 */
export interface StdDataErasureParams {
  entityName: string;
  /** Extra fields to add to the orbital-scoped entity clone. */
  fields?: EntityField[];
  /** Entity persistence mode. Defaults to `persistent` when omitted.
   *  See @almadar/core EntityPersistence: persistent | runtime. */
  persistence?: EntityPersistence;
  /** Rename the inlined trait at the call site. */
  traitName?: string;
  /** Per-key event rename map. Keys narrow to the trait's declared emit names. */
  events?: Partial<Record<StdDataErasureEventKey, string>>;
  /** Per-event effect replacement (keys are POST-rename event names). */
  effects?: Record<string, SExpr[]>;
  /** Replace the imported trait's `listens` array entirely. */
  listens?: TraitEventListener[];
  /** Set every emit's scope. */
  emitsScope?: 'internal' | 'external';
  /** Typed call-site config block — see the per-field interface. */
  config?: StdDataErasureConfig;
  /** URL path override for the (first) page. */
  pagePath?: string;
}

/** Trait descriptor: `DataErasure.traits.ErasureWorkflow`. */
export function stdDataErasureErasureWorkflowTrait(params: StdDataErasureParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.ErasureWorkflow`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Trait descriptor: `DataErasure.traits.InlineSpinnerRender1`. */
export function stdDataErasureInlineSpinnerRender1Trait(params: StdDataErasureParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.InlineSpinnerRender1`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Trait descriptor: `DataErasure.traits.InlineTypographyRender2`. */
export function stdDataErasureInlineTypographyRender2Trait(params: StdDataErasureParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.InlineTypographyRender2`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Trait descriptor: `DataErasure.traits.InlineIconRender3`. */
export function stdDataErasureInlineIconRender3Trait(params: StdDataErasureParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.InlineIconRender3`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Trait descriptor: `DataErasure.traits.InlineTypographyRender4`. */
export function stdDataErasureInlineTypographyRender4Trait(params: StdDataErasureParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.InlineTypographyRender4`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Trait descriptor: `DataErasure.traits.InlineButtonRender5`. */
export function stdDataErasureInlineButtonRender5Trait(params: StdDataErasureParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.InlineButtonRender5`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Trait descriptor: `DataErasure.traits.InlineDividerRender6`. */
export function stdDataErasureInlineDividerRender6Trait(params: StdDataErasureParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.InlineDividerRender6`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Trait descriptor: `DataErasure.traits.InlineAlertRender7`. */
export function stdDataErasureInlineAlertRender7Trait(params: StdDataErasureParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.InlineAlertRender7`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Trait descriptor: `DataErasure.traits.InlineAlertRender8`. */
export function stdDataErasureInlineAlertRender8Trait(params: StdDataErasureParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.InlineAlertRender8`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Trait descriptor: `DataErasure.traits.InlineSpinnerRender9`. */
export function stdDataErasureInlineSpinnerRender9Trait(params: StdDataErasureParams): TraitReference {
  return makeTraitRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.traits.InlineSpinnerRender9`,
    linkedEntity: params.entityName,
    ...(params.traitName !== undefined ? { name: params.traitName } : {}),
    ...(params.events !== undefined ? { events: params.events as Record<string, string> } : {}),
    ...(params.effects !== undefined ? { effects: params.effects } : {}),
    ...(params.listens !== undefined ? { listens: params.listens } : {}),
    ...(params.emitsScope !== undefined ? { emitsScope: params.emitsScope } : {}),
    ...(params.config !== undefined ? { config: params.config as TraitConfig } : {}),
  });
}

/** Page descriptor: `DataErasure.pages.ErasureWorkflowPage`. */
export function stdDataErasurePage(params: StdDataErasureParams): PageRefObject {
  return makePageRef({
    from: BEHAVIOR_PATH,
    ref: `${ALIAS}.pages.ErasureWorkflowPage`,
    ...(params.pagePath !== undefined ? { path: params.pagePath } : {}),
    linkedEntity: params.entityName,
  });
}

/** Whole-orbital descriptor. */
export function stdDataErasure(params: StdDataErasureParams): OrbitalDefinition {
  const entity: Entity = {
    name: params.entityName,
    fields: params.fields ?? [],
    ...(params.persistence !== undefined ? { persistence: params.persistence } : {}),
  };
  return makeOrbitalWithUses({
    name: 'DataErasureOrbital',
    uses: [{ from: BEHAVIOR_PATH, as: ALIAS }],
    entity,
    traits: [
      stdDataErasureErasureWorkflowTrait(params),
      stdDataErasureInlineSpinnerRender1Trait(params),
      stdDataErasureInlineTypographyRender2Trait(params),
      stdDataErasureInlineIconRender3Trait(params),
      stdDataErasureInlineTypographyRender4Trait(params),
      stdDataErasureInlineButtonRender5Trait(params),
      stdDataErasureInlineDividerRender6Trait(params),
      stdDataErasureInlineAlertRender7Trait(params),
      stdDataErasureInlineAlertRender8Trait(params),
      stdDataErasureInlineSpinnerRender9Trait(params),
    ],
    pages: [
      stdDataErasurePage(params),
    ],
  });
}
